<a href="https://colab.research.google.com/github/kartik815/Amazon-ML-Challenge-2026/blob/main/notebooks/02_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import os
import pandas as pd

DRIVE_ROOT = "/content/drive/MyDrive/Amazon ML Challenge 2026"

DATASET_ROOT = os.path.join(
    DRIVE_ROOT,
    "01_Dataset",
    "6ab10eb3b23ba_student_resource",
    "student_resource",
    "dataset"
)

TRAIN_ROOT = os.path.join(DATASET_ROOT, "train")
TEST_ROOT = os.path.join(DATASET_ROOT, "test")

print("Train path:", TRAIN_ROOT)
print("Test path:", TEST_ROOT)

print("\nTrain files:")
print(os.listdir(TRAIN_ROOT))

print("\nTest files:")
print(os.listdir(TEST_ROOT))

Train path: /content/drive/MyDrive/Amazon ML Challenge 2026/01_Dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train
Test path: /content/drive/MyDrive/Amazon ML Challenge 2026/01_Dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/test

Train files:
['train_source3.tsv', 'train_source2.tsv', 'train_source1.tsv', 'train_ground_truth.tsv']

Test files:
['test_source3.tsv', 'test_source2.tsv', 'test_source1.tsv']

In [2]:
train_s1 = pd.read_csv(
    os.path.join(TRAIN_ROOT, "train_source1.tsv"),
    sep="\t"
)

train_s2 = pd.read_csv(
    os.path.join(TRAIN_ROOT, "train_source2.tsv"),
    sep="\t"
)

train_s3 = pd.read_csv(
    os.path.join(TRAIN_ROOT, "train_source3.tsv"),
    sep="\t"
)

ground_truth = pd.read_csv(
    os.path.join(TRAIN_ROOT, "train_ground_truth.tsv"),
    sep="\t"
)

test_s1 = pd.read_csv(
    os.path.join(TEST_ROOT, "test_source1.tsv"),
    sep="\t"
)

test_s2 = pd.read_csv(
    os.path.join(TEST_ROOT, "test_source2.tsv"),
    sep="\t"
)

test_s3 = pd.read_csv(
    os.path.join(TEST_ROOT, "test_source3.tsv"),
    sep="\t"
)

print("Loaded successfully!")

Loaded successfully!

In [3]:
datasets = {
    "Train Source 1": train_s1,
    "Train Source 2": train_s2,
    "Train Source 3": train_s3,
    "Ground Truth": ground_truth,
    "Test Source 1": test_s1,
    "Test Source 2": test_s2,
    "Test Source 3": test_s3,
}

for name, df in datasets.items():
    print(f"{name:20} : {df.shape[0]:>8} rows × {df.shape[1]} columns")

Train Source 1       :  2206821 rows × 4 columns
Train Source 2       :  5034616 rows × 4 columns
Train Source 3       :  5285603 rows × 4 columns
Ground Truth         :  2206821 rows × 2 columns
Test Source 1        :  1732544 rows × 4 columns
Test Source 2        :  4887273 rows × 4 columns
Test Source 3        :  5082316 rows × 4 columns

In [4]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.columns.tolist())

============================================================
Train Source 1
============================================================
['entity_id', 'business_name', 'business_address', 'country']

============================================================
Train Source 2
============================================================
['entity_id', 'business_name', 'business_address', 'country']

============================================================
Train Source 3
============================================================
['entity_id', 'business_name', 'business_address', 'country']

============================================================
Ground Truth
============================================================
['source1_entity_id', 'matched_entity_ids']

============================================================
Test Source 1
============================================================
['entity_id', 'business_name', 'business_address', 'country']

============================================================
Test Source 2
============================================================
['entity_id', 'business_name', 'business_address', 'country']

============================================================
Test Source 3
============================================================
['entity_id', 'business_name', 'business_address', 'country']

In [5]:
display(train_s1.head(10))

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India
5,S1-851869949,Custom Wealth Services LLC,"OH, Columbus, 5559 Orville Avenue",US
6,S1-785847572,Consulting Nyasa Nursing Private Limited,"2505, Tower 1, Oakwood, Runwal Greens, Mulund ...",India
7,S1-27541239,Nexus Anchor Rain,"1111 Church Street, Unit 2007, Nashville, TN",US
8,S1-629417405,Moore Bitwise Inc,"337 Oakland Avenue, Michigan City, IN",US
9,S1-22305073,Dermatology Green Medicine,"294 Meadowcreek Drive, Unit Unit 2, Village Of...",US

In [6]:
display(train_s2.head(10))

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US
5,S2-138046867,Lee and Lawson,"1702 Pine Avenue, CITY OF MENOMONIE, WI",US
6,S2-584977605,SHIVSHAKTI VIDYALAYA VIDYALAYA OVERSEAS CORPOR...,"H.NO 204 C ROAD HOSHIARPUR, PUNJAB, Punjab",India
7,S2-277444929,Shree Infracon Private Ltd,"63/2275/7, ALHIND TOWER, FIRST FLOOR, JAFFERKH...",India
8,S2-721031885,Chavira Platinum Chimera LLC,"282 SAXONY DRIVE, FTT MITCHELL, KY",US
9,S2-508602797,FOUNDATION EXCEL AGENCY PRIVATE LIMITED,"HN 753 E-1, BHARAT NAGAR, 104/1/1 ERANDWANE, M...",India

In [7]:
display(train_s3.head(10))

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India
5,S3-578159284,LLC Hernandez Colonial Redwood,"2260- Housecreek Trail, Unit 407, Raleigh, Nor...",US
6,S3-121412624,Classic Equity Partners Group,"6885 Catalpa Bluff Ln, PO Box 5799, Dickinson,...",US
7,S3-249416830,Ectolumdrex dba X+ Madison Inc,"S03575 Cty Tk M, Town Of Buffalo, WI",US
8,S3-107644605,Animal Hanisch Hospirlg,"##8 Willow Oak Lane, Fl. 0, Saint Louis, Missouri",US
9,S3-160217003,Gomez Optimal,"343 Hempstead 161, Hope, Arkansas",US

In [8]:
display(ground_truth.head(10))

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5       S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6      S1-318373630                          S2-660036492,S3-804600254
7       S1-86989137                          S3-274817120,S3-312496301
8       S1-29845983                          S2-648035184,S3-588502663
9      S1-789009573              S2-383871912,S3-74481402,S3-576451439

In [9]:
for name, df in datasets.items():
    print("\n" + "=" * 60)
    print(name)
    print("=" * 60)
    print(df.isnull().sum())

============================================================
Train Source 1
============================================================
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

============================================================
Train Source 2
============================================================
entity_id                0
business_name            2
business_address    168967
country                  0
dtype: int64

============================================================
Train Source 3
============================================================
entity_id                0
business_name           13
business_address    175916
country                  0
dtype: int64

============================================================
Ground Truth
============================================================
source1_entity_id          0
matched_entity_ids    123247
dtype: int64

============================================================
Test Source 1
============================================================
entity_id           0
business_name       0
business_address    0
country             0
dtype: int64

============================================================
Test Source 2
============================================================
entity_id                0
business_name           46
business_address    129408
country                  0
dtype: int64

============================================================
Test Source 3
============================================================
entity_id                0
business_name           59
business_address    136098
country                  0
dtype: int64

In [10]:
for name, df in {
    "Train S1": train_s1,
    "Train S2": train_s2,
    "Train S3": train_s3,
    "Test S1": test_s1,
    "Test S2": test_s2,
    "Test S3": test_s3,
}.items():

    print("\n" + name)
    print(df["country"].value_counts(dropna=False))

Train S1
country
US       1323633
India     883188
Name: count, dtype: int64

Train S2
country
US       3016817
India    2017799
Name: count, dtype: int64

Train S3
country
US       3170056
India    2115547
Name: count, dtype: int64

Test S1
country
India     809986
US        663106
France    259452
Name: count, dtype: int64

Test S2
country
India     2312565
US        1871330
France     703378
Name: count, dtype: int64

Test S3
country
India     2405000
US        1945701
France     731615
Name: count, dtype: int64

In [11]:
display(ground_truth.head(20))

   source1_entity_id                                 matched_entity_ids
0          S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1        S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2       S1-343815751             S2-790675320,S2-479876582,S3-878454467
3       S1-656753428              S2-153058913,S2-24659151,S3-679606215
4       S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5        S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6       S1-318373630                          S2-660036492,S3-804600254
7        S1-86989137                          S3-274817120,S3-312496301
8        S1-29845983                          S2-648035184,S3-588502663
9       S1-789009573              S2-383871912,S3-74481402,S3-576451439
10      S1-730934468                          S2-356983532,S3-352439310
11        S1-7293388  S2-7028416,S2-442723188,S2-157073701,S3-523120965
12      S1-546142636  S2-487600131,S2-582477216,S2-392804085,S3-2000...
13      S1-274126313  S2-736616474,S2-680265918,S2-51486805,S3-92563...
14      S1-145361722              S2-120366543,S2-939389287,S3-96572514
15      S1-503957000  S2-994658326,S2-235117490,S2-353308450,S2-1732...
16      S1-692000596                          S2-580419223,S3-164220452
17      S1-561341312                          S2-483615364,S3-619529814
18      S1-777597828                          S2-836452886,S3-413669121
19      S1-282467635                          S2-938895481,S3-138350041

In [12]:
ground_truth["matched_count"] = (
    ground_truth["matched_entity_ids"]
    .fillna("")
    .astype(str)
    .apply(
        lambda x: 0 if x.strip() == "" else len(x.split(","))
    )
)

print(
    ground_truth["matched_count"]
    .value_counts()
    .sort_index()
)

matched_count
0     123247
1     119157
2     375212
3     530841
4     484115
5     321957
6     164868
7      63968
8      18680
9       4205
10       534
11        37
Name: count, dtype: int64

In [13]:
display(ground_truth.head(20))

,source1_entity_id,matched_entity_ids,matched_count
0,S1-965667,"S2-681193310,S2-743505751,S3-775321672,S3-1129...",5
1,S1-55344266,"S2-249013014,S2-197070651,S3-478195123,S3-3843...",4
2,S1-343815751,"S2-790675320,S2-479876582,S3-878454467",3
3,S1-656753428,"S2-153058913,S2-24659151,S3-679606215",3
4,S1-102811957,"S2-478959098,S2-553508714,S2-625774905,S3-7280...",6
5,S1-18727616,"S2-755677256,S3-187831601,S3-641489370,S3-4762...",4
6,S1-318373630,"S2-660036492,S3-804600254",2
7,S1-86989137,"S3-274817120,S3-312496301",2
8,S1-29845983,"S2-648035184,S3-588502663",2
9,S1-789009573,"S2-383871912,S3-74481402,S3-576451439",3
10,S1-730934468,"S2-356983532,S3-352439310",2
11,S1-7293388,"S2-7028416,S2-442723188,S2-157073701,S3-523120965",4
12,S1-546142636,"S2-487600131,S2-582477216,S2-392804085,S3-2000...",6
13,S1-274126313,"S2-736616474,S2-680265918,S2-51486805,S3-92563...",6
14,S1-145361722,"S2-120366543,S2-939389287,S3-96572514",3
15,S1-503957000,"S2-994658326,S2-235117490,S2-353308450,S2-1732...",7
16,S1-692000596,"S2-580419223,S3-164220452",2
17,S1-561341312,"S2-483615364,S3-619529814",2
18,S1-777597828,"S2-836452886,S3-413669121",2
19,S1-282467635,"S2-938895481,S3-138350041",2

In [14]:
match_counts = ground_truth["matched_count"].value_counts().sort_index()

print(
    pd.DataFrame({
        "count": match_counts,
        "percentage": (match_counts / len(ground_truth) * 100).round(2)
    })
)

                count  percentage
matched_count
0              123247        5.58
1              119157        5.40
2              375212       17.00
3              530841       24.05
4              484115       21.94
5              321957       14.59
6              164868        7.47
7               63968        2.90
8               18680        0.85
9                4205        0.19
10                534        0.02
11                 37        0.00

In [15]:
print("Total S1:", len(ground_truth))
print("Singletons:", (ground_truth["matched_count"] == 0).sum())
print(
    "Singleton %:",
    round((ground_truth["matched_count"] == 0).mean() * 100, 2)
)

Total S1: 2206821
Singletons: 123247
Singleton %: 5.58

In [16]:
matches = ground_truth["matched_entity_ids"].fillna("").astype(str)

s2_count = matches.str.count(r"S2-")
s3_count = matches.str.count(r"S3-")

print("Total S2 matches:", s2_count.sum())
print("Total S3 matches:", s3_count.sum())

print("\nNumber of S1 entities with:")
print("S2 matches only :", ((s2_count > 0) & (s3_count == 0)).sum())
print("S3 matches only :", ((s2_count == 0) & (s3_count > 0)).sum())
print("Both S2 and S3  :", ((s2_count > 0) & (s3_count > 0)).sum())
print("No matches      :", ((s2_count == 0) & (s3_count == 0)).sum())

Total S2 matches: 3693619
Total S3 matches: 3944746

Number of S1 entities with:
S2 matches only : 143029
S3 matches only : 164498
Both S2 and S3  : 1776047
No matches      : 123247

In [17]:
for name, df in {
    "S1": train_s1,
    "S2": train_s2,
    "S3": train_s3
}.items():

    print("\n", "=" * 50)
    print(name)

    print(
        "Duplicate business names:",
        df["business_name"].duplicated().sum()
    )

    print(
        "Duplicate addresses:",
        df["business_address"].duplicated().sum()
    )

    print(
        "Duplicate name + address:",
        df.duplicated(
            subset=["business_name", "business_address"]
        ).sum()
    )

 ==================================================
S1
Duplicate business names: 667592
Duplicate addresses: 76215
Duplicate name + address: 0

 ==================================================
S2
Duplicate business names: 632607
Duplicate addresses: 697354
Duplicate name + address: 25891

 ==================================================
S3
Duplicate business names: 633994
Duplicate addresses: 652838
Duplicate name + address: 18881

In [18]:
display(
    train_s2[
        train_s2["business_name"].duplicated(keep=False)
    ].sort_values("business_name").head(30)
)

,entity_id,business_name,business_address,country
387195,S2-898690529,# 1,NaN,US
3300033,S2-298385733,# 1,"712 CALHOUN RD, MAGNOLIA, AR",US
515866,S2-694096437,# 1,"712 CALHOUN ROAD, MAGNOLIA, AR",US
2448508,S2-362507314,# 1,"11008 96TH SRREET, VANCOUVER, WA",US
3317323,S2-801500807,# 2,"10867 38ND TRAIL, null, LAKE ELMO, MN",US
1268481,S2-898468674,# 2,"COLUMBUS, 1528 LINCOLN RD, OH",US
2163151,S2-211843176,# 2,"7484 LA JUTNA RD, SCOTTSDALLE, AZ",US
1173331,S2-925640291,# 2 CE Wellness,"5615 MONROE ST, HYATTSVILLE CITY, MD",US
2114519,S2-162845527,# 2 CE Wellness,"5615 MONROE ST, HYATTSVILLE CITY, MD",US
1969459,S2-189435585,# 2 Js Cslm,"ELM ST, HOPKINSVILLE, KY",US
247357,S2-291697528,# 2 Js Cslm,"15607 THORNBROOK DR, HOUSTON, TX",US
2471886,S2-325961737,# 2 KY Associated L.L.C.,"##932 CUSTER STREET, SALINA, KS",US
3589817,S2-776458449,# 2 KY Associated L.L.C.,"1510- BEECHER DRIVE, SAINT LOUIS, MO",US
5014942,S2-515056361,# 2 KY Associated Llc,"1510- BEECHER DRIVE, SAINT LOUIS, MO",US
876385,S2-463843468,# 2 KY Associated Llc,"1510- BEECHER DRIVE, SAINT LOUIS, MO",US
4390106,S2-172950854,# 2 MJ Choice Inc,"280 MAIN SAINT, PO BOX 7869, AGOLA, NY",US
1674728,S2-452041582,# 2 MJ Choice Inc,"275. MAIN STREET, ANGOLA, NY",US
3927865,S2-128707531,# 2 OG Capital LLC,"4720 Wild Canyon Drive, WOODBURY, MN",US
296628,S2-119813356,# 2 OG Capital LLC,"16124 MONROE ST, GOODYEAR, AZ",US
2580068,S2-449533172,# 2 TO Hub Corp,"4831-D JARMESE STREET, HOUTON, TX",US
1183923,S2-971342523,# 2 TO Hub Corp,NaN,US
1559565,S2-693478940,# 3,"234 1/2 COUNTY ROAD 5215, CLVEELAND CDP, TX",US
1733286,S2-486349043,# 3,"4030 HAMPTON DR, BENTON CDDP, AR",US
4493432,S2-260842643,# 3,NaN,US
2393535,S2-92728324,# 3,"040 GRANT 167070, SHERIDAN, AR",US
1903324,S2-340329081,# 3 DR Bsp LLC,"20 MAIN ST, PMB 3281, NORTH BALTIMORE, OH",US
2998162,S2-395862347,# 3 DR Bsp LLC,"20 MAIN STREET, PMB 3281, NORTH BALTIMORE, OH",US
97639,S2-447395321,# 4,"414 NEWBARY COURT, FRANKLIN, TN",US
2651274,S2-660685774,# 4,"786 1/2 CANTERBURY CT, SARATOGA SPRINGS, UT",US
3429728,S2-980240110,# 4,NaN,US

In [19]:
for name, df in {
    "S1": train_s1,
    "S2": train_s2,
    "S3": train_s3
}.items():

    df["name_length"] = (
        df["business_name"]
        .fillna("")
        .astype(str)
        .str.len()
    )

    df["address_length"] = (
        df["business_address"]
        .fillna("")
        .astype(str)
        .str.len()
    )

    print("\n", name)

    print(df["name_length"].describe())
    print(df["address_length"].describe())

 S1
count    2.206821e+06
mean     2.403440e+01
std      7.740533e+00
min      3.000000e+00
25%      1.800000e+01
50%      2.400000e+01
75%      3.000000e+01
max      1.050000e+02
Name: name_length, dtype: float64
count    2.206821e+06
mean     5.206621e+01
std      2.532972e+01
min      1.100000e+01
25%      3.300000e+01
50%      4.100000e+01
75%      7.000000e+01
max      2.560000e+02
Name: address_length, dtype: float64

 S2
count    5.034616e+06
mean     2.510357e+01
std      8.894694e+00
min      0.000000e+00
25%      1.900000e+01
50%      2.500000e+01
75%      3.100000e+01
max      1.040000e+02
Name: name_length, dtype: float64
count    5.034616e+06
mean     4.622591e+01
std      2.484467e+01
min      0.000000e+00
25%      3.000000e+01
50%      3.700000e+01
75%      6.100000e+01
max      2.490000e+02
Name: address_length, dtype: float64

 S3
count    5.285603e+06
mean     2.520214e+01
std      9.493635e+00
min      0.000000e+00
25%      1.800000e+01
50%      2.500000e+01
75%      3.100000e+01
max      1.230000e+02
Name: name_length, dtype: float64
count    5.285603e+06
mean     4.671444e+01
std      2.164981e+01
min      0.000000e+00
25%      3.500000e+01
50%      4.200000e+01
75%      5.400000e+01
max      2.400000e+02
Name: address_length, dtype: float64

In [20]:
s1_lookup = train_s1.set_index("entity_id")
s2_lookup = train_s2.set_index("entity_id")
s3_lookup = train_s3.set_index("entity_id")

def show_match(s1_id, matched_ids):
    print("\nS1")
    print(s1_lookup.loc[s1_id][
        ["business_name", "business_address", "country"]
    ])

    for mid in matched_ids.split(","):
        if mid.startswith("S2-"):
            row = s2_lookup.loc[mid]
        else:
            row = s3_lookup.loc[mid]

        print("\n", mid)
        print(row[
            ["business_name", "business_address", "country"]
        ])

In [21]:
for _, row in ground_truth[
    ground_truth["matched_count"] > 0
].sample(10, random_state=42).iterrows():

    show_match(
        row["source1_entity_id"],
        row["matched_entity_ids"]
    )

S1
business_name                Davis Family Office
business_address    88 Olive Circle, Lebanon, TN
country                                       US
Name: S1-777210964, dtype: object

 S2-12029274
business_name              Davis Family Offie
business_address    88 OLIVE CIR, LEBANON, TN
country                                    US
Name: S2-12029274, dtype: object

 S2-407524980
business_name          DAVIS FAMILY OFFICE
business_address    OLIVE CIR, LEBANON, TN
country                                 US
Name: S2-407524980, dtype: object

 S3-970714334
business_name                  Davis Family (Office)
business_address    88 Olive Cir, Lebanon, Tennessee
country                                           US
Name: S3-970714334, dtype: object

 S3-712922821
business_name                           Davis Family
business_address    Lebanon, Tennessee, 88 Olive Cir
country                                           US
Name: S3-712922821, dtype: object

S1
business_name                                     MS Consultancy Corp
business_address    Shymala Appts 1St Floor Flat No. 4 Opp Ratna H...
country                                                         India
Name: S1-190133982, dtype: object

 S2-523219173
business_name                                        MS [Consultancy]
business_address    SHYMALA APPTS 1-1ST FLOOR FLAT NO. 4 OPP RATNA...
country                                                         India
Name: S2-523219173, dtype: object

 S3-716445195
business_name                                    M5  Consultancy Corp
business_address    Pune, MH, Pune, Shymala Appts 1St Floor Flat N...
country                                                         India
Name: S3-716445195, dtype: object

 S3-986804760
business_name                                        MS Corp Services
business_address    Shymala Appts 1St Floor Flat No. 4 Opp Ratna H...
country                                                         India
Name: S3-986804760, dtype: object

S1
business_name            3520 Main Road Realty Inc
business_address    TX, 158 Simpson Lane, Somerset
country                                         US
Name: S1-970131671, dtype: object

 S2-670035601
business_name        3520 MAIN ROAD REALTY INC
business_address    SIMPSON LANE, SOMERSET, TX
country                                     US
Name: S2-670035601, dtype: object

 S3-392756625
business_name               3520 MAIN ROAD Realty INC
business_address    158 Simpson Lane, Somerset, Texas
country                                            US
Name: S3-392756625, dtype: object

S1
business_name                                      Team Air Pvt. Ltd.
business_address    Flat No:101, Anuska Towers, Opp. Mercedes Benz...
country                                                         India
Name: S1-391999301, dtype: object

 S2-742819060
business_name                                             TEAMAIR.COM
business_address    FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ...
country                                                         India
Name: S2-742819060, dtype: object

 S2-339356009
business_name                            Thg Air Pvt. Ltd.
business_address    FLAT NO:101, -POOL, HYDERABAD, తెలంగాణ
country                                              India
Name: S2-339356009, dtype: object

 S2-233734305
business_name                                             teamair.com
business_address    FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ...
country                                                         India
Name: S2-233734305, dtype: object

 S3-938838849
business_name                                                 Mirasol
business_address    Flat No:1-101, Anuska Towers, Opp. Mercedes Be...
country                                                         India
Name: S3-938838849, dtype: object

 S3-99519749
business_name                                   Team Air Pvt. Limited
business_address    Flat No:1-101, Anuska Towers, Opp. Mercedes Be...
country                                                         India
Name: S3-99519749, dtype: object

S1
business_name                                      Drayex Berto LLC
business_address    Montgomery Village, MD, 19821 Wheelwright Drive
country                                                          US
Name: S1-435988542, dtype: object

 S2-500704398
business_name                                    DRAYEX  BERTO LLC
business_address    ##19821 WHEELWRIGHT DR, MONTGOMERY VILLAGE, MD
country                                                         US
Name: S2-500704398, dtype: object

S1
business_name                    Grand Connecticut LLC
business_address    Calumet City, 351 Hoxie Avenue, IL
country                                             US
Name: S1-351020560, dtype: object

 S2-907008976
business_name                          Grand Connecticut
business_address    CALUMET CITY, 351 HOXIE AVE, N/A, IL
country                                               US
Name: S2-907008976, dtype: object

 S3-943702663
business_name                               Grand LLC Service
business_address    Illinois, Calumet City, 351- Hoxie Avenue
country                                                    US
Name: S3-943702663, dtype: object

 S3-503506440
business_name                               Grand Connecticut
business_address    351- Hoxie Avenue, Calumet City, Illinois
country                                                    US
Name: S3-503506440, dtype: object

 S3-27236093
business_name                  Grand Grand Connecticut LLC
business_address    351- Hoxie Ave, Calumet City, Illinois
country                                                 US
Name: S3-27236093, dtype: object

S1
business_name                     Prairie Capital Partners PLLC
business_address    120 Autumn Woods Boulevard, Mount Holly, NC
country                                                      US
Name: S1-353020204, dtype: object

 S2-403125820
business_name                      PRAIRIE CAPITAL PLLC-PARTNERS
business_address    120. Autumn Woods Boulevard, MOUNT HOLLY, NC
country                                                       US
Name: S2-403125820, dtype: object

 S2-482586584
business_name                        Prairie (Capital)
business_address    AUTUMN WOODS BLVD, MOUNT HOLLY, NC
country                                             US
Name: S2-482586584, dtype: object

 S3-740655592
business_name                      Prairie Partners PLLC  Services
business_address    Autumn Woods Blvd, Mount Holly, North Carolina
country                                                         US
Name: S3-740655592, dtype: object

 S3-701336150
business_name       prairie capital partners pllc
business_address                              NaN
country                                        US
Name: S3-701336150, dtype: object

S1
business_name                                          Jalna Chem LLP
business_address    At H. No 211, Bhamberi Tq. Ambad S/Dn Dist Jal...
country                                                         India
Name: S1-374388852, dtype: object

 S2-509116615
business_name                                         Jalna Chem  LLP
business_address    AT H. NO 211, BHAMBERI TQ. AMBAD S/DN DIST JAL...
country                                                         India
Name: S2-509116615, dtype: object

 S3-913638566
business_name                                           Jalna  Ce LLP
business_address    Blokc C-724 At H. No 211, Bhamberi Tq. Ambad S...
country                                                         India
Name: S3-913638566, dtype: object

S1
business_name                      Clairvoyant Record Private Limited
business_address    1St Floor, Tamrakarmall, New Bus Stand, Sehore...
country                                                         India
Name: S1-793615008, dtype: object

 S2-102911781
business_name                      Clairvoyant Ride Private (Limited)
business_address    NO 7-1ST FLOOR, TAMRAKARMALL, NEW BUS STAND, S...
country                                                         India
Name: S2-102911781, dtype: object

 S2-942337168
business_name                          Clairvoyant Récord Private Ltd
business_address    7-1ST FLOOR, TAMRAKARMALL, NEW BUS STAND, SEHO...
country                                                         India
Name: S2-942337168, dtype: object

 S2-875327982
business_name                       Clairvoyant Rcdbr Private Limited
business_address    7-1ST FLOOR, TAMRAKARMALL, NEW BUS STAND, SEHO...
country                                                         India
Name: S2-875327982, dtype: object

 S3-276503007
business_name                           Clairvoyant Record Private
business_address    1St Floor, Sehore, Madhya Pradesh, मध्य प्रदेश
country                                                      India
Name: S3-276503007, dtype: object

 S3-154593156
business_name        Clairvoyant Rceoad Private (Limited)
business_address    1St Floor, Sehore, Madhya Pradesh, MP
country                                             India
Name: S3-154593156, dtype: object

S1
business_name                                     FH Business Pvt Ltd
business_address    602, 6Th Floor, Crystal Mall, Bani Park, Jaipu...
country                                                         India
Name: S1-339384180, dtype: object

 S2-763394237
business_name                                 FH BUSINESS PVT LIMITED
business_address    602, 6TH FLOOR, CRYSTAL MALL, BANI PARK, JAIPU...
country                                                         India
Name: S2-763394237, dtype: object

 S3-162797226
business_name       FH Business Pvt-Ltd.
business_address         602, Jaipur, RJ
country                            India
Name: S3-162797226, dtype: object

 S3-914554628
business_name                                 FH FH Business Pvt Ltd.
business_address    6Th Floor, Crystal Mall, Bani Park, Jaipur, 60...
country                                                         India
Name: S3-914554628, dtype: object

In [22]:
print("TRAIN")
print(set(train_s1["country"].dropna().unique()))
print(set(train_s2["country"].dropna().unique()))
print(set(train_s3["country"].dropna().unique()))

print("\nTEST")
print(set(test_s1["country"].dropna().unique()))
print(set(test_s2["country"].dropna().unique()))
print(set(test_s3["country"].dropna().unique()))

TRAIN
{'India', 'US'}
{'India', 'US'}
{'India', 'US'}

TEST
{'France', 'India', 'US'}
{'France', 'India', 'US'}
{'France', 'India', 'US'}

In [23]:
train_countries = set(
    pd.concat([
        train_s1["country"],
        train_s2["country"],
        train_s3["country"]
    ]).dropna()
)

test_countries = set(
    pd.concat([
        test_s1["country"],
        test_s2["country"],
        test_s3["country"]
    ]).dropna()
)

print("Train countries:", train_countries)
print("Test countries:", test_countries)
print("New test countries:", test_countries - train_countries)

Train countries: {'India', 'US'}
Test countries: {'France', 'India', 'US'}
New test countries: {'France'}

In [24]:
# How many unique names?
for name, df in {
    "S1": train_s1,
    "S2": train_s2,
    "S3": train_s3
}.items():

    print(
        name,
        "rows =", len(df),
        "unique names =", df["business_name"].nunique(),
        "unique addresses =", df["business_address"].nunique(),
        "unique name+address =",
        df[["business_name", "business_address"]].drop_duplicates().shape[0]
    )

S1 rows = 2206821 unique names = 1539229 unique addresses = 2130606 unique name+address = 2206821
S2 rows = 5034616 unique names = 4402008 unique addresses = 4337261 unique name+address = 5008725
S3 rows = 5285603 unique names = 4651608 unique addresses = 4632764 unique name+address = 5266722

In [25]:
for name, df in {
    "S1": train_s1,
    "S2": train_s2,
    "S3": train_s3
}.items():

    name_counts = df["business_name"].value_counts()

    print("\n", name)
    print("Names appearing >1:", (name_counts > 1).sum())
    print("Maximum name frequency:", name_counts.max())

 S1
Names appearing >1: 177793
Maximum name frequency: 253

 S2
Names appearing >1: 239778
Maximum name frequency: 320

 S3
Names appearing >1: 258275
Maximum name frequency: 421

In [26]:
# Build lookups once
s1_lookup = train_s1.set_index("entity_id")
s2_lookup = train_s2.set_index("entity_id")
s3_lookup = train_s3.set_index("entity_id")


# Get only S1 entities that have matches
matched_gt = ground_truth[
    ground_truth["matched_entity_ids"].fillna("").str.strip() != ""
]

print("S1 entities with at least one match:", len(matched_gt))


# Show 20 examples
sample = matched_gt.sample(
    min(20, len(matched_gt)),
    random_state=42
)

for _, row in sample.iterrows():

    s1_id = row["source1_entity_id"]

    print("\n" + "=" * 80)

    print("S1:", s1_id)
    print("Name   :", s1_lookup.loc[s1_id, "business_name"])
    print("Address:", s1_lookup.loc[s1_id, "business_address"])
    print("Country:", s1_lookup.loc[s1_id, "country"])

    matched_ids = row["matched_entity_ids"].split(",")

    for mid in matched_ids:

        mid = mid.strip()

        if mid.startswith("S2-"):
            lookup = s2_lookup
        elif mid.startswith("S3-"):
            lookup = s3_lookup
        else:
            continue

        print("\n", mid)
        print("Name   :", lookup.loc[mid, "business_name"])
        print("Address:", lookup.loc[mid, "business_address"])
        print("Country:", lookup.loc[mid, "country"])

S1 entities with at least one match: 2083574

================================================================================
S1: S1-777210964
Name   : Davis Family Office
Address: 88 Olive Circle, Lebanon, TN
Country: US

 S2-12029274
Name   : Davis Family Offie
Address: 88 OLIVE CIR, LEBANON, TN
Country: US

 S2-407524980
Name   : DAVIS FAMILY OFFICE
Address: OLIVE CIR, LEBANON, TN
Country: US

 S3-970714334
Name   : Davis Family (Office)
Address: 88 Olive Cir, Lebanon, Tennessee
Country: US

 S3-712922821
Name   : Davis Family
Address: Lebanon, Tennessee, 88 Olive Cir
Country: US

================================================================================
S1: S1-190133982
Name   : MS Consultancy Corp
Address: Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, Maharashtra
Country: India

 S2-523219173
Name   : MS [Consultancy]
Address: SHYMALA APPTS 1-1ST FLOOR FLAT NO. 4 OPP RATNA HOSPITAL SB ROAD IN HAVELI, PUNE, Maharashtra
Country: India

 S3-716445195
Name   : M5  Consultancy Corp
Address: Pune, MH, Pune, Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli
Country: India

 S3-986804760
Name   : MS Corp Services
Address: Shymala Appts 1St Floor Flat No. 4 Opp Ratna Hospital Sb Road In Haveli, Pune, MH
Country: India

================================================================================
S1: S1-970131671
Name   : 3520 Main Road Realty Inc
Address: TX, 158 Simpson Lane, Somerset
Country: US

 S2-670035601
Name   : 3520 MAIN ROAD REALTY INC
Address: SIMPSON LANE, SOMERSET, TX
Country: US

 S3-392756625
Name   : 3520 MAIN ROAD Realty INC
Address: 158 Simpson Lane, Somerset, Texas
Country: US

================================================================================
S1: S1-391999301
Name   : Team Air Pvt. Ltd.
Address: Flat No:101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Telangana
Country: India

 S2-742819060
Name   : TEAMAIR.COM
Address: FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ SHOW ROOM, LAKDI- KA, -POOL, తెలంగాణ
Country: India

 S2-339356009
Name   : Thg Air Pvt. Ltd.
Address: FLAT NO:101, -POOL, HYDERABAD, తెలంగాణ
Country: India

 S2-233734305
Name   : teamair.com
Address: FLAT NO:101, ANUSKA TOWERS, OPP. MERCEDES BENZ SHOW ROOM, LAKDI- KA, -POOL, Telangana
Country: India

 S3-938838849
Name   : Mirasol
Address: Flat No:1-101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, Hyderabad, -Pool, Andhra Pradesh
Country: India

 S3-99519749
Name   : Team Air Pvt. Limited
Address: Flat No:1-101, Anuska Towers, Opp. Mercedes Benz Show Room, Lakdi- Ka, -Pool, Hyderabad, Andhra Pradesh
Country: India

================================================================================
S1: S1-435988542
Name   : Drayex Berto LLC
Address: Montgomery Village, MD, 19821 Wheelwright Drive
Country: US

 S2-500704398
Name   : DRAYEX  BERTO LLC
Address: ##19821 WHEELWRIGHT DR, MONTGOMERY VILLAGE, MD
Country: US

================================================================================
S1: S1-351020560
Name   : Grand Connecticut LLC
Address: Calumet City, 351 Hoxie Avenue, IL
Country: US

 S2-907008976
Name   : Grand Connecticut
Address: CALUMET CITY, 351 HOXIE AVE, N/A, IL
Country: US

 S3-943702663
Name   : Grand LLC Service
Address: Illinois, Calumet City, 351- Hoxie Avenue
Country: US

 S3-503506440
Name   : Grand Connecticut
Address: 351- Hoxie Avenue, Calumet City, Illinois
Country: US

 S3-27236093
Name   : Grand Grand Connecticut LLC
Address: 351- Hoxie Ave, Calumet City, Illinois
Country: US

================================================================================
S1: S1-353020204
Name   : Prairie Capital Partners PLLC
Address: 120 Autumn Woods Boulevard, Mount Holly, NC
Country: US

 S2-403125820
Name   : PRAIRIE CAPITAL PLLC-PARTNERS
Address: 120. Autumn Woods Boulevard, MOUNT HOLLY, NC
Country: US

 S2-482586584
Name   : Prairie (Capital)
Address: AUTUMN WOODS BLVD, MOUNT HOLLY, NC
Country: US

 S3-740655592
Name   : Prairie Partners PLLC  Services
Address: Autumn Woods Blvd, Mount Holly, North Carolina
Country: US

 S3-701336150
Name   : prairie capital partners pllc
Address: nan
Country: US

================================================================================
S1: S1-374388852
Name   : Jalna Chem LLP
Address: At H. No 211, Bhamberi Tq. Ambad S/Dn Dist Jalna, Jalna, Maharashtra
Country: India

 S2-509116615
Name   : Jalna Chem  LLP
Address: AT H. NO 211, BHAMBERI TQ. AMBAD S/DN DIST JALNA, JALNA, Maharashtra
Country: India

 S3-913638566
Name   : Jalna  Ce LLP
Address: Blokc C-724 At H. No 211, Bhamberi Tq. Ambad S/dn Dist Jalna, Jalna, MH
Country: India

================================================================================
S1: S1-793615008
Name   : Clairvoyant Record Private Limited
Address: 1St Floor, Tamrakarmall, New Bus Stand, Sehore, Madhya Pradesh
Country: India

 S2-102911781
Name   : Clairvoyant Ride Private (Limited)
Address: NO 7-1ST FLOOR, TAMRAKARMALL, NEW BUS STAND, SEHORE, Madhya Pradesh
Country: India

 S2-942337168
Name   : Clairvoyant Récord Private Ltd
Address: 7-1ST FLOOR, TAMRAKARMALL, NEW BUS STAND, SEHORE, मध्य प्रदेश
Country: India

 S2-875327982
Name   : Clairvoyant Rcdbr Private Limited
Address: 7-1ST FLOOR, TAMRAKARMALL, NEW BUS STAND, SEHORE, Madhya Pradesh
Country: India

 S3-276503007
Name   : Clairvoyant Record Private
Address: 1St Floor, Sehore, Madhya Pradesh, मध्य प्रदेश
Country: India

 S3-154593156
Name   : Clairvoyant Rceoad Private (Limited)
Address: 1St Floor, Sehore, Madhya Pradesh, MP
Country: India

================================================================================
S1: S1-339384180
Name   : FH Business Pvt Ltd
Address: 602, 6Th Floor, Crystal Mall, Bani Park, Jaipur, Rajasthan
Country: India

 S2-763394237
Name   : FH BUSINESS PVT LIMITED
Address: 602, 6TH FLOOR, CRYSTAL MALL, BANI PARK, JAIPUR, राजस्थान
Country: India

 S3-162797226
Name   : FH Business Pvt-Ltd.
Address: 602, Jaipur, RJ
Country: India

 S3-914554628
Name   : FH FH Business Pvt Ltd.
Address: 6Th Floor, Crystal Mall, Bani Park, Jaipur, 602, RJ
Country: India

================================================================================
S1: S1-83174673
Name   : Supreme It Private Limited
Address: Office No S 07 82Haware, Centurion Plt88-91 Sec19A, Thane, Maharashtra
Country: India

 S2-348030512
Name   : Supreme  It Private Limited
Address: OFFICE NO S 07 82HAWARE, CENTURION PLT88-91 SEC19A, THANE, Maharashtra
Country: India

 S3-755114994
Name   : सुप्रीम आईटी प्राइवेट लिमिटेड
Address: Offiec No S ##07 82Haware, Centurion Plt88-91 Sec19a, Thane, MH
Country: India

 S3-444196916
Name   : Supreme It Private
Address: Office No S ##07 82Haware, Centurion Plt88-91 Sec19a, Thane, MH
Country: India

 S3-130505638
Name   : सुप्रीम आईटी प्राइवेट लिमिटेड
Address: Office No S ##07 82Haware, Centurion Plt88-91 Sec19a, Thane, MH
Country: India

================================================================================
S1: S1-350092923
Name   : Cardiology Metro Care Associates Inc
Address: 1138 Trimble Creek Drive, West Jordan City, UT
Country: US

 S2-358229894
Name   : cardiologymetrocare.com
Address: 1138 TRIMBLE CREEK DRIVE, WEST JORDAN, UT
Country: US

 S2-910624268
Name   : cmcáre.com
Address: 1138 TRIMBLE CREEK DRIVE, WEST JORDAN, UT
Country: US

 S3-662458828
Name   : Cardiology Metro Care Asfsogiadmrts Inc | www.cardiology.com
Address: 1138 Trimble Creek Drive, West Jordan City, Utah
Country: US

================================================================================
S1: S1-665522603
Name   : Achyut Colonisers Pvt Ltd
Address: House No 4/82 Madanlal Bohara Kapad Market Ichalkaranji, Ichalkaranji, Kolhapur, Maharashtra
Country: India

 S3-813562861
Name   : Shri Verafayemira
Address: House No 4/82 Madanlal Bohara Kapad Market Ichalkaranji, Kolhapur, महाराष्ट्र
Country: India

================================================================================
S1: S1-200723243
Name   : Unique & Sons Private Limited
Address: Plot No.118, 119 Syno:190, Ip Chandanvelly, Rangareddy, K.V.Rangareddy, Telangana
Country: India

 S2-952851011
Name   : Unique & 5ons Pirave Limited
Address: PLOT NO.118, 119 SYNO:190, IP CHANDANVELLY, RANGAREDDY, Telangana
Country: India

 S2-788224506
Name   : UNIQUE & SONS LIMITED SERVICE
Address: #118 , 119 SYNO:190, IP CHANDANVELLY, RANGAREDDY, తెలంగాణ
Country: India

 S2-221988027
Name   : uniquesons.com
Address: 118 , 119 SYNO:190, IP CHANDANVELLY, RANGAREDDY, Telangana
Country: India

 S2-621477890
Name   : Unique &  Sons Private [Limited]
Address: PLOT NO.118, 119 SYNO:190, IP CHANDANVELLY, RANGAREDDY, Telangana
Country: India

 S3-153417633
Name   : Unique & Sons
Address: #118, 119 Syno:190, Ip Chandanvelly, Hyderabad City Region, K.v.rangareddy, TG
Country: India

 S3-234128350
Name   : Unique & Sons Prcvate Limited
Address: H.no 118, Hyderabad City Region, K.v.rangareddy, TG
Country: India

================================================================================
S1: S1-46329934
Name   : Sarasva India Limited
Address: 9/1/3 Kasundia 2Nd Bye Lane Lp-224/24/1, Santragachi, Howrah, West Bengal
Country: India

 S2-704697535
Name   : limited sarasva india
Address: 9/1/3. KASUNDIA 2ND BYE LANE LP-224/24/1, HOWRAH, West Bengal
Country: India

 S2-604099225
Name   : Sarasva Índia
Address: DOOR NO 9/1/3. KASUNDIA 2ND BYE LANE LP-224/24/1, SANTRAGACHI, HOWRAH, পশ্চিমবঙ্গ
Country: India

 S2-975202599
Name   : SARASVA (INDIA) (INDIA)
Address: 9/1/3. KASUNDIA 2ND BYE LANE LP-224/24/1, SANTRAGACHI, HOWRAH, পশ্চিমবঙ্গ
Country: India

 S3-688076126
Name   : Sarasva India [[Limited]]
Address: H.no 9/1/3 Kasundia 2Nd Bye Lane Lp-224/24/1, Santragachi, Howrah, WB
Country: India

 S3-175132143
Name   : Limited Sarasva lndia
Address: 9/1/3 Kasundia 2Nd Bye Lane Lp-224/24/1, Santragachi, Howrah, WB
Country: India

================================================================================
S1: S1-957340511
Name   : Desert Society Inc
Address: 4038 Talmadge Road, Unit 102, Toledo, OH
Country: US

 S2-363608755
Name   : Society Desert Inc
Address: #4038 TALMADGE RD, TOLEDO, OH
Country: US

 S2-326291497
Name   : Desert Society Inc
Address: #4038 TALMADGE RD, TOLEDO, OH
Country: US

 S2-971669168
Name   : INCORPORATED DESERT SOCIETY
Address: #4038 TALMADGE RD, TOLEDO, OH
Country: US

 S3-603047654
Name   : desert society inc
Address: 4038 Talmadge Road, # 102, Toledo, Ohio
Country: US

 S3-917953818
Name   : Desert S0ciety Inc
Address: Talmadge Road, Unit 102, Toledo, Ohio
Country: US

================================================================================
S1: S1-661807190
Name   : Mendez's Excavation PLLC
Address: 914 Charlotte Drive, Anoka, MN
Country: US

 S2-7657580
Name   : Mendez's Excavation
Address: 914 CHARLOTTE DRIVE, ANOKA, MN
Country: US

 S2-372634346
Name   : Mendez's Excavation
Address: 914 CHARLOTTE DR, ANOKA, MN
Country: US

 S2-414241629
Name   : Mendez's-Excavation PLLC
Address: 914 CHARLOTTE DRIVE, ANOKA, MN
Country: US

 S2-240792458
Name   : Mendez's Excavation PLLC
Address: MN, ANOKA, CHARLOTTE DRIVE
Country: US

 S2-651471068
Name   : Mendez's Excavation
Address: 914 CHARLOTTE DR, ANOKA, MN
Country: US

 S3-106044387
Name   : Mendez'S Excavation PLLC
Address: 914 Charlotte Drive, Anoka, Minnesota
Country: US

 S3-306328111
Name   : Mendez's Excavation
Address: Charlotte Dr, Anoka, Minnesota
Country: US

 S3-182045112
Name   : Mendez's Excabatsibo PLLC
Address: Anoka, Minnesota, 914 Charlotte Dr
Country: US

================================================================================
S1: S1-670305710
Name   : Loudoun County Cultural Coalition, LLC
Address: 44023 Vaira Terrace, Loudoun County, VA
Country: US

 S2-892615832
Name   : LOUDOUN COUNTY CULTURAL COALITION, LLC
Address: 0044023 VAIRA TER, N/A, CHANTILLY, VA
Country: US

 S3-524974871
Name   : Loudoun County Cultural Coalition, LLC District
Address: Chantilly, Virginia, #44023 Vaira Terrace
Country: US

================================================================================
S1: S1-691615940
Name   : Rapid Transit Laboratories Care
Address: 8201 Highpoint Road, Fl 0, Curtis Bay, MD
Country: US

 S2-748691171
Name   : Rapid Transit Lab0ratories Cáre
Address: 8201 HIGHPOINT RD, CURTIS BAY, MD
Country: US

 S3-397491565
Name   : Rapid Tránsit Laboratories Cise
Address: Curtis Bay, Maryland, 8201 1/2 Highpoint Rd
Country: US

 S3-955477709
Name   : Rapid Transit
Address: 8201 1/2 Highpoint Road, Fl 0, Curtis Bay, Maryland
Country: US

================================================================================
S1: S1-116292005
Name   : Cornerstone Investments L.L.C.
Address: 1475 Manitowoc Road, City Of Menasha, WI
Country: US

 S2-190403429
Name   : L.L.C. CORNERSTONE INVESTMENTS
Address: 1475 MANITOWOC RD, CITY OF MENASHA, WI
Country: US

 S2-352866222
Name   : @cornerstoneinvestments
Address: 1475 MANITOAOC RD, CITY OF MENASHA, WI
Country: US

 S2-807647266
Name   : cornerstone investments l.l.c.
Address: MANITOWOC RD, MENASHA, WI
Country: US

 S3-491460140
Name   : Cornerstone  Investments L.L.C.
Address: Manitowoc Road, City Of Menasha, Wisconsin
Country: US

 S3-703236777
Name   : Center Cornerstone L.L.C.
Address: 1475 Manitowoc Rd, City Of Menasha, Wisconsin
Country: US

 S3-903695330
Name   : Drexsolpyra DBA: Cornerstone Investments L.L.C.
Address: City Of Menasha, WI, 1475 Manitowoc Road
Country: US