<a href="https://colab.research.google.com/github/kartik815/Amazon-ML-Challenge-2026/blob/main/notebooks/04_Blocking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

import os
import gc
import pandas as pd

DRIVE_ROOT = "/content/drive/MyDrive/Amazon ML Challenge 2026"

CLEANED_DATA_ROOT = os.path.join(
    DRIVE_ROOT,
    "03_Experiments",
    "Cleaned_Data"
)

TRAIN_ROOT = os.path.join(
    DRIVE_ROOT,
    "01_Dataset",
    "6ab10eb3b23ba_student_resource",
    "student_resource",
    "dataset",
    "train"
)

TEST_ROOT = os.path.join(
    DRIVE_ROOT,
    "01_Dataset",
    "6ab10eb3b23ba_student_resource",
    "student_resource",
    "dataset",
    "test"
)

BLOCKING_OUTPUT_ROOT = os.path.join(
    DRIVE_ROOT,
    "05_Outputs",
    "Candidate_Pairs"
)

os.makedirs(BLOCKING_OUTPUT_ROOT, exist_ok=True)

print("Cleaned data:")
print(CLEANED_DATA_ROOT)

print("\nBlocking output:")
print(BLOCKING_OUTPUT_ROOT)

Mounted at /content/drive
Cleaned data:
/content/drive/MyDrive/Amazon ML Challenge 2026/03_Experiments/Cleaned_Data

Blocking output:
/content/drive/MyDrive/Amazon ML Challenge 2026/05_Outputs/Candidate_Pairs

In [ ]:
RAW_S1_PATH = os.path.join(
    TRAIN_ROOT,
    "train_source1.tsv"
)

RAW_S2_PATH = os.path.join(
    TRAIN_ROOT,
    "train_source2.tsv"
)

In [ ]:
CLEANED_FILES = [
    "train_s1_cleaned.tsv",
    "train_s2_cleaned.tsv",
    "train_s3_cleaned.tsv",
    "test_s1_cleaned.tsv",
    "test_s2_cleaned.tsv",
    "test_s3_cleaned.tsv"
]

print("Checking cleaned files...\n")

for filename in CLEANED_FILES:

    path = os.path.join(
        CLEANED_DATA_ROOT,
        filename
    )

    print(
        f"{filename:<25}",
        "EXISTS" if os.path.exists(path) else "MISSING"
    )

Checking cleaned files...

train_s1_cleaned.tsv      EXISTS
train_s2_cleaned.tsv      EXISTS
train_s3_cleaned.tsv      EXISTS
test_s1_cleaned.tsv       EXISTS
test_s2_cleaned.tsv       EXISTS
test_s3_cleaned.tsv       EXISTS

In [ ]:
sample_path = os.path.join(
    CLEANED_DATA_ROOT,
    "train_s1_cleaned.tsv"
)

sample = pd.read_csv(
    sample_path,
    sep="\t",
    nrows=5
)

print("Columns:")
print(sample.columns.tolist())

print("\nSample:")
display(sample)

Columns:
['entity_id', 'business_name', 'business_address', 'country', 'name_norm', 'address_norm', 'country_norm', 'name_missing', 'address_missing', 'name_token_count', 'address_token_count', 'name_core']

Sample:

,entity_id,business_name,business_address,country,name_norm,address_norm,country_norm,name_missing,address_missing,name_token_count,address_token_count,name_core
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US,orelee s barbershop,1795 westchester dr high point nc,us,0,0,3,6,orelee s barbershop
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US,prime money,17560 ellis rd tahlequah ok,us,0,0,2,5,prime money
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US,b retail inc,1712 montebello ave phoenix az,us,0,0,3,5,b retail
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US,christ chapel,2100 cameron dr unit apt g dundalk md,us,0,0,2,8,christ chapel
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India,prabhav business center,797 lake town block a kolkata howrah west bengal,india,0,0,3,9,prabhav business center

Blocker 1 (country_norm + name_core)

In [ ]:
import pandas as pd
from collections import Counter

S2_PATH = os.path.join(
    CLEANED_DATA_ROOT,
    "train_s2_cleaned.tsv"
)

S3_PATH = os.path.join(
    CLEANED_DATA_ROOT,
    "train_s3_cleaned.tsv"
)

CHUNK_SIZE = 200_000

def get_block_sizes(path):
  counter = Counter()

  for chunk in pd.read_csv(
      path,
      sep="\t",
      chunksize=CHUNK_SIZE,
      dtype={"country_norm": "string", "name_norm": "string"}):
      chunk = chunk[
          chunk["name_core"].notna() &
          (chunk["name_core"] != "")
      ]

      keys = zip(
          chunk["country_norm"],
          chunk["name_core"]
      )

      counter.update(keys)

      del chunk
      gc.collect()

  return counter

print("Building S2 block statistics...")
s2_blocks = get_block_sizes(S2_PATH)

print("Building S3 block statistics...")
s3_blocks = get_block_sizes(S3_PATH)

print("\nS2 unique blocks:", len(s2_blocks))
print("S3 unique blocks:", len(s3_blocks))

Building S2 block statistics...
Building S3 block statistics...

S2 unique blocks: 3597772
S3 unique blocks: 3850257

In [ ]:
print("\nLargest S2 blocks:")
for key, count in s2_blocks.most_common(20):
    print(count, "->", key)

print("\nLargest S3 blocks:")
for key, count in s3_blocks.most_common(20):
    print(count, "->", key)

Largest S2 blocks:
647 -> ('us', 'meridian')
563 -> ('us', 'physical therapy')
550 -> ('us', 'primary care')
514 -> ('us', 'womens health')
507 -> ('us', 'internal medicine')
500 -> ('us', 'behavioral health')
494 -> ('us', 'urgent care')
491 -> ('us', 'pediatric dental')
482 -> ('us', 'pediatric dentistry')
408 -> ('us', 'ear nose throat')
398 -> ('us', 'foot ankle')
375 -> ('us', 'family center')
374 -> ('us', 'summit')
374 -> ('us', 'lynx')
366 -> ('us', 'anchor')
362 -> ('us', 'sapphire')
360 -> ('us', 'helios')
359 -> ('us', 'falcon')
356 -> ('us', 'cedar')
355 -> ('us', 'earnosethroat com')

Largest S3 blocks:
584 -> ('us', 'meridian')
548 -> ('us', 'primary care')
538 -> ('us', 'physical therapy')
524 -> ('us', 'pediatric dental')
507 -> ('us', 'urgent care')
492 -> ('us', 'womens health')
490 -> ('us', 'pediatric dentistry')
458 -> ('us', 'behavioral health')
452 -> ('us', 'internal medicine')
426 -> ('us', 'summit')
418 -> ('us', 'cascade')
412 -> ('us', 'family center')
399 -> ('us', 'sterling')
390 -> ('us', 'cedar')
386 -> ('us', 'apex')
379 -> ('us', 'foot ankle')
377 -> ('us', 'vanguard')
369 -> ('us', 'cornerstone')
369 -> ('us', 'lynx')
361 -> ('us', 'anchor')

In [ ]:
from collections import defaultdict
import gc

def build_block_index(path):

    index = defaultdict(list)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "country_norm", "name_core"],
        chunksize=200_000,
        dtype={
            "entity_id": "string",
            "country_norm": "string",
            "name_core": "string"
        }
    ):

        chunk = chunk[
            chunk["name_core"].notna() &
            (chunk["name_core"] != "")
        ]

        for country, name, entity_id in zip(
            chunk["country_norm"],
            chunk["name_core"],
            chunk["entity_id"]
        ):
            index[(country, name)].append(entity_id)

        del chunk
        gc.collect()

    return index

In [ ]:
print("Building S2 index...")
s2_index = build_block_index(S2_PATH)
print("S2 index blocks:", len(s2_index))
gc.collect()
print("\nBuilding S3 index...")
s3_index = build_block_index(S3_PATH)
print("S3 index blocks:", len(s3_index))

Building S2 index...
S2 index blocks: 3597772

Building S3 index...
S3 index blocks: 3850257

In [ ]:
GT_PATH = os.path.join(
    TRAIN_ROOT,
    "train_ground_truth.tsv"
)

S1_PATH = os.path.join(
    CLEANED_DATA_ROOT,
    "train_s1_cleaned.tsv"
)

gt = pd.read_csv(
    GT_PATH,
    sep="\t",
    dtype={
        "source1_entity_id": "string",
        "matched_entity_ids": "string"
    }
)

s1 = pd.read_csv(
    S1_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "country_norm",
        "name_core"
    ],
    dtype={
        "entity_id": "string",
        "country_norm": "string",
        "name_core": "string"
    }
)

print("S1 rows:", len(s1))
print("Ground truth rows:", len(gt))

S1 rows: 2206821
Ground truth rows: 2206821

In [ ]:
gt_lookup = {}

for row in gt.itertuples(index=False):
    s1_id = row.source1_entity_id
    matched = row.matched_entity_ids

    if pd.isna(matched) or matched == "":
        gt_lookup[s1_id] = set()
    else:
        gt_lookup[s1_id] = {
            x.strip()
            for x in str(matched).split(",")
            if x.strip()
        }

print("Ground truth lookup entries:", len(gt_lookup))

Ground truth lookup entries: 2206821

In [ ]:
def calculate_block_recall(
    s1_df,
    gt_lookup,
    index,
    prefix,
    block_column
):
    total_matches = 0
    captured_matches = 0

    for row in s1_df.itertuples(index=False):

        s1_id = row.entity_id
        country = row.country_norm
        block_value = getattr(row, block_column)

        true_ids = {
            x for x in gt_lookup.get(s1_id, set())
            if x.startswith(prefix)
        }

        if not true_ids:
            continue

        total_matches += len(true_ids)

        if pd.isna(block_value) or block_value == "":
            candidates = []
        else:
            candidates = index.get(
                (country, block_value),
                []
            )

        captured_matches += len(
            true_ids.intersection(candidates)
        )

    recall = (
        captured_matches / total_matches
        if total_matches
        else 0
    )

    return total_matches, captured_matches, recall

In [ ]:
s1_blocking = pd.read_csv(
    S1_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "country_norm",
        "name_core",
        "address_norm"
    ],
    dtype={
        "entity_id": "string",
        "country_norm": "string",
        "name_core": "string",
        "address_norm": "string"
    }
)

print(s1_blocking.shape)
print(s1_blocking.columns.tolist())

(2206821, 4)
['entity_id', 'address_norm', 'country_norm', 'name_core']

In [ ]:
from collections import defaultdict
import pandas as pd
import gc

def build_name_index(path):
    index = defaultdict(list)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "country_norm", "name_core"],
        chunksize=200_000,
        dtype={
            "entity_id": "string",
            "country_norm": "string",
            "name_core": "string"
        }
    ):
        chunk = chunk[
            chunk["name_core"].notna() &
            (chunk["name_core"] != "")
        ]

        for country, name, entity_id in zip(
            chunk["country_norm"],
            chunk["name_core"],
            chunk["entity_id"]
        ):
            index[(country, name)].append(entity_id)

        del chunk
        gc.collect()

    return index

In [ ]:
print("Building S2 exact-name index...")

s2_name_index = build_name_index(S2_PATH)

print("S2 name blocks:", len(s2_name_index))

Building S2 exact-name index...
S2 name blocks: 3597772

In [ ]:
from collections import defaultdict
import gc
import pandas as pd

def build_address_index(path):
    index = defaultdict(list)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "country_norm", "address_norm"],
        chunksize=200_000,
        dtype={
            "entity_id": "string",
            "country_norm": "string",
            "address_norm": "string"
        }
    ):
        chunk = chunk[
            chunk["address_norm"].notna() &
            (chunk["address_norm"] != "")
        ]

        for country, address, entity_id in zip(
            chunk["country_norm"],
            chunk["address_norm"],
            chunk["entity_id"]
        ):
            index[(country, address)].append(entity_id)

        del chunk
        gc.collect()

    return index

In [ ]:
s2_total, s2_captured, s2_recall = calculate_block_recall(
    s1_blocking,
    gt_lookup,
    s2_name_index,
    "S2-",
    "name_core"
)

print("S2")
print("Total true matches :", s2_total)
print("Captured matches   :", s2_captured)
print(f"Blocking recall    : {s2_recall:.4%}")

S2
Total true matches : 3693619
Captured matches   : 1447011
Blocking recall    : 39.1760%

In [ ]:
s3_address_index = build_address_index(S3_PATH)

s3_addr_total, s3_addr_captured, s3_addr_recall = calculate_block_recall(
    s1_blocking,
    gt_lookup,
    s3_address_index,
    "S3-",
    "address_norm"
)

print("S3")
print("Total true matches :", s3_addr_total)
print("Captured matches   :", s3_addr_captured)
print(f"Address + country recall: {s3_addr_recall:.4%}")

S3
Total true matches : 3944746
Captured matches   : 170441
Address + country recall: 4.3207%

In [ ]:
del s2_index
del s3_index
gc.collect()
print("Name indexes cleared from memory.")

Name indexes cleared from memory.

In [ ]:
print("Building S2 address index...")
s2_address_index = build_address_index(S2_PATH)
print("S2 address blocks:", len(s2_address_index))

Building S2 address index...
S2 address blocks: 4090600

In [ ]:
s2_addr_total, s2_addr_captured, s2_addr_recall = calculate_block_recall(
    s1_blocking,
    gt_lookup,
    s2_address_index,
    "S2-",
    "address_norm"
)

print("S2")
print("Total true matches :", s2_addr_total)
print("Captured matches   :", s2_addr_captured)
print(f"Address + country recall: {s2_addr_recall:.4%}")

S2
Total true matches : 3693619
Captured matches   : 719297
Address + country recall: 19.4740%

In [ ]:
del s2_address_index
gc.collect()
print("S2 address index cleared.")

S2 address index cleared.

In [ ]:
print("Building S3 address index...")
s3_address_index = build_address_index(S3_PATH)
print("S3 address blocks:", len(s3_address_index))

Building S3 address index...
S3 address blocks: 4437787

In [ ]:
s3_address_index = build_address_index(S3_PATH)

s3_addr_total, s3_addr_captured, s3_addr_recall = calculate_block_recall(
    s1_blocking,
    gt_lookup,
    s3_address_index,
    "S3-",
    "address_norm"
)

print("S3")
print("Total true matches :", s3_addr_total)
print("Captured matches   :", s3_addr_captured)
print(f"Address + country recall: {s3_addr_recall:.4%}")

S3
Total true matches : 3944746
Captured matches   : 170441
Address + country recall: 4.3207%

In [ ]:
del s3_address_index
gc.collect()

33

In [ ]:
# Show some S1 entities that have known S2 matches
# and compare their normalized name/address fields.

sample_s1_ids = []

for s1_id, matches in gt_lookup.items():
    s2_matches = [x for x in matches if x.startswith("S2-")]
    if s2_matches:
        sample_s1_ids.append((s1_id, s2_matches[:3]))

    if len(sample_s1_ids) >= 10:
        break

sample_s1_ids

[('S1-965667', ['S2-681193310', 'S2-743505751']),
 ('S1-55344266', ['S2-249013014', 'S2-197070651']),
 ('S1-343815751', ['S2-790675320', 'S2-479876582']),
 ('S1-656753428', ['S2-24659151', 'S2-153058913']),
 ('S1-102811957', ['S2-478959098', 'S2-553508714', 'S2-625774905']),
 ('S1-18727616', ['S2-755677256']),
 ('S1-318373630', ['S2-660036492']),
 ('S1-29845983', ['S2-648035184']),
 ('S1-789009573', ['S2-383871912']),
 ('S1-730934468', ['S2-356983532'])]

In [ ]:
sample_ids = [x[0] for x in sample_s1_ids]
sample_s2_ids = [
    match
    for _, matches in sample_s1_ids
    for match in matches
]

s1_sample = pd.read_csv(
    S1_PATH,
    sep="\t",
    dtype="string"
)

s2_sample = pd.read_csv(
    S2_PATH,
    sep="\t",
    dtype="string"
)

s1_sample = s1_sample[
    s1_sample["entity_id"].isin(sample_ids)
]

s2_sample = s2_sample[
    s2_sample["entity_id"].isin(sample_s2_ids)
]

print("S1 samples:")
display(
    s1_sample[
        ["entity_id", "business_name", "business_address",
         "name_core", "address_norm"]
    ]
)

print("\nS2 matching samples:")
display(
    s2_sample[
        ["entity_id", "business_name", "business_address",
         "name_core", "address_norm"]
    ]
)

S1 samples:

,entity_id,business_name,business_address,name_core,address_norm
539414,S1-102811957,Payne Enterprises,"3315 Fremont Street, Peoria, IL",payne enterprises,3315 fremont st peoria il
547338,S1-343815751,Dahlia Power Reliable Scientific LLC,"630 45th Terrace, Kansas City, MO",dahlia power reliable scientific,630 45th terrace kansas city mo
603899,S1-318373630,Red Ventures Private Limited,"Rajasthan, Jaipur, Banipark, Gokul Apartment, ...",red ventures,rajasthan jaipur banipark gokul apt e 3a kanti...
1043869,S1-730934468,Orellana Investments LLC,"728 A Quail Avenue, Fl Ground Floor, Geneva, IA",orellana investments,728 a quail ave fl ground floor geneva ia
1072115,S1-656753428,Ss Food Private Limited,"Af-684, Nandgram Near Mother India Public Scho...",ss food,af 684 nandgram near mother india public schoo...
1232493,S1-29845983,Hendricks and Flowers Inc,"33 Sleepy Hollow Drive, Danbury, CT",hendricks and flowers,33 sleepy hollow dr danbury ct
1265942,S1-789009573,Hotel Enterprises Limited,"Wz-187C Shop No.13, 14 Kh. No.47 S/F. Vikaspur...",hotel enterprises,wz 187c shop no 13 14 kh no 47 s f vikaspuri b...
1286323,S1-965667,Maure Williams Colombier Inc,"85 Wayne Avenue, Ticonderoga, NY",maure williams colombier,85 wayne ave ticonderoga ny
1898165,S1-55344266,Raj Investments LLP,"6(29), C.I.T. Colony, 2Nd Main Road Mylapore, ...",raj investments,6 29 c i t colony 2nd main rd mylapore chennai...
2117972,S1-18727616,Lumay Boral,"1056 Belden Avenue, Akron, OH",lumay boral,1056 belden ave akron oh

S2 matching samples:

,entity_id,business_name,business_address,name_core,address_norm
191919,S2-648035184,Hendricks and Flowers Inc,"CT, SLEEPY HOLLOW DRIVE, DANBURY",hendricks and flowers,ct sleepy hollow dr danbury
223808,S2-755677256,Lumay Boral Inc.,"1056-1060 BELDEN AVE, PO BOX 8807, AKRON, OH",lumay boral,1056 1060 belden ave po box 8807 akron oh
385243,S2-625774905,PAYNE-ENRTPRMISES,"3315 FREMONT SAINT, PEORIA, IL",payne enrtprmises,3315 fremont saint peoria il
488130,S2-383871912,होटल एंटरप्राइजेज लिमिटेड,"WZ-187C SHOP NO.13, DELHI, WEST DELHI, Delhi",ह टल ए टरप र इज ज ल म ट ड,wz 187c shop no 13 delhi west delhi delhi
731099,S2-478959098,Payne Énterprises,"3315 FREMONT ST, PEORIA, IL",payne énterprises,3315 fremont st peoria il
809231,S2-660036492,रेड वेंचर्स प्राइवेट लिमिटेड,"G-1, BANIPARK, JAIPUR, Rajasthan",र ड व चर स प र इव ट ल म ट ड,g 1 banipark jaipur rajasthan
1376739,S2-681193310,Maure Wilblims Colombier Inc,<NA>,maure wilblims colombier,<NA>
1776076,S2-553508714,Payne Enterpires,"3315 FREMONT ST, PEORIA, IL",payne enterpires,3315 fremont st peoria il
1886844,S2-197070651,Raj Investments LLP,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",raj investments,6 29 c i t colony 2nd main rd mylapore chennai...
1901972,S2-479876582,Dahlia Power Reliable Scientific,"45ND TERRACE, null, KANSAS CITY, MO",dahlia power reliable scientific,45nd terrace null kansas city mo
2003754,S2-743505751,Maure Williams Colombier,<NA>,maure williams colombier,<NA>
2630198,S2-153058913,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, NANDGRAM NEAR MOTHER INDIA PUBLIC SCH...",एसएस फ ड प र इव ट ल म ट ड,af 0684 nandgram near mother india public scho...
3579917,S2-790675320,Dahlia Power Reliable,"KANSAS CITY, MO, 630 45ND TERRACE, null",dahlia power reliable,kansas city mo 630 45nd terrace null
3867924,S2-356983532,Orellana Investments Investments Llc,<NA>,orellana investments investments,<NA>
4130950,S2-249013014,ராஜ் இன்வெஸ்ட்மெண்ட்ஸ் எல்எல்பி,"6(29), C.I.T. COLONY, 2ND MAIN ROAD MYLAPORE, ...",ர ஜ இன வ ஸ ட ம ண ட ஸ எல எல ப,6 29 c i t colony 2nd main rd mylapore chennai...
5014138,S2-24659151,एसएस फूड प्राइवेट लिमिटेड,"AF-0684, Uttar Pradesh, GHAZIABAD, 9487203",एसएस फ ड प र इव ट ल म ट ड,af 0684 uttar pradesh ghaziabad 9487203

In [ ]:
from collections import Counter
import pandas as pd
import gc

token_counts = Counter()

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["name_core"],
    chunksize=200_000,
    dtype={"name_core": "string"}
):
    for name in chunk["name_core"].dropna():
        tokens = set(name.split())

        for token in tokens:
            if token:
                token_counts[token] += 1

    del chunk
    gc.collect()

print("Unique name tokens:", len(token_counts))

print("\nMost common tokens:")
for token, count in token_counts.most_common(30):
    print(f"{token:30} {count:,}")

Unique name tokens: 810506

Most common tokens:
ल                              237,102
ट                              232,862
र                              226,825
ड                              208,515
प                              206,868
म                              206,488
com                            201,464
center                         193,696
ltd                            161,428
स                              160,325
इव                             157,955
partners                       152,694
pvt                            147,583
services                       145,239
group                          139,390
s                              138,303
llc                            121,171
and                            118,201
c                              113,281
india                          110,684
क                              105,891
holdings                       97,019
l                              93,771
care                           88,788
of                             87,992
inc                            86,846
associates                     73,221
ज                              69,152
न                              58,535
ग                              56,675

In [ ]:
NAME_STOPWORDS = {
    "inc", "incorporated",
    "llc",
    "ltd", "limited",
    "pvt", "private",
    "company", "co",
    "corp", "corporation",
    "group",
    "services",
    "partners",
    "holdings",
    "associates",
    "center",
    "india",
    "and",
    "of"
}

def meaningful_tokens(name):
    if pd.isna(name) or not str(name).strip():
        return []

    tokens = str(name).split()

    return [
        token for token in tokens
        if token not in NAME_STOPWORDS
        and len(token) >= 2
    ]

In [ ]:
examples = [
    "payne enterprises",
    "payne enrtprmises",
    "maure williams colombier",
    "maure wilblims colombier",
    "dahlia power reliable scientific",
    "dahlia power reliable",
    "raj investments",
    "ss food",
    "orellana investments investments"
]

for name in examples:
    print(name, "->", meaningful_tokens(name))

payne enterprises -> ['payne', 'enterprises']
payne enrtprmises -> ['payne', 'enrtprmises']
maure williams colombier -> ['maure', 'williams', 'colombier']
maure wilblims colombier -> ['maure', 'wilblims', 'colombier']
dahlia power reliable scientific -> ['dahlia', 'power', 'reliable', 'scientific']
dahlia power reliable -> ['dahlia', 'power', 'reliable']
raj investments -> ['raj', 'investments']
ss food -> ['ss', 'food']
orellana investments investments -> ['orellana', 'investments', 'investments']

In [ ]:
from collections import Counter
import gc
import pandas as pd

meaningful_token_counts = Counter()

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["name_core"],
    chunksize=200_000,
    dtype={"name_core": "string"}
):
    for name in chunk["name_core"].dropna():
        for token in set(meaningful_tokens(name)):
            meaningful_token_counts[token] += 1

    del chunk
    gc.collect()

print("Unique meaningful tokens:", len(meaningful_token_counts))

print("\nMost common meaningful tokens:")
for token, count in meaningful_token_counts.most_common(30):
    print(f"{token:30} {count:,}")

Unique meaningful tokens: 810209

Most common meaningful tokens:
com                            201,464
इव                             157,955
care                           88,788
service                        55,261
health                         51,338
enterprises                    49,341
lp                             47,941
industries                     47,928
clinic                         46,246
ventures                       44,338
the                            42,897
solutions                      41,013
public                         36,965
pc                             35,772
global                         35,242
brothers                       35,234
trading                        35,098
pediatric                      32,974
medicine                       31,536
technologies                   30,230
exports                        29,692
यर                             29,249
dental                         26,003
dr                             25,806
shri                           25,712
sri                            25,680
international                  25,578
mr                             25,554
smt                            25,492
trust                          24,748

In [ ]:
from collections import Counter

frequency_buckets = {
    "1": 0,
    "2-5": 0,
    "6-10": 0,
    "11-50": 0,
    "51-100": 0,
    "101-500": 0,
    "501-1000": 0,
    "1001-5000": 0,
    "5001-10000": 0,
    "10001-50000": 0,
    "50001+": 0
}

for token, count in meaningful_token_counts.items():

    if count == 1:
        frequency_buckets["1"] += 1
    elif count <= 5:
        frequency_buckets["2-5"] += 1
    elif count <= 10:
        frequency_buckets["6-10"] += 1
    elif count <= 50:
        frequency_buckets["11-50"] += 1
    elif count <= 100:
        frequency_buckets["51-100"] += 1
    elif count <= 500:
        frequency_buckets["101-500"] += 1
    elif count <= 1000:
        frequency_buckets["501-1000"] += 1
    elif count <= 5000:
        frequency_buckets["1001-5000"] += 1
    elif count <= 10000:
        frequency_buckets["5001-10000"] += 1
    elif count <= 50000:
        frequency_buckets["10001-50000"] += 1
    else:
        frequency_buckets["50001+"] += 1

for bucket, count in frequency_buckets.items():
    print(f"{bucket:>12}: {count:,}")

           1: 640,328
         2-5: 88,666
        6-10: 24,300
       11-50: 38,107
      51-100: 9,998
     101-500: 6,224
    501-1000: 1,273
   1001-5000: 911
  5001-10000: 161
 10001-50000: 236
      50001+: 5

In [ ]:
from collections import defaultdict
import pandas as pd
import gc

MIN_TOKEN_FREQ = 2
MAX_TOKEN_FREQ = 500

# Keeps only tokens that occur in the useful frequency range
allowed_tokens = {
    token
    for token, count in meaningful_token_counts.items()
    if MIN_TOKEN_FREQ <= count <= MAX_TOKEN_FREQ
}

print("Allowed tokens:", len(allowed_tokens))

Allowed tokens: 167295

In [ ]:
def build_token_index(path, allowed_tokens):
    index = defaultdict(list)

    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "name_core"],
        chunksize=200_000,
        dtype={
            "entity_id": "string",
            "name_core": "string"
        }
    ):
        for entity_id, name in zip(
            chunk["entity_id"],
            chunk["name_core"]
        ):
            if pd.isna(name):
                continue

            tokens = set(meaningful_tokens(name))

            for token in tokens:
                if token in allowed_tokens:
                    index[token].append(entity_id)

        del chunk
        gc.collect()

    return index

In [ ]:
print("Building S2 token index...")
s2_token_index = build_token_index(
    S2_PATH,
    allowed_tokens
)

print("S2 token blocks:", len(s2_token_index))

Building S2 token index...
S2 token blocks: 167295

In [ ]:
def calculate_token_block_recall(
    s1_df,
    gt_lookup,
    token_index,
    prefix
):
    total_matches = 0
    captured_matches = 0

    for row in s1_df.itertuples(index=False):

        s1_id = row.entity_id
        name = row.name_core

        true_ids = {
            x for x in gt_lookup.get(s1_id, set())
            if x.startswith(prefix)
        }

        if not true_ids:
            continue

        total_matches += len(true_ids)

        if pd.isna(name):
            continue

        tokens = set(meaningful_tokens(name))

        candidate_set = set()

        for token in tokens:
            if token in allowed_tokens:
                candidate_set.update(token_index.get(token, []))

        captured_matches += len(
            true_ids.intersection(candidate_set)
        )

    recall = (
        captured_matches / total_matches
        if total_matches else 0
    )

    return total_matches, captured_matches, recall

In [ ]:
s2_token_total, s2_token_captured, s2_token_recall = \
    calculate_token_block_recall(
        s1,
        gt_lookup,
        s2_token_index,
        "S2-")

print("S2 total true matches:", s2_token_total)
print("S2 captured matches:", s2_token_captured)
print(f"S2 token blocking recall: {s2_token_recall:.4%}")

S2 total true matches: 3693619
S2 captured matches: 1568457
S2 token blocking recall: 42.4640%

In [ ]:
def token_candidate_stats(s1_df, token_index, sample_size=10000):
    candidate_counts = []

    for i, row in enumerate(s1_df.itertuples(index=False)):

        if i >= sample_size:
            break

        name = row.name_core

        if pd.isna(name):
            candidate_counts.append(0)
            continue

        tokens = set(meaningful_tokens(name))

        candidate_set = set()

        for token in tokens:
            if token in allowed_tokens:
                candidate_set.update(
                    token_index.get(token, [])
                )

        candidate_counts.append(len(candidate_set))

    s = pd.Series(candidate_counts)

    return {
        "sample_size": len(s),
        "mean": s.mean(),
        "median": s.median(),
        "p90": s.quantile(0.90),
        "p95": s.quantile(0.95),
        "p99": s.quantile(0.99),
        "max": s.max(),
        "zero_candidates": (s == 0).sum()
    }

In [ ]:
s2_token_stats = token_candidate_stats(
    s1,
    s2_token_index,
    sample_size=10000
)

s2_token_stats

{'sample_size': 10000,
 'mean': np.float64(69.5515),
 'median': 0.0,
 'p90': np.float64(242.10000000000036),
 'p95': np.float64(357.0),
 'p99': np.float64(517.0),
 'max': 995,
 'zero_candidates': np.int64(5161)}

In [ ]:
def calculate_union_recall(
    s1_df,
    gt_lookup,
    name_index,
    token_index,
    allowed_tokens,
    prefix
):
    total_matches = 0
    captured_matches = 0

    for row in s1_df.itertuples(index=False):
        s1_id = row.entity_id
        country = row.country_norm
        name = row.name_core
        true_ids = {
            x for x in gt_lookup.get(s1_id, set())
            if x.startswith(prefix)
        }

        if not true_ids:
            continue

        total_matches += len(true_ids)
        candidate_set = set()

        if pd.notna(name):
            candidate_set.update(
                name_index.get((country, name), [])
            )

        if pd.notna(name):

            tokens = set(meaningful_tokens(name))
            for token in tokens:
                if token in allowed_tokens:
                    candidate_set.update(
                        token_index.get(token, [])
                    )

        captured_matches += len(
            true_ids.intersection(candidate_set)
        )

    recall = (
        captured_matches / total_matches
        if total_matches else 0
    )

    return total_matches, captured_matches, recall

In [ ]:
s2_union_total, s2_union_captured, s2_union_recall = \
    calculate_union_recall(
        s1,
        gt_lookup,
        s2_name_index,
        s2_token_index,
        allowed_tokens,
        "S2-"
    )

print("S2 total true matches:", s2_union_total)
print("S2 captured matches:", s2_union_captured)
print(f"S2 union blocking recall: {s2_union_recall:.4%}")

S2 total true matches: 3693619
S2 captured matches: 2255373
S2 union blocking recall: 61.0613%

In [ ]:
address_token_counts = Counter()
for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["address_norm"],
    chunksize=200_000,
    dtype={"address_norm": "string"}
):
    for address in chunk["address_norm"].dropna():

        tokens = set(str(address).split())

        for token in tokens:
            if token:
                address_token_counts[token] += 1
    del chunk
    gc.collect()

print("Unique address tokens:", len(address_token_counts))
print("\nMost common address tokens:")
for token, count in address_token_counts.most_common(40):
    print(f"{token:30} {count:,}")

Unique address tokens: 607900

Most common address tokens:
rd                             998,770
no                             916,457
st                             668,885
dr                             499,393
ave                            417,689
floor                          319,586
maharashtra                    319,026
city                           298,419
tx                             292,289
nagar                          286,965
1                              281,622
a                              265,469
delhi                          262,478
c                              254,392
ln                             233,983
2                              228,483
ny                             225,422
pradesh                        214,708
new                            210,472
nc                             207,687
west                           200,360
oh                             187,361
h                              186,400
b                              183,628
plot                           178,181
ct                             173,664
il                             165,947
mumbai                         162,531
o                              154,053
र                              137,492
null                           131,794
va                             131,283
tn                             131,049
ma                             125,903
az                             124,432
uttar                          123,770
3                              121,045
d                              118,380
s                              117,498
karnataka                      117,453

In [ ]:
frequency_buckets_address = {
    "1": 0,
    "2-5": 0,
    "6-10": 0,
    "11-50": 0,
    "51-100": 0,
    "101-500": 0,
    "501-1000": 0,
    "1001-5000": 0,
    "5001-10000": 0,
    "10001-50000": 0,
    "50001+": 0
}

for token, count in address_token_counts.items():
    if count == 1:
        frequency_buckets_address["1"] += 1
    elif count <= 5:
        frequency_buckets_address["2-5"] += 1
    elif count <= 10:
        frequency_buckets_address["6-10"] += 1
    elif count <= 50:
        frequency_buckets_address["11-50"] += 1
    elif count <= 100:
        frequency_buckets_address["51-100"] += 1
    elif count <= 500:
        frequency_buckets_address["101-500"] += 1
    elif count <= 1000:
        frequency_buckets_address["501-1000"] += 1
    elif count <= 5000:
        frequency_buckets_address["1001-5000"] += 1
    elif count <= 10000:
        frequency_buckets_address["5001-10000"] += 1
    elif count <= 50000:
        frequency_buckets_address["10001-50000"] += 1
    else:
        frequency_buckets_address["50001+"] += 1

for bucket, count in frequency_buckets_address.items():
    print(f"{bucket:>12}: {count:,}")

           1: 197,573
         2-5: 253,143
        6-10: 57,323
       11-50: 65,176
      51-100: 13,387
     101-500: 15,221
    501-1000: 2,798
   1001-5000: 2,500
  5001-10000: 348
 10001-50000: 317
      50001+: 114

In [ ]:
MIN_ADDRESS_TOKEN_FREQ = 2
MAX_ADDRESS_TOKEN_FREQ = 500

allowed_address_tokens = {
    token
    for token, count in address_token_counts.items()
    if MIN_ADDRESS_TOKEN_FREQ <= count <= MAX_ADDRESS_TOKEN_FREQ
}

print("Allowed address tokens:", len(allowed_address_tokens))

Allowed address tokens: 404250

In [ ]:
from collections import defaultdict
import gc
import pandas as pd

def build_address_token_index(path, allowed_tokens):
    index = defaultdict(list)
    for chunk in pd.read_csv(
        path,
        sep="\t",
        usecols=["entity_id", "address_norm"],
        chunksize=200_000,
        dtype={
            "entity_id": "string",
            "address_norm": "string"
        }
    ):
        for entity_id, address in zip(
            chunk["entity_id"],
            chunk["address_norm"]
        ):
            if pd.isna(address):
                continue

            tokens = set(str(address).split())

            for token in tokens:
                if token in allowed_tokens:
                    index[token].append(entity_id)

        del chunk
        gc.collect()

    return index

In [ ]:
print("Building S2 address-token index...")
s2_address_token_index = build_address_token_index(S2_PATH, allowed_address_tokens)

print("S2 address-token blocks:", len(s2_address_token_index))

Building S2 address-token index...
S2 address-token blocks: 404250

In [ ]:
def address_token_candidate_stats(
    s1_df,
    address_token_index,
    allowed_tokens,
    sample_size=10000
):
    candidate_counts = []

    for i, row in enumerate(s1_df.itertuples(index=False)):

        if i >= sample_size:
            break

        address = row.address_norm

        if pd.isna(address):
            candidate_counts.append(0)
            continue

        tokens = set(str(address).split())

        candidate_set = set()

        for token in tokens:
            if token in allowed_tokens:
                candidate_set.update(
                    address_token_index.get(token, [])
                )

        candidate_counts.append(len(candidate_set))

    s = pd.Series(candidate_counts)

    return {
        "sample_size": len(s),
        "mean": s.mean(),
        "median": s.median(),
        "p90": s.quantile(0.90),
        "p95": s.quantile(0.95),
        "p99": s.quantile(0.99),
        "max": s.max(),
        "zero_candidates": (s == 0).sum()
    }

In [ ]:
S1_ADDRESS_PATH = S1_PATH

s1_address = pd.read_csv(
    S1_ADDRESS_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "country_norm",
        "address_norm"
    ],
    dtype={
        "entity_id": "string",
        "country_norm": "string",
        "address_norm": "string"
    }
)

print(s1_address.shape)
print(s1_address.columns.tolist())

(2206821, 3)
['entity_id', 'address_norm', 'country_norm']

In [ ]:
s2_address_token_stats = address_token_candidate_stats(
    s1_address,
    s2_address_token_index,
    allowed_address_tokens,
    sample_size=10000
)

s2_address_token_stats

{'sample_size': 10000,
 'mean': np.float64(203.0828),
 'median': 131.5,
 'p90': np.float64(498.10000000000036),
 'p95': np.float64(641.0),
 'p99': np.float64(887.0200000000004),
 'max': 1794,
 'zero_candidates': np.int64(2228)}

In [ ]:
def calculate_address_token_recall(
    s1_df,
    gt_lookup,
    address_token_index,
    allowed_tokens,
    prefix
):
    total_matches = 0
    captured_matches = 0

    for row in s1_df.itertuples(index=False):

        s1_id = row.entity_id
        address = row.address_norm

        true_ids = {
            x for x in gt_lookup.get(s1_id, set())
            if x.startswith(prefix)
        }

        if not true_ids:
            continue

        total_matches += len(true_ids)

        if pd.isna(address):
            continue

        tokens = set(str(address).split())

        candidate_set = set()

        for token in tokens:
            if token in allowed_tokens:
                candidate_set.update(
                    address_token_index.get(token, [])
                )

        captured_matches += len(
            true_ids.intersection(candidate_set)
        )

    recall = (
        captured_matches / total_matches
        if total_matches else 0
    )

    return total_matches, captured_matches, recall

In [ ]:
s2_addr_token_total, s2_addr_token_captured, s2_addr_token_recall = \
    calculate_address_token_recall(
        s1_address,
        gt_lookup,
        s2_address_token_index,
        allowed_address_tokens,
        "S2-"
    )

print("S2 total true matches:", s2_addr_token_total)
print("S2 captured matches:", s2_addr_token_captured)
print(f"S2 address-token blocking recall: {s2_addr_token_recall:.4%}")

S2 total true matches: 3693619
S2 captured matches: 2523099
S2 address-token blocking recall: 68.3097%

In [ ]:
def calculate_three_way_union_recall(
    s1_df,
    gt_lookup,
    name_index,
    token_index,
    address_token_index,
    allowed_name_tokens,
    allowed_address_tokens,
    prefix
):
    total_matches = 0
    captured_matches = 0

    for row in s1_df.itertuples(index=False):

        s1_id = row.entity_id
        country = row.country_norm
        name = row.name_core
        address = row.address_norm

        true_ids = {
            x for x in gt_lookup.get(s1_id, set())
            if x.startswith(prefix)
        }

        if not true_ids:
            continue

        total_matches += len(true_ids)

        candidate_set = set()

        # BLOCKER 1: Exact country + name
        if pd.notna(name):
            candidate_set.update(
                name_index.get((country, name), [])
            )

        # BLOCKER 2: Name tokens
        if pd.notna(name):

            name_tokens = set(
                meaningful_tokens(name)
            )

            for token in name_tokens:

                if token in allowed_name_tokens:
                    candidate_set.update(
                        token_index.get(token, [])
                    )

        # BLOCKER 3: Address tokens
        if pd.notna(address):

            address_tokens = set(
                str(address).split()
            )

            for token in address_tokens:

                if token in allowed_address_tokens:
                    candidate_set.update(
                        address_token_index.get(token, [])
                    )

        captured_matches += len(
            true_ids.intersection(candidate_set)
        )

    recall = (
        captured_matches / total_matches
        if total_matches else 0
    )

    return total_matches, captured_matches, recall

In [ ]:
s2_all_total, s2_all_captured, s2_all_recall = \
    calculate_three_way_union_recall(
        s1_blocking,
        gt_lookup,
        s2_name_index,
        s2_token_index,
        s2_address_token_index,
        allowed_tokens,
        allowed_address_tokens,
        "S2-"
    )

print("S2 total true matches:", s2_all_total)
print("S2 captured matches:", s2_all_captured)
print(f"S2 three-way blocking recall: {s2_all_recall:.4%}")

S2 total true matches: 3693619
S2 captured matches: 3222405
S2 three-way blocking recall: 87.2425%

In [ ]:
def find_missed_s2_matches(
    s1_df,
    gt_lookup,
    name_index,
    token_index,
    address_token_index,
    allowed_name_tokens,
    allowed_address_tokens,
    sample_limit=100
):
    missed = []

    for row in s1_df.itertuples(index=False):

        s1_id = row.entity_id
        country = row.country_norm
        name = row.name_core
        address = row.address_norm

        true_ids = {
            x for x in gt_lookup.get(s1_id, set())
            if x.startswith("S2-")
        }

        if not true_ids:
            continue

        candidate_set = set()
        if pd.notna(name):
            candidate_set.update(
                name_index.get((country, name), [])
            )
        if pd.notna(name):
            for token in set(meaningful_tokens(name)):
                if token in allowed_name_tokens:
                    candidate_set.update(
                        token_index.get(token, [])
                    )
        if pd.notna(address):
            for token in set(str(address).split()):
                if token in allowed_address_tokens:
                    candidate_set.update(
                        address_token_index.get(token, [])
                    )

        missed_ids = true_ids - candidate_set

        for s2_id in missed_ids:

            missed.append({
                "s1_id": s1_id,
                "s2_id": s2_id
            })

            if len(missed) >= sample_limit:
                return missed

    return missed

In [ ]:
# Taking 100 missing S2 examples:
missed_s2 = find_missed_s2_matches(
    s1_blocking,
    gt_lookup,
    s2_name_index,
    s2_token_index,
    s2_address_token_index,
    allowed_tokens,
    allowed_address_tokens,
    sample_limit=100
)

print("Missed examples collected:", len(missed_s2))
missed_s2[:10]

Missed examples collected: 100

[{'s1_id': 'S1-133037285', 's2_id': 'S2-407207105'},
 {'s1_id': 'S1-27541239', 's2_id': 'S2-199341916'},
 {'s1_id': 'S1-629417405', 's2_id': 'S2-928426462'},
 {'s1_id': 'S1-504790211', 's2_id': 'S2-340882825'},
 {'s1_id': 'S1-865131206', 's2_id': 'S2-657355663'},
 {'s1_id': 'S1-626914593', 's2_id': 'S2-563003232'},
 {'s1_id': 'S1-597762257', 's2_id': 'S2-152865025'},
 {'s1_id': 'S1-597762257', 's2_id': 'S2-750318376'},
 {'s1_id': 'S1-597762257', 's2_id': 'S2-535895394'},
 {'s1_id': 'S1-252242682', 's2_id': 'S2-84842746'}]

In [ ]:
missed_s1_ids = {
    x["s1_id"]
    for x in missed_s2}
missed_s2_ids = {
    x["s2_id"]
    for x in missed_s2
}

In [ ]:
s1_missed_sample = s1_blocking[
    s1_blocking["entity_id"].isin(missed_s1_ids)
].copy()

In [ ]:
s2_missed_sample = []

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "business_address",
        "country_norm",
        "name_core",
        "address_norm"
    ],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "business_name": "string",
        "business_address": "string",
        "country_norm": "string",
        "name_core": "string",
        "address_norm": "string"
    }
):
    matched = chunk[
        chunk["entity_id"].isin(missed_s2_ids)
    ]

    if len(matched):
        s2_missed_sample.append(matched)

    del chunk
    gc.collect()

s2_missed_sample = pd.concat(
    s2_missed_sample,
    ignore_index=True
)

print("S2 missed records retrieved:", len(s2_missed_sample))

S2 missed records retrieved: 100

In [ ]:
missed_pairs = pd.DataFrame(missed_s2)
missed_pairs = (
    missed_pairs
    .merge(
        s1_missed_sample,
        left_on="s1_id",
        right_on="entity_id",
        how="left",
        suffixes=("_s1", "")
    )
    .drop(columns=["entity_id"])
)

missed_pairs = (
    missed_pairs
    .merge(
        s2_missed_sample,
        left_on="s2_id",
        right_on="entity_id",
        how="left",
        suffixes=("_s1", "_s2")
    )
    .drop(columns=["entity_id"])
)

In [ ]:
print(missed_pairs.columns.tolist())

['s1_id', 's2_id', 'address_norm_s1', 'country_norm_s1', 'name_core_s1', 'business_name', 'business_address', 'address_norm_s2', 'country_norm_s2', 'name_core_s2']

In [ ]:
display(
    missed_pairs[
        [
            "s1_id",
            "s2_id",
            "business_name",
            "business_address",
            "name_core_s1",
            "name_core_s2",
            "address_norm_s1",
            "address_norm_s2"
        ]
    ].head(50)
)

,s1_id,s2_id,business_name,business_address,name_core_s1,name_core_s2,address_norm_s1,address_norm_s2
0,S1-133037285,S2-407207105,Christ [Chape1],"2100 CAMERON DR, DUNDALK, MD",christ chapel,christ chape1,2100 cameron dr unit apt g dundalk md,2100 cameron dr dundalk md
1,S1-27541239,S2-199341916,NEXUS ACORMHR RAIN,"CHURCH STREET, NASHVILLE, TN",nexus anchor rain,nexus acormhr rain,1111 church st unit 2007 nashville tn,church st nashville tn
2,S1-629417405,S2-928426462,Moore Inc Center,"337 OAKLAND AVE, MICHHIGAN CITY CITY, IN",moore bitwise,moore inc center,337 oakland ave michigan city in,337 oakland ave michhigan city city in
3,S1-504790211,S2-340882825,Crystal PC Lending,<NA>,crystal lending pc,crystal pc lending,11643 prosperity rd south jordan ut,<NA>
4,S1-865131206,S2-657355663,HELI0S LP,"66 EDGEWOOD ST, BRIDGEPORT, CT",helios,heli0s lp,66 edgewood st bridgeport ct,66 edgewood st bridgeport ct
5,S1-626914593,S2-563003232,Unified Choice Dynamx,"MIDDLE RIVER, 2701 Eastern Blvd, MD",unified choice dynamix,unified choice dynamx,unit bldg 3030 md 2701 eastern blvd middle river,middle river 2701 eastern blvd md
6,S1-597762257,S2-152865025,ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड,"E-7, NEW DELHI, SECOND FLOOR, SOUTH DELHI, Delhi",green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,e 7 second floor new delhi south delhi delhi,e 7 new delhi second floor south delhi delhi
7,S1-597762257,S2-750318376,ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड,"E-7, SECOND FLOOR, NEW DELHI, SOUTH DELHI, Delhi",green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,e 7 second floor new delhi south delhi delhi,e 7 second floor new delhi south delhi delhi
8,S1-597762257,S2-535895394,ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड,"E-7, SECOND FLOOR, NEW DELHI, SOUTH DELHI, दिल्ली",green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,e 7 second floor new delhi south delhi delhi,e 7 second floor new delhi south delhi द ल ल
9,S1-252242682,S2-84842746,*** aggieenagle.com,"54ND AVENUE, MINNEAPLIS, MN",aggie e nagle l c s w,aggieenagle com,11900 54th ave plymouth mn,54nd ave minneaplis mn
10,S1-883973644,S2-346262429,GLOBAL HOGNANINN LLC,"4024B 39RD AVE, SEATTLE, WA",global hovnanian,global hognaninn,4024 39th ave seattle wa,4024b 39rd ave seattle wa
11,S1-17666546,S2-341313901,Pacific Learning Laboratories L.L.C.,<NA>,pacific learning laboratories,pacific learning laboratories l l c,4810 nassau ave sand springs ok,<NA>
12,S1-602913883,S2-837366545,catelecom.com,"65 LINDEN STREET, WELLESLEY, MA",cascade allied telecom,catelecom com,165 linden st unit 106 wellesley ma,65 linden st wellesley ma
13,S1-401372098,S2-58252265,INC APEX,"108 RICHARDSON ST, BETHANY, WV",apex,inc apex,108 richardson st bethany wv,108 richardson st bethany wv
14,S1-401372098,S2-687064785,Apex Inc Services,"108 RICHARDSON STREET, BETHANY, WV",apex,apex inc services,108 richardson st bethany wv,108 richardson st bethany wv
15,S1-134898809,S2-156312637,Brixlyra,"PMB 9599, MA, BEVERLY, 0026 STONE ST",corner hypnosis,brixlyra,26 stone st unit 3 beverly ma,pmb 9599 ma beverly 0026 stone st
16,S1-681392030,S2-501358496,Care of Innsdtitute Technology,"NO. 423 229, NETAJI SUBHAS CHANDRA BOSE ROAD V...",care institute of technology,care of innsdtitute technology,west bengal howrah 229 kolkata netaji subhas c...,no 423 229 netaji subhas chandra bose rd vishn...
17,S1-492467148,S2-946846997,Cure Bike Smcop,"1317 UNIVERSITY CITY BOULEVARD, PO BOX 3338, B...",cure bike shop,cure bike smcop,1317 university city blvd unit apt 5 blacksbur...,1317 university city blvd po box 3338 blacksbu...
18,S1-951599976,S2-907629838,Unified Green Tbarget LLC,"HALIFAX COUNTY, 1037. CEDAR GROVE RD, VA",unified green target,unified green tbarget,1037 cedar grove rd halifax county va,halifax county 1037 cedar grove rd va
19,S1-666876590,S2-185860935,एसएस सिस्टम्स लिमिटेड,"A-3, 401, RAHUL APARTMENT, MARVE ROAD, MUMBAI,...",ss systems,एसएस स स टम स ल म ट ड,a 1 malad west mumbai maharashtra 401 rahul ap...,a 3 401 rahul apt marve rd mumbai maharashtra
20,S1-666876590,S2-975207252,एसएस सिस्टम्स लिमिटेड,"A-3, 401, RAHUL APARTMENT, MARVE ROAD, MUMBAI ...",ss systems,एसएस स स टम स ल म ट ड,a 1 malad west mumbai maharashtra 401 rahul ap...,a 3 401 rahul apt marve rd mumbai suburban mal...
21,S1-279914306,S2-747970909,JOBST ROYAL LLC WORKS METAL,<NA>,jobst royal metal works,jobst royal llc works metal,grayson 115 paradise hill ky,<NA>
22,S1-208973592,S2-481660181,INC MORGAN AEMBERN,"266 ENTERPRISE DR, BAYOU CANE, LA",morgan ameren,inc morgan aembern,la 266 enterprise dr houma,266 enterprise dr bayou cane la
23,S1-366329737,S2-23560385,सिल्वर कंस्ट्रक्शंस एलएलपी,"#101 CTS NO, PUNE CITY, PUNE, Maharashtra",silver constructions,स ल वर क स ट रक श स एलएलप,101 cts no 917 18 f p no near british library ...,101 cts no pune city pune maharashtra
24,S1-708796012,S2-994438467,Board of Consumer Affair,"122 DAYTON YELLOW SPRINGS ROAD, FAIRBORN, OH",board of consumer affairs,board of consumer affair,122 dayton yellow springs rd unit 4 fairborn oh,122 dayton yellow springs rd fairborn oh
25,S1-912508322,S2-276782865,ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ,"Karnataka, BENGALURU, 42, BANGALORE",shiv technologies,ಶ ವ ಟ ಕ ನ ಲಜ ಸ ಎಲ ಎಲ ಪ,42 16th cross 8th main rd malleswaram bengalur...,karnataka bengaluru 42 bangalore
26,S1-912508322,S2-974864172,Dr SHIV TECHNOLOGIES,"42, 16TH CROSS, 8TH MAIN ROAD, MALLESWARAM, BE...",shiv technologies,dr shiv technologies,42 16th cross 8th main rd malleswaram bengalur...,42 16th cross 8th main rd malleswaram bengalur...
27,S1-912508322,S2-334957677,SHIV TECHNOLOGIES L.L.P.,"42, 16TH CROSS, 8TH MAIN ROAD, MALLESWARAM, BE...",shiv technologies,shiv technologies l l p,42 16th cross 8th main rd malleswaram bengalur...,42 16th cross 8th main rd malleswaram bengalur...
28,S1-544301808,S2-152166163,Advanced Bright,"HUGHES DR, PLYMOUTH, NC",advanced bright intelligent,advanced bright,142 hughes dr plymouth nc,hughes dr plymouth nc
29,S1-800915873,S2-592882465,"Adams, Williams and Alexander Carolina L.L.C.","LYNN AVE, SAINT LOUIS, MO",adams williams and alexander carolina,adams williams and alexander carolina l l c,7333 lynn ave fl 0 saint louis mo,lynn ave saint louis mo
30,S1-978421811,S2-798657992,Highland Learning,"1240 INDIANA AVENUE, SALT LAKE CITY, UT",highland learning center,highland learning,1240 indiana ave salt lake city ut,1240 indiana ave salt lake city ut
31,S1-978421811,S2-687120101,Highland Learning Centre,"1240 INDIANA AVE, UT, SALT LAKE CITY",highland learning center,highland learning centre,1240 indiana ave salt lake city ut,1240 indiana ave ut salt lake city
32,S1-216511119,S2-645205818,सूर्य एनर्जी प्राइवेट लिमिटेड,"HANS MARG, C-252-A, MALVIYA NAGAR, NAGAR JAIPU...",surya energy,स र य एनर ज प र इव ट ल म ट ड,nagar jaipur hans marg c 252 a malviya nagar r...,hans marg c 252 a malviya nagar nagar jaipur r...
33,S1-499302167,S2-148775637,શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ,"PLOT NO. 265, SURAT, ગુજરાત",shree industries,શ ર ઇન ડસ ટ ર ઝ પ ર ઇવ ટ લ મ ટ ડ,plot no 265 g i d c estate sachin surat gujarat,plot no 265 surat ગ જર ત
34,S1-499302167,S2-45522817,શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ,"PLOT NO. 265, G. I. D. C. ESTATE SACHIN, SURAT...",shree industries,શ ર ઇન ડસ ટ ર ઝ પ ર ઇવ ટ લ મ ટ ડ,plot no 265 g i d c estate sachin surat gujarat,plot no 265 g i d c estate sachin surat ગ જર ત
35,S1-499302167,S2-127669900,શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ,"G. I. D. C. ESTATE SACHIN, SURAT, PLOT NO. 265...",shree industries,શ ર ઇન ડસ ટ ર ઝ પ ર ઇવ ટ લ મ ટ ડ,plot no 265 g i d c estate sachin surat gujarat,g i d c estate sachin surat plot no 265 gujarat
36,S1-417526535,S2-566526014,Center Vanguard Inc,"STAUNTON, IL, 022899 GEORGE LN, PO BOX 2478",vanguard allstate,center vanguard,22899 george ln staunton il,staunton il 022899 george ln po box 2478
37,S1-613598143,S2-742518143,CLAIRSPROTT.COM,"430 LEWIS AVE, LOMBARD, IL",clair sprott,clairsprott com,430 lewis ave lombard il,430 lewis ave lombard il
38,S1-613598143,S2-980172703,CLAIRSPROTT.COM,"LOMBARD, IL, 430 Lewis Avenue",clair sprott,clairsprott com,430 lewis ave lombard il,lombard il 430 lewis ave
39,S1-378164861,S2-825460140,INDUSTRIAL ENTERPRISES WHÓLESALE,"BRANSON LANDING, BRANSON, MO",industrial wholesale enterprises,industrial enterprises whólesale,2507 branson landing unit unit 507b branson mo,branson landing branson mo
40,S1-639096068,S2-435057007,India Imantc Development Limited,<NA>,india impact development,india imantc development,w 21 674 beach rd alleppey alappuzha kerala,<NA>
41,S1-831843558,S2-681892599,Hernandez Regional,"ARBOR ROSE LANE, SPRING, TX",hernandez regional aktiengesellschaft,hernandez regional,7102 arbor rose ln spring tx,arbor rose ln spring tx
42,S1-846542666,S2-896746887,XYLOMIRADREX,"1717 COLE STREET, KILLEEN, TX",desert sprott,xylomiradrex,1717 cole st killeen tx,1717 cole st killeen tx
43,S1-419483044,S2-708439842,King LLC [Partners],"GRAND AVENUE, OLD ORCHARD BEACH, ME",king aria,king llc partners,215 grand ave unit apt 609 old orchard beach me,grand ave old orchard beach me
44,S1-419483044,S2-497881051,kingaria.com,"00215 GRAND AVE, OLD ORCHARD BEACH, ME",king aria,kingaria com,215 grand ave unit apt 609 old orchard beach me,00215 grand ave old orchard beach me
45,S1-787617931,S2-863761700,DELTA MÍNISTRIES IV,"BAY HILL WAY, PHOENIX, AZ",delta ministries iv,delta mínistries iv,40219 bay hill way phoenix az,bay hill way phoenix az
46,S1-535605149,S2-751164711,सुप्रीम इंजीनियरिंग एलएलपी,"SHOP-1-04, RAIGARH(MH), Maharashtra",supreme engineering,स प र म इ ज न यर ग एलएलप,shop 04 gut 41 2 plot 3 a 3 b pratham park pan...,shop 1 04 raigarh mh maharashtra
47,S1-498738124,S2-218846957,Primary Care Medicine District,"1509B PRIMROSE LANE, CARY, NC",primary care medicine,primary care medicine district,1509 primrose ln cary nc,1509b primrose ln cary nc
48,S1-748364403,S2-166464835,Eye Group Group,"JOHNSON CITY, 802 BUFFALO ST, TN",eye group,eye group group,802 buffalo st unit 8 johnson city tn,johnson city 802 buffalo st tn
49,S1-155027115,S2-780856981,भारत जय टेक,"157, BISHRAKH, GAUTAM BUDDHA NAGAR, Uttar Pradesh",bharat jai tech,भ रत जय ट क,157 udyog kendra toy cit greater noida bishrak...,157 bishrakh gautam buddha nagar uttar pradesh

In [ ]:
from difflib import SequenceMatcher
import pandas as pd

def char_similarity(a, b):
    if pd.isna(a) or pd.isna(b):
        return None

    a = str(a)
    b = str(b)

    if not a or not b:
        return None
    return SequenceMatcher(None, a, b).ratio()

missed_pairs["name_char_similarity"] = missed_pairs.apply(
    lambda row: char_similarity(
        row["name_core_s1"],
        row["name_core_s2"]
    ),
    axis=1
)

missed_pairs["address_char_similarity"] = missed_pairs.apply(
    lambda row: char_similarity(
        row["address_norm_s1"],
        row["address_norm_s2"]
    ),
    axis=1
)

print("Done.")

Done.

In [ ]:
print("Name Character Similarity")
print(
    missed_pairs["name_char_similarity"]
    .describe()
)

print("\nAddress Character Similarity")
print(
    missed_pairs["address_char_similarity"]
    .describe()
)

Name Character Similarity
count    100.000000
mean       0.586463
std        0.347140
min        0.039216
25%        0.153846
50%        0.750000
75%        0.868750
max        0.979592
Name: name_char_similarity, dtype: float64

Address Character Similarity
count    89.000000
mean      0.778370
std       0.186548
min       0.305085
25%       0.661538
50%       0.825397
75%       0.927152
max       1.000000
Name: address_char_similarity, dtype: float64

In [ ]:
bins = [0, 0.5, 0.6, 0.7, 0.8, 0.9, 1.01]
labels = [
    "<0.5",
    "0.5-0.6",
    "0.6-0.7",
    "0.7-0.8",
    "0.8-0.9",
    "0.9-1.0"
]

name_buckets = pd.cut(
    missed_pairs["name_char_similarity"],
    bins=bins,
    labels=labels,
    right=False
)

print(name_buckets.value_counts().sort_index())

name_char_similarity
<0.5       32
0.5-0.6     6
0.6-0.7     7
0.7-0.8    14
0.8-0.9    19
0.9-1.0    22
Name: count, dtype: int64

In [ ]:
display(
    missed_pairs[
        [
            "name_core_s1",
            "name_core_s2",
            "name_char_similarity",
            "address_norm_s1",
            "address_norm_s2",
            "address_char_similarity"
        ]
    ]
    .sort_values("name_char_similarity")
    .reset_index(drop=True)
)

,name_core_s1,name_core_s2,name_char_similarity,address_norm_s1,address_norm_s2,address_char_similarity
0,creative services,క ర య ట వ సర వ స స ప ర వ ట ల మ ట డ,0.039216,h no 8 3 214 1 a 1 plot no b2madhura nagar hyd...,h no 8 3 214 1 a 1 andhra pradesh hyderabad te...,0.661538
1,creative services,క ర య ట వ సర వ స స ప ర వ ట ల మ ట డ,0.039216,h no 8 3 214 1 a 1 plot no b2madhura nagar hyd...,hyderabad andhra pradesh telangana 8 3 214 1 a 1,0.544000
2,green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,0.040816,e 7 second floor new delhi south delhi delhi,e 7 new delhi second floor south delhi delhi,0.772727
3,green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,0.040816,e 7 second floor new delhi south delhi delhi,e 7 second floor new delhi south delhi delhi,1.000000
4,green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,0.040816,e 7 second floor new delhi south delhi delhi,e 7 second floor new delhi south delhi द ल ल,0.886364
...,...,...,...,...,...,...
95,gulf apex,gulf alpex,0.947368,1025 holland sylvania rd unit 5 toledo oh,oh 1025 holland sylvania rd toledo,0.826667
96,highland learning center,highland learning centre,0.958333,1240 indiana ave salt lake city ut,1240 indiana ave ut salt lake city,0.911765
97,unified green target,unified green tbarget,0.975610,1037 cedar grove rd halifax county va,halifax county 1037 cedar grove rd va,0.594595
98,unified choice dynamix,unified choice dynamx,0.976744,unit bldg 3030 md 2701 eastern blvd middle river,middle river 2701 eastern blvd md,0.567901
99,board of consumer affairs,board of consumer affair,0.979592,122 dayton yellow springs rd unit 4 fairborn oh,122 dayton yellow springs rd fairborn oh,0.919540

In [ ]:
thresholds = [0.60, 0.70, 0.80, 0.85, 0.90, 0.95]
for threshold in thresholds:
    count = (missed_pairs["name_char_similarity"] >= threshold).sum()

    print(
        f"Similarity >= {threshold:.2f}: "
        f"{count}/100 ({count:.1f}%)"
    )

Similarity >= 0.60: 62/100 (62.0%)
Similarity >= 0.70: 55/100 (55.0%)
Similarity >= 0.80: 41/100 (41.0%)
Similarity >= 0.85: 30/100 (30.0%)
Similarity >= 0.90: 22/100 (22.0%)
Similarity >= 0.95: 4/100 (4.0%)

Name vs Address Similarity

In [ ]:
def token_jaccard(a, b):
    if pd.isna(a) or pd.isna(b):
        return None

    a_tokens = set(str(a).split())
    b_tokens = set(str(b).split())

    if not a_tokens or not b_tokens:
        return None

    return len(a_tokens & b_tokens) / len(a_tokens | b_tokens)
missed_pairs["name_token_jaccard"] = missed_pairs.apply(
    lambda row: token_jaccard(
        row["name_core_s1"],
        row["name_core_s2"]
    ),
    axis=1
)

missed_pairs["address_token_jaccard"] = missed_pairs.apply(
    lambda row: token_jaccard(
        row["address_norm_s1"],
        row["address_norm_s2"]
    ),
    axis=1
)

In [ ]:
print("NAME TOKEN JACCARD")
print(missed_pairs["name_token_jaccard"].describe())

print("\nADDRESS TOKEN JACCARD")
print(missed_pairs["address_token_jaccard"].describe())

NAME TOKEN JACCARD
count    100.000000
mean       0.320810
std        0.293351
min        0.000000
25%        0.000000
50%        0.333333
75%        0.500000
max        1.000000
Name: name_token_jaccard, dtype: float64

ADDRESS TOKEN JACCARD
count    89.000000
mean      0.695194
std       0.225127
min       0.210526
25%       0.538462
50%       0.666667
75%       0.888889
max       1.000000
Name: address_token_jaccard, dtype: float64

In [ ]:
print("NAME TOKEN JACCARD")

print(
    pd.cut(
        missed_pairs["name_token_jaccard"],
        bins=[0, 0.2, 0.4, 0.6, 0.8, 1.01],
        labels=[
            "<0.2",
            "0.2-0.4",
            "0.4-0.6",
            "0.6-0.8",
            "0.8-1.0"
        ],
        right=False
    ).value_counts().sort_index()
)

print("\nADDRESS TOKEN JACCARD")

print(
    pd.cut(
        missed_pairs["address_token_jaccard"],
        bins=[0, 0.2, 0.4, 0.6, 0.8, 1.01],
        labels=[
            "<0.2",
            "0.2-0.4",
            "0.4-0.6",
            "0.6-0.8",
            "0.8-1.0"
        ],
        right=False
    ).value_counts().sort_index()
)

NAME TOKEN JACCARD
name_token_jaccard
<0.2       37
0.2-0.4    21
0.4-0.6    22
0.6-0.8    14
0.8-1.0     6
Name: count, dtype: int64

ADDRESS TOKEN JACCARD
address_token_jaccard
<0.2        0
0.2-0.4     7
0.4-0.6    24
0.6-0.8    27
0.8-1.0    31
Name: count, dtype: int64

In [ ]:
display(
    missed_pairs[
        [
            "name_core_s1",
            "name_core_s2",
            "name_char_similarity",
            "name_token_jaccard",
            "address_char_similarity",
            "address_token_jaccard"
        ]
    ]
    .sort_values(
        ["address_token_jaccard", "name_char_similarity"],
        ascending=False
    )
    .reset_index(drop=True)
)

,name_core_s1,name_core_s2,name_char_similarity,name_token_jaccard,address_char_similarity,address_token_jaccard
0,unified green target,unified green tbarget,0.975610,0.500000,0.594595,1.0
1,highland learning center,highland learning centre,0.958333,0.500000,0.911765,1.0
2,anand brothers,anand 8rothers,0.928571,0.333333,0.927152,1.0
3,cannon precious,cann0n précious,0.866667,0.000000,0.645161,1.0
4,anand brothers,anandbrothers com,0.838710,0.000000,0.768212,1.0
...,...,...,...,...,...,...
95,clean investment services,clean investment center,0.791667,0.500000,NaN,NaN
96,jobst royal metal works,jobst royal llc works metal,0.760000,0.800000,NaN,NaN
97,classic printing enterprises,classic enterprises corp services,0.622951,0.400000,NaN,NaN
98,paul holdings,paul,0.470588,0.500000,NaN,NaN
99,quartz,quartz llc enterprises,0.428571,0.333333,NaN,NaN

In [ ]:
# Filling the missing similarities with 0 (experiment)
experiment_df = missed_pairs.copy()

for col in [
    "name_char_similarity",
    "name_token_jaccard",
    "address_char_similarity",
    "address_token_jaccard"
]:
    experiment_df[col] = experiment_df[col].fillna(0)

# Address is currently the strongest signal
experiment_df["combined_similarity"] = (
    0.25 * experiment_df["name_char_similarity"] +
    0.15 * experiment_df["name_token_jaccard"] +
    0.25 * experiment_df["address_char_similarity"] +
    0.35 * experiment_df["address_token_jaccard"]
)

display(
    experiment_df[
        [
            "name_core_s1",
            "name_core_s2",
            "name_char_similarity",
            "name_token_jaccard",
            "address_char_similarity",
            "address_token_jaccard",
            "combined_similarity"
        ]
    ]
    .sort_values("combined_similarity", ascending=False)
    .reset_index(drop=True)
)

,name_core_s1,name_core_s2,name_char_similarity,name_token_jaccard,address_char_similarity,address_token_jaccard,combined_similarity
0,highland learning center,highland learning,0.829268,0.666667,1.000000,1.000000,0.907317
1,highland learning center,highland learning centre,0.958333,0.500000,0.911765,1.000000,0.892525
2,shiv technologies,dr shiv technologies,0.918919,0.666667,0.919355,0.900000,0.874568
3,anand brothers,anand 8rothers,0.928571,0.333333,0.927152,1.000000,0.863931
4,apex,inc apex,0.666667,0.500000,1.000000,1.000000,0.841667
...,...,...,...,...,...,...,...
95,shakti consulting,शक त क सल ट ग ल म ट ड,0.052632,0.000000,0.463158,0.266667,0.222281
96,classic printing enterprises,classic enterprises corp services,0.622951,0.400000,0.000000,0.000000,0.215738
97,paul holdings,paul,0.470588,0.500000,0.000000,0.000000,0.192647
98,high estate,ह ई एस ट ट ल म ट ड,0.068966,0.000000,0.305085,0.210526,0.167197
99,quartz,quartz llc enterprises,0.428571,0.333333,0.000000,0.000000,0.157143

In [ ]:
print(experiment_df["combined_similarity"].describe())

count    100.000000
mean       0.584477
std        0.208372
min        0.157143
25%        0.389999
50%        0.636902
75%        0.751012
max        0.907317
Name: combined_similarity, dtype: float64

In [ ]:
for threshold in [0.50, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85]:
    count = (experiment_df["combined_similarity"] >= threshold).sum()

    print(
        f"Combined similarity >= {threshold:.2f}: "
        f"{count}/100 ({count:.1f}%)"
    )

Combined similarity >= 0.50: 69/100 (69.0%)
Combined similarity >= 0.60: 57/100 (57.0%)
Combined similarity >= 0.65: 48/100 (48.0%)
Combined similarity >= 0.70: 38/100 (38.0%)
Combined similarity >= 0.75: 27/100 (27.0%)
Combined similarity >= 0.80: 15/100 (15.0%)
Combined similarity >= 0.85: 4/100 (4.0%)

Character N-Grams

In [ ]:
def char_ngrams(text, n=3):
    if pd.isna(text):
        return set()

    text = str(text).replace(" ", "")

    if len(text) < n:
        return {text}

    return {
        text[i:i+n]
        for i in range(len(text) - n + 1)
    }


def ngram_jaccard(a, b, n=3):
    a_grams = char_ngrams(a, n)
    b_grams = char_ngrams(b, n)

    if not a_grams or not b_grams:
        return 0.0

    return len(a_grams & b_grams) / len(a_grams | b_grams)

In [ ]:
missed_pairs["name_char3_jaccard"] = missed_pairs.apply(
    lambda row: ngram_jaccard(
        row["name_core_s1"],
        row["name_core_s2"],
        n=3
    ),
    axis=1)

missed_pairs["name_char4_jaccard"] = missed_pairs.apply(
    lambda row: ngram_jaccard(
        row["name_core_s1"],
        row["name_core_s2"],
        n=4
    ),
    axis=1)

In [ ]:
print("CHAR 3-GRAM JACCARD")
print(missed_pairs["name_char3_jaccard"].describe())
print("\nCHAR 4-GRAM JACCARD")
print(missed_pairs["name_char4_jaccard"].describe())

CHAR 3-GRAM JACCARD
count    100.000000
mean       0.385566
std        0.308936
min        0.000000
25%        0.000000
50%        0.433036
75%        0.630515
max        0.950000
Name: name_char3_jaccard, dtype: float64

CHAR 4-GRAM JACCARD
count    100.000000
mean       0.338205
std        0.299855
min        0.000000
25%        0.000000
50%        0.311422
75%        0.555556
max        0.947368
Name: name_char4_jaccard, dtype: float64

Threshold Experiment

In [ ]:
for column in [
    "name_char3_jaccard",
    "name_char4_jaccard"]:
    print(f"\n{column}")

    for threshold in [0.20, 0.30, 0.40, 0.50, 0.60, 0.70, 0.80]:
        count = (
            missed_pairs[column] >= threshold
        ).sum()

        print(
            f">= {threshold:.2f}: "
            f"{count}/100 ({count}%)"
        )

name_char3_jaccard
>= 0.20: 67/100 (67%)
>= 0.30: 57/100 (57%)
>= 0.40: 52/100 (52%)
>= 0.50: 45/100 (45%)
>= 0.60: 31/100 (31%)
>= 0.70: 19/100 (19%)
>= 0.80: 12/100 (12%)

name_char4_jaccard
>= 0.20: 58/100 (58%)
>= 0.30: 52/100 (52%)
>= 0.40: 46/100 (46%)
>= 0.50: 34/100 (34%)
>= 0.60: 22/100 (22%)
>= 0.70: 15/100 (15%)
>= 0.80: 11/100 (11%)

In [ ]:
display(
    missed_pairs[
        [
            "name_core_s1",
            "name_core_s2",
            "name_char_similarity",
            "name_token_jaccard",
            "name_char3_jaccard",
            "name_char4_jaccard"
        ]
    ]
    .sort_values("name_char3_jaccard")
    .reset_index(drop=True)
)

,name_core_s1,name_core_s2,name_char_similarity,name_token_jaccard,name_char3_jaccard,name_char4_jaccard
0,green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,0.040816,0.000000,0.000000,0.000000
1,green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,0.040816,0.000000,0.000000,0.000000
2,corner hypnosis,brixlyra,0.173913,0.000000,0.000000,0.000000
3,green logistics,ग र न ल ज स ट क स प र इव ट ल म ट ड,0.040816,0.000000,0.000000,0.000000
4,shiv technologies,ಶ ವ ಟ ಕ ನ ಲಜ ಸ ಎಲ ಎಲ ಪ,0.051282,0.000000,0.000000,0.000000
...,...,...,...,...,...,...
95,shiv technologies,dr shiv technologies,0.918919,0.666667,0.875000,0.866667
96,pacific learning laboratories,pacific learning laboratories l l c,0.906250,0.600000,0.892857,0.888889
97,operating engineers union local no 269,operating engineers union local no,0.944444,0.833333,0.903226,0.900000
98,adams williams and alexander carolina,adams williams and alexander carolina l l c,0.925000,0.714286,0.906250,0.909091
99,board of consumer affairs,board of consumer affair,0.979592,0.600000,0.950000,0.947368

3-GRAM is better than 4-GRAM

In [ ]:
char3_counter = Counter()

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["name_core"],
    chunksize=200_000,
    dtype={"name_core": "string"}
):

    for name in chunk["name_core"].dropna():
        grams = char_ngrams(name, n=3)

        char3_counter.update(grams)

    del chunk
    gc.collect()

print("Unique 3-grams:", len(char3_counter))

Unique 3-grams: 90023

In [ ]:
char3_freq = pd.Series(char3_counter)
print(char3_freq.describe())

count     90023.000000
mean        901.906091
std        7896.146677
min           1.000000
25%           2.000000
50%          10.000000
75%          69.000000
max      509272.000000
dtype: float64

In [ ]:
bins = [
    1,
    2,
    5,
    10,
    20,
    50,
    100,
    500,
    1000,
    5000,
    10000,
    float("inf")
]

labels = [
    "1",
    "2-4",
    "5-9",
    "10-19",
    "20-49",
    "50-99",
    "100-499",
    "500-999",
    "1000-4999",
    "5000-9999",
    "10000+"
]

print(
    pd.cut(
        char3_freq,
        bins=bins,
        labels=labels,
        right=False,
        include_lowest=True
    ).value_counts().sort_index()
)

1            15716
2-4          17405
5-9          11145
10-19         9223
20-49        10715
50-99         6517
100-499      10463
500-999       2692
1000-4999     3598
5000-9999      995
10000+        1554
Name: count, dtype: int64

In [ ]:
print(char3_freq.sort_values(ascending=False).head(30))

ent    509272
ter    458539
ers    436935
nte    382223
ion    380764
ing    367878
ate    292581
com    285833
tio    266353
ice    260997
art    258857
and    255983
ati    242251
ner    236182
ser    230001
cen    228713
llc    223707
rvi    220140
dia    218173
erv    217787
vic    217091
ons    209638
ind    208741
par    200443
tal    199241
लमट    190106
मटड    190091
din    188122
str    185234
ces    183961
dtype: int64

In [ ]:
allowed_char3 = {
    gram
    for gram, freq in char3_counter.items()
    if 2 <= freq <= 500}
print("Allowed 3-grams:", len(allowed_char3))

Allowed 3-grams: 65473

In [ ]:
from collections import defaultdict
import gc
import pandas as pd

char3_index = defaultdict(list)

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["entity_id", "name_core"],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "name_core": "string"
    }
):

    for entity_id, name in zip(
        chunk["entity_id"],
        chunk["name_core"]
    ):

        if pd.isna(name):
            continue

        for gram in char_ngrams(name, n=3):
            if gram in allowed_char3:
                char3_index[gram].append(entity_id)

    del chunk
    gc.collect()
print("Index blocks:", len(char3_index))

Index blocks: 65473

In [ ]:
candidate_counts = []

for row in s1_blocking.itertuples(index=False):
    name = row.name_core
    if pd.isna(name):
        candidate_counts.append(0)
        continue
    candidate_set = set()
    for gram in char_ngrams(name, n=3):
        if gram in char3_index:
            candidate_set.update(char3_index[gram])
    candidate_counts.append(len(candidate_set))
    if len(candidate_counts) >= 100_000:
        break
candidate_counts = pd.Series(candidate_counts)

print(candidate_counts.describe())
print("Zero candidates:", (candidate_counts == 0).sum())
print("Candidates > 1000:", (candidate_counts > 1000).sum())
print("Candidates > 5000:", (candidate_counts > 5000).sum())

count    100000.000000
mean         46.891170
std         140.894528
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max        2549.000000
dtype: float64
Zero candidates: 85970
Candidates > 1000: 131
Candidates > 5000: 0

In [ ]:
def calculate_char3_recall(
    s1_df,
    gt_lookup,
    char3_index,
    allowed_char3,
    prefix
):
    total_matches = 0
    captured_matches = 0

    for row in s1_df.itertuples(index=False):
        s1_id = row.entity_id
        name = row.name_core
        true_ids = {
            x for x in gt_lookup.get(s1_id, set())
            if x.startswith(prefix)
        }

        if not true_ids:
            continue

        total_matches += len(true_ids)
        candidate_set = set()
        if pd.notna(name) and name != "":
            for gram in char_ngrams(name, n=3):
                if gram in allowed_char3:
                    candidate_set.update(
                        char3_index.get(gram, [])
                    )

        captured_matches += len(
            true_ids.intersection(candidate_set)
        )
    recall = (
        captured_matches / total_matches
        if total_matches
        else 0)

    return total_matches, captured_matches, recall

In [ ]:
s2_c3_total, s2_c3_captured, s2_c3_recall = calculate_char3_recall(
    s1_blocking,
    gt_lookup,
    char3_index,
    allowed_char3,
    "S2-")

print("S2")
print("Total true matches :", s2_c3_total)
print("Captured matches   :", s2_c3_captured)
print(f"3-gram recall      : {s2_c3_recall:.4%}")

S2
Total true matches : 3693619
Captured matches   : 439775
3-gram recall      : 11.9063%

In [ ]:
print([x for x in [
        "s2_name_index",
        "token_index",
        "address_token_index",
        "allowed_name_tokens",
        "allowed_address_tokens"
    ] if x in globals()]
)

['s2_name_index', 'allowed_address_tokens']

In [ ]:
from collections import Counter, defaultdict
import gc
import pandas as pd

name_token_counter = Counter()
for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["name_core"],
    chunksize=200_000,
    dtype={"name_core": "string"}
):

    for name in chunk["name_core"].dropna():
        name_token_counter.update(
            set(meaningful_tokens(name)))

    del chunk
    gc.collect()
print("Unique name tokens:", len(name_token_counter))

Unique name tokens: 810209

In [ ]:
allowed_name_tokens = {token
    for token, freq in name_token_counter.items()
    if 2 <= freq <= 500}

print("Allowed name tokens: ", len(allowed_name_tokens))

Allowed name tokens:  167295

In [ ]:
name_token_index = defaultdict(list)
for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["entity_id", "name_core"],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "name_core": "string"
    }
):

    for entity_id, name in zip(
        chunk["entity_id"],
        chunk["name_core"]):

        if pd.isna(name):
            continue

        for token in set(meaningful_tokens(name)):
            if token in allowed_name_tokens:
                name_token_index[token].append(entity_id)

    del chunk
    gc.collect()

print("Name-token blocks:", len(name_token_index))

Name-token blocks: 167295

In [ ]:
address_token_index = defaultdict(list)
for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["entity_id", "address_norm"],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "address_norm": "string"
    }
):

    for entity_id, address in zip(
        chunk["entity_id"],
        chunk["address_norm"]
    ):

        if pd.isna(address):
            continue

        for token in set(str(address).split()):
            if token in allowed_address_tokens:
                address_token_index[token].append(entity_id)
    del chunk
    gc.collect()

print("Address-token blocks:", len(address_token_index))

Address-token blocks: 404250

In [ ]:
missed_s2_ids = set()
total_true = 0
captured_existing = 0

for row in s1_blocking.itertuples(index=False):
    s1_id = row.entity_id
    country = row.country_norm
    name = row.name_core
    address = row.address_norm

    true_ids = {
        x for x in gt_lookup.get(s1_id, set())
        if x.startswith("S2-")
    }

    if not true_ids:
        continue

    total_true += len(true_ids)
    candidate_set = set()

    # 1. Exact country + name
    if pd.notna(name) and name != "":
        candidate_set.update(
            s2_name_index.get((country, name), [])
        )

        # 2. Name token
        for token in set(meaningful_tokens(name)):
            if token in allowed_name_tokens:
                candidate_set.update(
                    name_token_index.get(token, [])
                )
    # 3. Address token
    if pd.notna(address) and address != "":
        for token in set(str(address).split()):
            if token in allowed_address_tokens:
                candidate_set.update(
                    address_token_index.get(token, [])
                )

    captured = true_ids.intersection(candidate_set)

    captured_existing += len(captured)

    missed_s2_ids.update(
        true_ids - captured
    )
print("Total true S2 matches:", total_true)
print("Captured by existing blocker:", captured_existing)
print("Missed by existing blocker:", len(missed_s2_ids))

Total true S2 matches: 3693619
Captured by existing blocker: 3222405
Missed by existing blocker: 471214

In [ ]:
newly_recovered_by_char3 = 0

for row in s1_blocking.itertuples(index=False):

    s1_id = row.entity_id
    name = row.name_core

    true_ids = {
        x for x in gt_lookup.get(s1_id, set())
        if x.startswith("S2-")
    }

    if not true_ids or pd.isna(name) or name == "":
        continue
    missed_for_s1 = true_ids.intersection(missed_s2_ids)
    if not missed_for_s1:
        continue
    char3_candidates = set()
    for gram in char_ngrams(name, n=3):
        if gram in allowed_char3:
            char3_candidates.update(
                char3_index.get(gram, [])
            )

    newly_recovered_by_char3 += len(
        missed_for_s1.intersection(char3_candidates)
    )
print(
    "New true matches recovered by 3-gram:",
    newly_recovered_by_char3
)
print(
    "Percentage of existing misses recovered:",
    f"{newly_recovered_by_char3 / len(missed_s2_ids):.4%}"
)

New true matches recovered by 3-gram: 19126
Percentage of existing misses recovered: 4.0589%

Transliteration

In [ ]:
import unicodedata
from collections import Counter
def get_script_name(text):
    scripts = set()
    if pd.isna(text):
        return scripts
    for ch in str(text):
        try:
            name = unicodedata.name(ch)
        except ValueError:
            continue

        for script in [
            "DEVANAGARI",
            "BENGALI",
            "GURMUKHI",
            "GUJARATI",
            "ORIYA",
            "TAMIL",
            "TELUGU",
            "KANNADA",
            "MALAYALAM",
            "SINHALA",
            "ARABIC",
            "BENGALI",
            "LATIN"
        ]:
            if script in name:
                scripts.add(script)

    return scripts

script_counts = Counter()

for chunk in pd.read_csv(
    S1_PATH,
    sep="\t",
    usecols=["name_core"],
    chunksize=200_000,
    dtype={"name_core": "string"}
):
    for name in chunk["name_core"].dropna():
        scripts = get_script_name(name)

        # Recording each non Latin script
        for script in scripts:
            if script != "LATIN":
                script_counts[script] += 1

    del chunk
    gc.collect()

print(script_counts)

Counter()

In [ ]:
def detect_script(text):
    if pd.isna(text):
        return "NA"

    scripts = set()

    for ch in str(text):
        try:
            char_name = unicodedata.name(ch)
        except ValueError:
            continue

        if "LATIN" in char_name:
            scripts.add("LATIN")
        elif "DEVANAGARI" in char_name:
            scripts.add("DEVANAGARI")
        elif "GUJARATI" in char_name:
            scripts.add("GUJARATI")
        elif "KANNADA" in char_name:
            scripts.add("KANNADA")
        elif "TELUGU" in char_name:
            scripts.add("TELUGU")
        elif "TAMIL" in char_name:
            scripts.add("TAMIL")
        elif "MALAYALAM" in char_name:
            scripts.add("MALAYALAM")
        elif "BENGALI" in char_name:
            scripts.add("BENGALI")
        elif "GURMUKHI" in char_name:
            scripts.add("GURMUKHI")
        elif "ORIYA" in char_name:
            scripts.add("ORIYA")
        elif "ARABIC" in char_name:
            scripts.add("ARABIC")

    if not scripts:
        return "OTHER"

    return "+".join(sorted(scripts))


print("detect_script restored")

detect_script restored

In [ ]:
script_counts_s1 = Counter()
examples_s1 = {}

for chunk in pd.read_csv(
    RAW_S1_PATH,
    sep="\t",
    usecols=["business_name"],
    chunksize=200_000,
    dtype={"business_name": "string"}
):
    for name in chunk["business_name"].dropna():
        script = detect_script(name)
        script_counts_s1[script] += 1

        if script != "LATIN" and script not in examples_s1:
            examples_s1[script] = name

    del chunk
    gc.collect()

print("S1 script counts:")
for script, count in script_counts_s1.most_common():
    print(f"{script:30s} {count:,}")

print("\nS1 non-Latin examples:")
for script, example in examples_s1.items():
    print(f"{script:30s} -> {example}")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Amazon ML Challenge 2026/01_Dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_s1.tsv'

In [ ]:
script_counts_s2 = Counter()
examples_s2 = {}

for chunk in pd.read_csv(
    RAW_S2_PATH,
    sep="\t",
    usecols=["business_name"],
    chunksize=200_000,
    dtype={"business_name": "string"}
):
    for name in chunk["business_name"].dropna():
        script = detect_script(name)
        script_counts_s2[script] += 1

        if script != "LATIN" and script not in examples_s2:
            examples_s2[script] = name

    del chunk
    gc.collect()

print("S2 script counts:")
for script, count in script_counts_s2.most_common():
    print(f"{script:30s} {count:,}")

print("\nS2 non-Latin examples:")
for script, example in examples_s2.items():
    print(f"{script:30s} -> {example}")

NameError: name 'RAW_S2_PATH' is not defined

In [ ]:
import unicodedata
from collections import Counter
def contains_non_latin(text):
    if pd.isna(text):
        return False
    for ch in str(text):
        try:
            name = unicodedata.name(ch)
        except ValueError:
            continue
        if "LATIN" not in name and any(
            script in name
            for script in [
                "DEVANAGARI",
                "TELUGU",
                "KANNADA",
                "TAMIL",
                "GUJARATI",
                "BENGALI",
                "MALAYALAM",
                "ORIYA",
                "GURMUKHI"
            ]):
            return True
    return False

In [ ]:
import unicodedata

def contains_non_latin(text):
    if pd.isna(text):
        return False

    for ch in str(text):
        try:
            char_name = unicodedata.name(ch)
        except ValueError:
            continue

        if "LATIN" not in char_name and any(
            script in char_name
            for script in [
                "DEVANAGARI",
                "TELUGU",
                "KANNADA",
                "TAMIL",
                "GUJARATI",
                "BENGALI",
                "MALAYALAM",
                "ORIYA",
                "GURMUKHI"
            ]
        ):
            return True

    return False

In [ ]:
missed_non_latin = set()
missed_latin = set()
for chunk in pd.read_csv(
    RAW_S2_PATH,
    sep="\t",
    usecols=["entity_id", "business_name"],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "business_name": "string"
    }
):
    for entity_id, name in zip(
        chunk["entity_id"],
        chunk["business_name"]
    ):
        if entity_id not in missed_s2_ids:
            continue
        if contains_non_latin(name):
            missed_non_latin.add(entity_id)
        else:
            missed_latin.add(entity_id)
    del chunk
    gc.collect()
print("Remaining missed S2 matches:", len(missed_s2_ids))
print("Missed with non-Latin names:", len(missed_non_latin))
print("Missed with Latin names:", len(missed_latin))

print(
    "Non-Latin percentage:",
    round(
        100 * len(missed_non_latin) / len(missed_s2_ids),
        4
    ),
    "%"
)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Amazon ML Challenge 2026/01_Dataset/6ab10eb3b23ba_student_resource/student_resource/dataset/train/train_s2.tsv'

In [ ]:
import subprocess
import sys
result = subprocess.run(
    [sys.executable, "-m", "pip", "index", "versions", "indic-transliteration"],
    capture_output=True,
    text=True
)
print(result.stdout[:2000])

indic-transliteration (2.3.82)
Available versions: 2.3.82, 2.3.81, 2.3.79, 2.3.78, 2.3.76, 2.3.75, 2.3.74, 2.3.73, 2.3.72, 2.3.71, 2.3.70, 2.3.69, 2.3.68, 2.3.67, 2.3.64, 2.3.61, 2.3.60, 2.3.59, 2.3.57, 2.3.56, 2.3.55, 2.3.54, 2.3.53, 2.3.52, 2.3.51, 2.3.50, 2.3.49, 2.3.48, 2.3.47, 2.3.46, 2.3.45, 2.3.44, 2.3.43, 2.3.42, 2.3.41, 2.3.40, 2.3.39, 2.3.38, 2.3.37, 2.3.36, 2.3.35, 2.3.34, 2.3.33, 2.3.32, 2.3.31, 2.3.30, 2.3.29, 2.3.28, 2.3.27, 2.3.26, 2.3.25, 2.3.24, 2.3.22, 2.3.21, 2.3.20, 2.3.19, 2.3.18, 2.3.17, 2.3.13, 2.3.12, 2.3.11, 2.3.10, 2.3.9, 2.3.7, 2.3.5, 2.3.4, 2.3.3, 2.3.2, 2.3.0, 2.2.9, 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.3, 2.2.2, 2.2.1, 2.2.0, 2.1.8, 2.1.7, 2.1.6, 2.1.5, 2.1.4, 2.1.3, 2.1.1, 2.1.0, 2.0.8, 2.0.7, 2.0.6, 2.0.5, 2.0.4, 2.0.3, 2.0.2, 2.0.1, 2.0.0, 1.9.9, 1.9.8, 1.9.7, 1.9.6, 1.9.5, 1.9.4, 1.9.3, 1.9.2, 1.9.1, 1.9.0, 1.8.9, 1.8.8, 1.8.7, 1.8.6, 1.8.5, 1.8.4, 1.8.3, 1.8.2, 1.8.1, 1.8.0, 1.7.9, 1.7.8, 1.7.7, 1.7.6, 1.7.5, 1.7.4, 1.7.3, 1.7.2, 1.7.1, 1.7.0, 1.6.9, 1.6.8, 1.6.7, 1.6.6, 1.6.5, 1.6.4, 1.6.3, 1.6.2, 1.6.1, 1.5.2, 1.5.1, 1.5.0, 1.4.0, 1.3.2, 1.3.1, 1.3.0, 1.2.0, 1.1.0, 1.0.0

In [ ]:
!pip install indic-transliteration==2.3.82 -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.9/162.9 kB 3.4 MB/s eta 0:00:00

In [ ]:
from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate
print("indic-transliteration imported successfully")

indic-transliteration imported successfully

In [ ]:
test_names = [
    "राम मार्केटिंग प्राइवेट लिमिटेड",
    "குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்",
    "શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ",
    "ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್",
    "গোল্ড প্রডিউসার স্টোর্স লিমিটেড",
    "శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్",
    "ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്",
    "ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍",
    "ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ"
]
script_pairs = [
    ("Devanagari", sanscript.DEVANAGARI),
    ("Tamil", sanscript.TAMIL),
    ("Gujarati", sanscript.GUJARATI),
    ("Kannada", sanscript.KANNADA),
    ("Bengali", sanscript.BENGALI),
    ("Telugu", sanscript.TELUGU),
    ("Malayalam", sanscript.MALAYALAM),
    ("Oriya", sanscript.ORIYA),
    ("Gurmukhi", sanscript.GURMUKHI),
]
for name in test_names:
    print("\nOriginal:", name)
    for script_name, source_script in script_pairs:
        try:
            result = transliterate(
                name,
                source_script,
                sanscript.ITRANS)
            print(f"{script_name:12s}: {result}")
        except Exception as e:
            print(f"{script_name:12s}: ERROR -> {e}")

Original: राम मार्केटिंग प्राइवेट लिमिटेड
Devanagari  : rAma mArkeTiMga prAiveTa limiTeDa
Tamil       : राम मार्केटिंग प्राइवेट लिमिटेड
Gujarati    : राम मार्केटिंग प्राइवेट लिमिटेड
Kannada     : राम मार्केटिंग प्राइवेट लिमिटेड
Bengali     : राम मार्केटिंग प्राइवेट लिमिटेड
Telugu      : राम मार्केटिंग प्राइवेट लिमिटेड
Malayalam   : राम मार्केटिंग प्राइवेट लिमिटेड
Oriya       : राम मार्केटिंग प्राइवेट लिमिटेड
Gurmukhi    : राम मार्केटिंग प्राइवेट लिमिटेड

Original: குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Devanagari  : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Tamil       : ghuLobhal bhijhiனs bhiraiveDh limiDhèDh
Gujarati    : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Kannada     : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Bengali     : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Telugu      : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Malayalam   : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Oriya       : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
Gurmukhi    : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்

Original: શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Devanagari  : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Tamil       : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Gujarati    : shakti arbana proDakTsa prAiveTa limiTeDa
Kannada     : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Bengali     : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Telugu      : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Malayalam   : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Oriya       : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
Gurmukhi    : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ

Original: ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Devanagari  : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Tamil       : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Gujarati    : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Kannada     : mADarn kansalTèMTs praiveT limiTèD
Bengali     : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Telugu      : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Malayalam   : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Oriya       : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
Gurmukhi    : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್

Original: গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Devanagari  : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Tamil       : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Gujarati    : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Kannada     : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Bengali     : golDa praDiusAra sTorsa limiTeDa
Telugu      : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Malayalam   : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Oriya       : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
Gurmukhi    : গোল্ড প্রডিউসার স্টোর্স লিমিটেড

Original: శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Devanagari  : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Tamil       : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Gujarati    : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Kannada     : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Bengali     : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Telugu      : shakti iMpèks praiveT limiTèD
Malayalam   : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Oriya       : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
Gurmukhi    : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్

Original: ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Devanagari  : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Tamil       : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Gujarati    : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Kannada     : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Bengali     : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Telugu      : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Malayalam   : shakti iMpèks praivaRR limiRRaD
Oriya       : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
Gurmukhi    : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്

Original: ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Devanagari  : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Tamil       : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Gujarati    : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Kannada     : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Bengali     : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Telugu      : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Malayalam   : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
Oriya       : bhijan Teknolojis prAibheT limiTeD
Gurmukhi    : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍

Original: ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Devanagari  : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Tamil       : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Gujarati    : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Kannada     : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Bengali     : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Telugu      : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Malayalam   : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Oriya       : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
Gurmukhi    : sakAI IsaTa isaTeTa limiTaDa

In [ ]:
import unicodedata
from indic_transliteration.sanscript import transliterate, DEVANAGARI, IAST
test_cases = [
    ("Devanagari", "राम मार्केटिंग प्राइवेट लिमिटेड", DEVANAGARI),
    ("Tamil", "குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்", sanscript.TAMIL),
    ("Gujarati", "શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ", sanscript.GUJARATI),
    ("Kannada", "ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್", sanscript.KANNADA),
    ("Bengali", "গোল্ড প্রডিউসার স্টোর্স লিমিটেড", sanscript.BENGALI),
    ("Telugu", "శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్", sanscript.TELUGU),
    ("Malayalam", "ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്", sanscript.MALAYALAM),
    ("Oriya", "ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍", sanscript.ORIYA),
    ("Gurmukhi", "ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ", sanscript.GURMUKHI),
]

def strip_diacritics(text):
    return "".join(
        ch for ch in unicodedata.normalize("NFKD", text)
        if not unicodedata.combining(ch)
    )
for script_name, text, source_script in test_cases:
    result = transliterate(text, source_script, IAST)
    normalized = strip_diacritics(result).lower()
    print(f"\n{script_name}")
    print("Original :", text)
    print("IAST     :", result)
    print("Normalized:", normalized)

Devanagari
Original : राम मार्केटिंग प्राइवेट लिमिटेड
IAST     : rāma mārkeṭiṃga prāiveṭa limiṭeḍa
Normalized: rama marketimga praiveta limiteda

Tamil
Original : குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
IAST     : ghuḻobhal bhijhiṉas bhiraiveḍh limiḍhèḍh
Normalized: ghulobhal bhijhinas bhiraivedh limidhedh

Gujarati
Original : શક્તિ અર્બન પ્રોડક્ટ્સ પ્રાઇવેટ લિમિટેડ
IAST     : śakti arbana proḍakṭsa prāiveṭa limiṭeḍa
Normalized: sakti arbana prodaktsa praiveta limiteda

Kannada
Original : ಮಾಡರ್ನ್ ಕನ್ಸಲ್ಟೆಂಟ್ಸ್ ಪ್ರೈವೇಟ್ ಲಿಮಿಟೆಡ್
IAST     : māḍarn kansalṭèṃṭs praiveṭ limiṭèḍ
Normalized: madarn kansaltemts praivet limited

Bengali
Original : গোল্ড প্রডিউসার স্টোর্স লিমিটেড
IAST     : golḍa praḍiusāra sṭorsa limiṭeḍa
Normalized: golda pradiusara storsa limiteda

Telugu
Original : శక్తి ఇంపెక్స్ ప్రైవేట్ లిమిటెడ్
IAST     : śakti iṃpèks praiveṭ limiṭèḍ
Normalized: sakti impeks praivet limited

Malayalam
Original : ശക്തി ഇംപെക്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്
IAST     : śakti iṃpèks praivaṟṟ limiṟṟaḍ
Normalized: sakti impeks praivarr limirrad

Oriya
Original : ଭିଜନ୍ ଟେକ୍ନୋଲୋଜିସ୍ ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍
IAST     : bhijan ṭeknolojis prāibheṭ limiṭeḍ
Normalized: bhijan teknolojis praibhet limited

Gurmukhi
Original : ਸਕਾਈ ਈਸਟ ਇਸਟੇਟ ਲਿਮਿਟਡ
IAST     : sakāī īsaṭa isaṭeṭa limiṭaḍa
Normalized: sakai isata isateta limitada

In [ ]:
NAME_STOPWORDS = {
    "inc", "incorporated", "llc", "ltd", "limited",
    "pvt", "private", "company", "co", "corp",
    "corporation", "group", "services", "partners",
    "holdings", "associates", "center", "india",
    "and", "of"
}

def meaningful_tokens(name):
    if pd.isna(name) or not str(name).strip():
        return []

    tokens = str(name).split()

    return [
        token
        for token in tokens
        if token not in NAME_STOPWORDS and len(token) >= 2
    ]

print("meaningful_tokens restored")

meaningful_tokens restored

In [ ]:
missed_s2_ids = set()

total_true = 0
captured_existing = 0

for row in s1_blocking.itertuples(index=False):

    s1_id = row.entity_id
    country = row.country_norm
    name = row.name_core
    address = row.address_norm

    true_ids = {
        x
        for x in gt_lookup.get(s1_id, set())
        if x.startswith("S2-")
    }

    if not true_ids:
        continue

    total_true += len(true_ids)

    candidate_set = set()

    # --------------------------------------------
    # 1. Exact name blocker
    # --------------------------------------------
    if pd.notna(name) and name != "":
        candidate_set.update(
            s2_name_index.get((country, name), [])
        )

        # ----------------------------------------
        # 2. Name-token blocker
        # ----------------------------------------
        for token in set(meaningful_tokens(name)):
            if token in allowed_name_tokens:
                candidate_set.update(
                    name_token_index.get(token, [])
                )

    # --------------------------------------------
    # 3. Address-token blocker
    # --------------------------------------------
    if pd.notna(address) and address != "":
        for token in set(str(address).split()):
            if token in allowed_address_tokens:
                candidate_set.update(
                    address_token_index.get(token, [])
                )

    captured = true_ids.intersection(candidate_set)

    captured_existing += len(captured)

    missed_s2_ids.update(
        true_ids - captured
    )

print("Total true S2 matches:", total_true)
print("Captured by existing blocker:", captured_existing)
print("Missed by existing blocker:", len(missed_s2_ids))

Total true S2 matches: 3693619
Captured by existing blocker: 3222405
Missed by existing blocker: 471214

In [ ]:
missed_non_latin = set()
missed_latin = set()

for chunk in pd.read_csv(
    RAW_S2_PATH,
    sep="\t",
    usecols=["entity_id", "business_name"],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "business_name": "string"
    }
):
    for entity_id, name in zip(
        chunk["entity_id"],
        chunk["business_name"]
    ):
        if entity_id not in missed_s2_ids:
            continue

        if contains_non_latin(name):
            missed_non_latin.add(entity_id)
        else:
            missed_latin.add(entity_id)

    del chunk
    gc.collect()

print("Remaining missed S2 matches:", len(missed_s2_ids))
print("Missed with non-Latin names:", len(missed_non_latin))
print("Missed with Latin names:", len(missed_latin))

print(
    "Non-Latin percentage:",
    round(
        100 * len(missed_non_latin) / len(missed_s2_ids),
        4
    ),
    "%"
)

Remaining missed S2 matches: 471214
Missed with non-Latin names: 122682
Missed with Latin names: 348532
Non-Latin percentage: 26.0353 %

In [ ]:
# Collect only the S2 records that are:
# 1. genuine ground-truth matches
# 2. currently missed by our blocker
# 3. have a non-Latin business name

missed_non_latin_records = []

for chunk in pd.read_csv(
    RAW_S2_PATH,
    sep="\t",
    usecols=["entity_id", "business_name"],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "business_name": "string"
    }
):
    mask = chunk["entity_id"].isin(missed_non_latin)

    selected = chunk.loc[mask]

    if len(selected) > 0:
        missed_non_latin_records.append(selected)

    del chunk
    gc.collect()

missed_non_latin_df = pd.concat(
    missed_non_latin_records,
    ignore_index=True
)

del missed_non_latin_records
gc.collect()

print("Records collected:", len(missed_non_latin_df))
print(missed_non_latin_df.head(10))

Records collected: 122682
      entity_id                                 business_name
0  S2-566688803                       रियल मॉडर्न फूड लिमिटेड
1  S2-879667609             குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்
2   S2-64510343         अल्फा अल टेक्नोलॉजीज प्राइवेट लिमिटेड
3  S2-631299191                 ग्लोबल इन्वेस्टमेंट प्रा. लि.
4  S2-906753214                   फर्स्ट फूड प्राइवेट लिमिटेड
5  S2-923049280              પ્રાઇમ બાલાજી ટ્રેડિંગ પ્રા. લિ.
6  S2-938256871       ডায়নামিক ইন্ডাস্ট্রিজ প্রাইভেট লিমিটেড
7  S2-293759502  పర్‌ఫెక్ట్ యునైటెడ్ మీడియా ప్రైవేట్ లిమిటెడ్
8  S2-625988543      సన్ బెస్ట్ సొల్యూషన్స్ ప్రైవేట్ లిమిటెడ్
9  S2-719478517                                  आनंद वेंचर्स

In [ ]:
missed_pairs_for_translit = []
for row in s1_blocking.itertuples(index=False):
    s1_id = row.entity_id
    true_s2_ids = {
        x for x in gt_lookup.get(s1_id, set())
        if x.startswith("S2-") and x in missed_non_latin
    }
    if not true_s2_ids:
        continue

    for s2_id in true_s2_ids:
        missed_pairs_for_translit.append({
            "s1_id": s1_id,
            "s1_name": row.name_core,
            "s2_id": s2_id
        })

missed_pairs_for_translit = pd.DataFrame(
    missed_pairs_for_translit
)

print("Missed non-Latin true pairs:", len(missed_pairs_for_translit))
print(missed_pairs_for_translit.head())

Missed non-Latin true pairs: 122682
          s1_id          s1_name         s2_id
0  S1-597762257  green logistics  S2-535895394
1  S1-597762257  green logistics  S2-750318376
2  S1-597762257  green logistics  S2-152865025
3  S1-666876590       ss systems  S2-185860935
4  S1-666876590       ss systems  S2-975207252

In [ ]:
missed_pairs_for_translit = missed_pairs_for_translit.merge(
    missed_non_latin_df,
    left_on="s2_id",
    right_on="entity_id",
    how="left"
)
missed_pairs_for_translit = missed_pairs_for_translit.rename(
    columns={"business_name": "s2_name"}
)
print(
    missed_pairs_for_translit[
        ["s1_id", "s1_name", "s2_id", "s2_name"]
    ].head(20).to_string(index=False)
)

In [ ]:
from indic_transliteration.sanscript import transliterate, IAST
from indic_transliteration import sanscript
import unicodedata

In [ ]:
SCRIPT_MAP = {
    "DEVANAGARI": sanscript.DEVANAGARI,
    "TELUGU": sanscript.TELUGU,
    "KANNADA": sanscript.KANNADA,
    "TAMIL": sanscript.TAMIL,
    "GUJARATI": sanscript.GUJARATI,
    "BENGALI": sanscript.BENGALI,
    "MALAYALAM": sanscript.MALAYALAM,
    "ORIYA": sanscript.ORIYA,
    "GURMUKHI": sanscript.GURMUKHI,
}

In [ ]:
def normalize_transliteration(text):
    if pd.isna(text):
        return ""

    text = str(text)
    scripts_found = set()

    for ch in text:
        try:
            char_name = unicodedata.name(ch)
        except ValueError:
            continue

        for script_name in SCRIPT_MAP:
            if script_name in char_name:
                scripts_found.add(script_name)
    if not scripts_found:
        return text.lower()

    result = text
    for script_name in scripts_found:
        source_script = SCRIPT_MAP[script_name]

        try:
            result = transliterate(
                result,
                source_script,
                IAST
            )
        except Exception:
            pass
    result = "".join(
        ch for ch in unicodedata.normalize("NFKD", result)
        if not unicodedata.combining(ch)
    )
    result = result.lower()
    result = " ".join(result.split())

    return result

In [ ]:
sample_translit = missed_pairs_for_translit.head(1000).copy()
sample_translit["s2_translit"] = (
    sample_translit["s2_name"]
    .apply(normalize_transliteration)
)
print(
    sample_translit[
        ["s1_name", "s2_name", "s2_translit"]
    ].head(30).to_string(index=False)
)

              s1_name                                   s2_name                                 s2_translit
      green logistics        ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड         grina laॉjistiksa praiveta limiteda
      green logistics        ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड         grina laॉjistiksa praiveta limiteda
      green logistics        ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड         grina laॉjistiksa praiveta limiteda
           ss systems                     एसएस सिस्टम्स लिमिटेड                    esaesa sistamsa limiteda
           ss systems                     एसएस सिस्टम्स लिमिटेड                    esaesa sistamsa limiteda
 silver constructions                सिल्वर कंस्ट्रक्शंस एलएलपी              silvara kamstraksamsa elaelapi
    shiv technologies                ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ                      siv teknalajis elel‌pi
         surya energy             सूर्य एनर्जी प्राइवेट लिमिटेड              surya enarji praiveta limiteda
     shree industries         શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ           sri indastrijha praiveta limiteda
     shree industries         શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ           sri indastrijha praiveta limiteda
     shree industries         શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ           sri indastrijha praiveta limiteda
  supreme engineering                सुप्रीम इंजीनियरिंग एलएलपी              suprima imjiniyarimga elaelapi
      bharat jai tech                               भारत जय टेक                           bharata jaya teka
  al blue consultancy                अल ब्लू कंसल्टेंसी लिमिटेड                ala blu kamsaltemsi limiteda
           urban tech                                 আরবান টেক                                aravana teka
           urban tech                                 আরবান টেক                                aravana teka
          high estate                        हाई एस्टेट लिमिटेड                         hai esteta limiteda
    creative services    క్రియేటివ్ సర్వీసెస్ ప్రైవేట్ లిమిటెడ్           kriyetiv sarvises praivet limited
    creative services    క్రియేటివ్ సర్వీసెస్ ప్రైవేట్ లిమిటెడ్           kriyetiv sarvises praivet limited
    future healthcare                फ्यूचर हेल्थकेयर प्रा. लि.              phyucara helthakeyara pra. li.
    new international           न्यू इंटरनेशनल प्राइवेट लिमिटेड        nyu imtaranesanala praiveta limiteda
    shakti consulting                   शक्ति कंसल्टिंग लिमिटेड                  sakti kamsaltimga limiteda
           lakshmi it           ଲକ୍ଷ୍ମୀ ଆଇଟି ପ୍ରାଇଭେଟ୍ ଲିମିଟେଡ୍                laksmi aiti praibhet limited
         real trading                           రియల్ ట్రేడింగ్                               riyal tredimg
         real trading                           రియల్ ట్రేడింగ్                               riyal tredimg
 universal management யுனிவர்சல் மேனேஜ்மெண்ட் பிரைவேட் லிமிடெட் yunivarjhal menejmendh bhiraivedh limidhedh
 universal management யுனிவர்சல் மேனேஜ்மெண்ட் பிரைவேட் லிமிடெட் yunivarjhal menejmendh bhiraivedh limidhedh
southern technologies  Southern ടെക്നോളജീസ് പ്രൈവറ്റ് ലിമിറ്റഡ്       southern teknolajis praivarr limirrad
       silver exports       सिल्वर एक्सपोर्ट्स प्राइवेट लिमिटेड        silvara eksaportsa praiveta limiteda
      high industries           हाई इंडस्ट्रीज प्राइवेट लिमिटेड            hai imdastrija praiveta limiteda

In [ ]:
from difflib import SequenceMatcher
def char_similarity(a, b):
    if not a or not b:
        return 0.0
    return SequenceMatcher(None, str(a), str(b)).ratio()

def ngrams(text, n=3):
    text = str(text).replace(" ", "")
    if len(text) < n:
        return {text} if text else set()
    return {
        text[i:i+n]
        for i in range(len(text) - n + 1)
    }

def jaccard_similarity(a, b):
    if not a or not b:
        return 0.0
    a_set = set(a)
    b_set = set(b)
    if not a_set or not b_set:
        return 0.0
    return len(a_set & b_set) / len(a_set | b_set)

In [ ]:
sample_translit = missed_pairs_for_translit.copy()

sample_translit["s2_translit"] = (
    sample_translit["s2_name"]
    .apply(normalize_transliteration)
)
sample_translit["translit_char_sim"] = sample_translit.apply(
    lambda row: char_similarity(
        row["s1_name"],
        row["s2_translit"]
    ),
    axis=1
)
sample_translit["translit_3gram_jaccard"] = sample_translit.apply(
    lambda row: jaccard_similarity(
        ngrams(row["s1_name"], 3),
        ngrams(row["s2_translit"], 3)
    ),
    axis=1
)
sample_translit["translit_token_jaccard"] = sample_translit.apply(
    lambda row: jaccard_similarity(
        str(row["s1_name"]).split(),
        str(row["s2_translit"]).split()
    ),
    axis=1
)
print(
    sample_translit[
        [
            "s1_name",
            "s2_name",
            "s2_translit",
            "translit_char_sim",
            "translit_3gram_jaccard",
            "translit_token_jaccard"
        ]
    ].head(20).to_string(index=False)
)

             s1_name                                s2_name                         s2_translit  translit_char_sim  translit_3gram_jaccard  translit_token_jaccard
     green logistics     ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड grina laॉjistiksa praiveta limiteda           0.400000                0.050000                     0.0
     green logistics     ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड grina laॉjistiksa praiveta limiteda           0.400000                0.050000                     0.0
     green logistics     ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड grina laॉjistiksa praiveta limiteda           0.400000                0.050000                     0.0
          ss systems                  एसएस सिस्टम्स लिमिटेड            esaesa sistamsa limiteda           0.470588                0.000000                     0.0
          ss systems                  एसएस सिस्टम्स लिमिटेड            esaesa sistamsa limiteda           0.470588                0.000000                     0.0
silver constructions             सिल्वर कंस्ट्रक्शंस एलएलपी      silvara kamstraksamsa elaelapi           0.400000                0.085714                     0.0
   shiv technologies             ಶಿವ್ ಟೆಕ್ನಾಲಜೀಸ್ ಎಲ್ಎಲ್‌ಪಿ              siv teknalajis elel‌pi           0.512821                0.066667                     0.0
        surya energy          सूर्य एनर्जी प्राइवेट लिमिटेड      surya enarji praiveta limiteda           0.428571                0.172414                     0.2
    shree industries      શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ   sri indastrijha praiveta limiteda           0.448980                0.078947                     0.0
    shree industries      શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ   sri indastrijha praiveta limiteda           0.448980                0.078947                     0.0
    shree industries      શ્રી ઇન્ડસ્ટ્રીઝ પ્રાઇવેટ લિમિટેડ   sri indastrijha praiveta limiteda           0.448980                0.078947                     0.0
 supreme engineering             सुप्रीम इंजीनियरिंग एलएलपी      suprima imjiniyarimga elaelapi           0.326531                0.054054                     0.0
     bharat jai tech                            भारत जय टेक                   bharata jaya teka           0.750000                0.200000                     0.0
 al blue consultancy             अल ब्लू कंसल्टेंसी लिमिटेड        ala blu kamsaltemsi limiteda           0.468085                0.027027                     0.0
          urban tech                              আরবান টেক                        aravana teka           0.545455                0.000000                     0.0
          urban tech                              আরবান টেক                        aravana teka           0.545455                0.000000                     0.0
         high estate                     हाई एस्टेट लिमिटेड                 hai esteta limiteda           0.600000                0.045455                     0.0
   creative services క్రియేటివ్ సర్వీసెస్ ప్రైవేట్ లిమిటెడ్   kriyetiv sarvises praivet limited           0.480000                0.076923                     0.0
   creative services క్రియేటివ్ సర్వీసెస్ ప్రైవేట్ లిమిటెడ్   kriyetiv sarvises praivet limited           0.480000                0.076923                     0.0
   future healthcare             फ्यूचर हेल्थकेयर प्रा. लि.      phyucara helthakeyara pra. li.           0.425532                0.055556                     0.0

In [ ]:
for col in [
    "translit_char_sim",
    "translit_3gram_jaccard",
    "translit_token_jaccard"
]:
    print("\n", "=" * 60)
    print(col)

    print(
        sample_translit[col].describe(
            percentiles=[0.25, 0.5, 0.75, 0.9, 0.95]
        ))
    for threshold in [0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]:
        recovered = (
            sample_translit[col] >= threshold
        ).sum()
        print(
            f">= {threshold:.1f}: "
            f"{recovered:,} "
            f"({recovered / len(sample_translit) * 100:.2f}%)"
        )

In [ ]:
post_3gram_non_latin = missed_non_latin.intersection(missed_s2_ids)
print("Non-Latin baseline misses:", len(missed_non_latin))
print("Remaining non-Latin misses after 3-gram:", len(post_3gram_non_latin))

In [ ]:
print(len(missed_non_latin))
print(len(missed_pairs_for_translit))
print(normalize_transliteration("ग्रीन लॉजिस्टिक्स प्राइवेट लिमिटेड"))

In [ ]:
import re
from collections import defaultdict
def translit_block_key(text, prefix_len=4):
    text = normalize_transliteration(text)
    text = re.sub(r"[^a-z0-9]", "", text)

    if not text:
        return ""

    return text[:prefix_len]

In [ ]:
missed_non_latin_df["s2_translit"] = (
    missed_non_latin_df["business_name"]
    .apply(normalize_transliteration)
)

for prefix_len in [3, 4, 5, 6]:
    missed_non_latin_df[f"block_{prefix_len}"] = (
        missed_non_latin_df["s2_translit"]
        .apply(lambda x: translit_block_key(x, prefix_len)))

print(missed_non_latin_df[
        ["business_name", "s2_translit", "block_3", "block_4", "block_5", "block_6"]
    ].head(20).to_string(index=False))

In [ ]:
s1_translit_blocking = s1_blocking[
    ["entity_id", "country_norm", "name_core"]
].copy()
s1_translit_blocking["name_block_3"] = (
    s1_translit_blocking["name_core"]
    .fillna("")
    .apply(lambda x: translit_block_key(x, 3))
)
s1_translit_blocking["name_block_4"] = (
    s1_translit_blocking["name_core"]
    .fillna("")
    .apply(lambda x: translit_block_key(x, 4))
)
s1_translit_blocking["name_block_5"] = (
    s1_translit_blocking["name_core"]
    .fillna("")
    .apply(lambda x: translit_block_key(x, 5))
)
s1_translit_blocking["name_block_6"] = (
    s1_translit_blocking["name_core"]
    .fillna("")
    .apply(lambda x: translit_block_key(x, 6))
)

In [133]:
# for n in [3, 4, 5, 6]:
#     counts = s1_translit_blocking[
#         s1_translit_blocking[f"name_block_{n}"] != ""
#     ][f"name_block_{n}"].value_counts()
#     print(f"\nPrefix length {n}")
#     print("Unique blocks:", len(counts))
#     print("Mean block size:", round(counts.mean(), 2))
#     print("Median block size:", counts.median())
#     print("95th percentile:", counts.quantile(0.95))
#     print("Maximum block size:", counts.max())

Prefix length 3
Unique blocks: 22369
Mean block size: 98.66
Median block size: 6.0
95th percentile: 223.59999999999854
Maximum block size: 18717

Prefix length 4
Unique blocks: 111200
Mean block size: 19.85
Median block size: 1.0
95th percentile: 39.0
Maximum block size: 18556

KeyError: 'name_block_5'


checking whether S1 and S2 share the same transliteration prefix

In [134]:
# s1_block_lookup = {}
# for row in s1_translit_blocking.itertuples(index=False):
#     s1_block_lookup[row.entity_id] = {
#         3: row.name_block_3,
#         4: row.name_block_4,
#         5: row.name_block_5,
#         6: row.name_block_6,
#     }

# for prefix_len in [3, 4, 5, 6]:

#     captured = 0
#     total = len(missed_pairs_for_translit)
#     for row in missed_pairs_for_translit.itertuples(index=False):
#         s1_key = s1_block_lookup.get(row.s1_id, {}).get(prefix_len, "")
#         s2_key = translit_block_key(
#             normalize_transliteration(row.s2_name),
#             prefix_len
#         )
#         if s1_key and s1_key == s2_key:
#             captured += 1
#     recall = captured / total if total else 0
#     print(
#         f"Prefix {prefix_len}: "
#         f"{captured:,} / {total:,} "
#         f"= {recall * 100:.4f}% recall"
#     )

AttributeError: 'Pandas' object has no attribute 'name_block_5'

In [135]:
from indic_transliteration.sanscript import transliterate
from indic_transliteration import sanscript
import unicodedata
import re

SCRIPT_MAP = {
    "DEVANAGARI": sanscript.DEVANAGARI,
    "BENGALI": sanscript.BENGALI,
    "GURMUKHI": sanscript.GURMUKHI,
    "GUJARATI": sanscript.GUJARATI,
    "ORIYA": sanscript.ORIYA,
    "TAMIL": sanscript.TAMIL,
    "TELUGU": sanscript.TELUGU,
    "KANNADA": sanscript.KANNADA,
    "MALAYALAM": sanscript.MALAYALAM,
}

In [136]:
def detect_script(text):
    if pd.isna(text):
        return None

    for ch in str(text):
        try:
            name = unicodedata.name(ch)
        except ValueError:
            continue

        for script_name in SCRIPT_MAP:
            if script_name in name:
                return script_name

    return None

In [137]:
def transliterate_text(text):
    if pd.isna(text):
        return ""

    text = str(text).strip()

    if not text:
        return ""

    script = detect_script(text)

    if script is None:
        return text.lower()

    try:
        result = transliterate(
            text,
            SCRIPT_MAP[script],
            sanscript.ITRANS
        )
    except Exception:
        return text.lower()

    return result

In [138]:
def normalize_transliterated(text):
    if pd.isna(text):
        return ""

    text = str(text).lower()

    text = unicodedata.normalize("NFKD", text)

    text = "".join(
        ch for ch in text
        if not unicodedata.combining(ch)
    )

    text = re.sub(r"[^a-z0-9]+", " ", text)

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [139]:
def normalize_transliteration(text):
    transliterated = transliterate_text(text)
    return normalize_transliterated(transliterated)

In [140]:
def char_ngrams_set(text, n=3):
    if pd.isna(text):
        return set()

    text = str(text).replace(" ", "")

    if len(text) < n:
        return {text} if text else set()

    return {
        text[i:i+n]
        for i in range(len(text) - n + 1)
    }


missed_3gram_stats = []

for row in missed_pairs.itertuples(index=False):

    a = char_ngrams_set(row.name_core_s1, 3)
    b = char_ngrams_set(row.name_core_s2, 3)

    shared = len(a & b)

    missed_3gram_stats.append({
        "shared_3grams": shared,
        "s1_grams": len(a),
        "s2_grams": len(b)
    })

missed_3gram_stats = pd.DataFrame(missed_3gram_stats)

print(
    missed_3gram_stats["shared_3grams"].describe()
)

print("\nShared 3-gram distribution:")
print(
    missed_3gram_stats["shared_3grams"]
    .value_counts()
    .sort_index()
)

count    100.000000
mean       7.600000
std        7.019453
min        0.000000
25%        0.000000
50%        6.500000
75%       13.000000
max       29.000000
Name: shared_3grams, dtype: float64

Shared 3-gram distribution:
shared_3grams
0     28
1      1
2      6
3      2
4      3
5      5
6      5
7      3
8      3
9      5
10     1
11     5
12     6
13     5
14     9
15     3
16     2
17     1
18     1
19     1
21     1
22     1
25     1
28     1
29     1
Name: count, dtype: int64

In [141]:
for threshold in [1, 2, 3, 4, 5]:
    recovered = (
        missed_3gram_stats["shared_3grams"] >= threshold
    ).sum()

    print(
        f"At least {threshold} shared 3-grams: "
        f"{recovered}/100 "
        f"({recovered}%)"
    )

At least 1 shared 3-grams: 72/100 (72%)
At least 2 shared 3-grams: 71/100 (71%)
At least 3 shared 3-grams: 65/100 (65%)
At least 4 shared 3-grams: 63/100 (63%)
At least 5 shared 3-grams: 60/100 (60%)

In [142]:
from collections import Counter, defaultdict
char3_freq_relaxed = Counter()

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["name_core"],
    chunksize=200_000,
    dtype={"name_core": "string"}
):
    for name in chunk["name_core"]:
        if pd.isna(name):
            continue

        grams = set(char_ngrams_set(name, 3))
        char3_freq_relaxed.update(grams)

    del chunk
    gc.collect()

print("Unique 3-grams:", len(char3_freq_relaxed))

for max_freq in [1000, 2000, 5000]:
    allowed = sum(
        1 for freq in char3_freq_relaxed.values()
        if 2 <= freq <= max_freq
    )

    print(
        f"max_freq={max_freq:,} → "
        f"{allowed:,} allowed grams"
    )

Unique 3-grams: 90023
max_freq=1,000 → 68,162 allowed grams
max_freq=2,000 → 69,944 allowed grams
max_freq=5,000 → 71,758 allowed grams

In [143]:
allowed_char3_relaxed = {
    gram
    for gram, freq in char3_freq_relaxed.items()
    if 2 <= freq <= 1000
}

print(
    "Allowed relaxed 3-grams:",
    len(allowed_char3_relaxed)
)

Allowed relaxed 3-grams: 68162

actual incremental recall

In [144]:
char3_relaxed_index = defaultdict(list)
for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["entity_id", "name_core"],
    chunksize=200_000,
    dtype={
        "entity_id": "string",
        "name_core": "string"
    }
):
    for entity_id, name in zip(
        chunk["entity_id"],
        chunk["name_core"]
    ):

        if pd.isna(name):
            continue

        for gram in char_ngrams_set(name, 3):

            if gram in allowed_char3_relaxed:
                char3_relaxed_index[gram].append(
                    entity_id
                )
    del chunk
    gc.collect()

print(
    "Relaxed 3-gram index built:",
    len(char3_relaxed_index)
)

Relaxed 3-gram index built: 68162

In [145]:
def calculate_relaxed_char3_recovery(
    s1_df,
    gt_lookup,
    char3_index,
    prefix,
    min_shared_grams=2
):
    total_missed = 0
    recovered = 0

    for row in s1_df.itertuples(index=False):

        s1_id = row.entity_id
        name = row.name_core
        true_ids = {
            x
            for x in gt_lookup.get(s1_id, set())
            if x.startswith(prefix)
        }
        if not true_ids:
            continue
        if pd.isna(name):
            continue
        gram_counts = Counter()
        for gram in char_ngrams_set(name, 3):
            if gram not in allowed_char3_relaxed:
                continue
            for s2_id in char3_index.get(gram, []):
                gram_counts[s2_id] += 1
        candidates = {
            s2_id
            for s2_id, count in gram_counts.items()
            if count >= min_shared_grams
        }
        recovered += len(
            true_ids.intersection(candidates)
        )
    return recovered

In [146]:
# Measure incremental recovery from the relaxed 3-gram blocker against the previously missed S2 matches.

relaxed_recovered = 0
relaxed_total_missed = 0

# Track recovered S2 IDs so we can inspect them later
relaxed_recovered_pairs = []

for row in s1_blocking.itertuples(index=False):

    s1_id = row.entity_id
    name = row.name_core

    true_ids = {
        x
        for x in gt_lookup.get(s1_id, set())
        if x.startswith("S2-")
    }

    if not true_ids:
        continue

    # We only care about the TRUE matches that were already missed by our baseline blocker
    # The baseline captured 3,222,405 of 3,693,619.

    # We'll identify baseline candidates using the
    # original three-way blockers below.

    candidate_counts = Counter()

    if pd.notna(name) and str(name).strip():

        for gram in char_ngrams_set(name, 3):

            if gram in allowed_char3_relaxed:

                for s2_id in char3_relaxed_index.get(
                    gram, []
                ):
                    candidate_counts[s2_id] += 1

    relaxed_candidates = {
        s2_id
        for s2_id, count in candidate_counts.items()
        if count >= 2
    }
    recovered_here = true_ids.intersection(
        relaxed_candidates
    )

    if recovered_here:

        relaxed_recovered += len(recovered_here)

        for s2_id in recovered_here:
            relaxed_recovered_pairs.append({
                "s1_id": s1_id,
                "s2_id": s2_id
            })

print(
    "Relaxed 3-gram recovered:",
    relaxed_recovered
)

print(
    "Potential overall captured:",
    3_222_405 + relaxed_recovered
)

print(
    "Potential overall recall:",
    (3_222_405 + relaxed_recovered)
    / 3_693_619
)

Relaxed 3-gram recovered: 268033
Potential overall captured: 3490438
Potential overall recall: 0.9449913485933443

In [147]:
relaxed_recovered_df = pd.DataFrame(relaxed_recovered_pairs)
relaxed_pair_set = set(
    zip(
        relaxed_recovered_df["s1_id"],
        relaxed_recovered_df["s2_id"]
    )
)
print("Relaxed recovered pairs:", len(relaxed_pair_set))

Relaxed recovered pairs: 268033

In [148]:
recovered_s2_ids = set(
    relaxed_recovered_df["s2_id"]
)
recovered_s2_lookup = {}

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "country_norm",
        "name_core",
        "address_norm"
    ],
    chunksize=200_000,
    dtype="string"
):

    mask = chunk["entity_id"].isin(recovered_s2_ids)

    selected = chunk.loc[
        mask,
        ["entity_id", "country_norm", "name_core", "address_norm"]
    ]

    for row in selected.itertuples(index=False):
        recovered_s2_lookup[row.entity_id] = {
            "country_norm": row.country_norm,
            "name_core": row.name_core,
            "address_norm": row.address_norm
        }

    del chunk
    gc.collect()

print(
    "Recovered S2 records found:",
    len(recovered_s2_lookup)
)

Recovered S2 records found: 268033

In [149]:
print("allowed_name_tokens:", "allowed_name_tokens" in globals())
print("allowed_address_tokens:", "allowed_address_tokens" in globals())

allowed_name_tokens: True
allowed_address_tokens: True

In [150]:
# Building a reverse lookup:
# S2 ID - (country, name_core, address_norm)

recovered_original_evidence = {}

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "country_norm",
        "name_core",
        "address_norm"
    ],
    chunksize=200_000,
    dtype="string"
):

    mask = chunk["entity_id"].isin(recovered_s2_ids)

    selected = chunk.loc[
        mask,
        [
            "entity_id",
            "country_norm",
            "name_core",
            "address_norm"
        ]
    ]

    for row in selected.itertuples(index=False):
        recovered_original_evidence[row.entity_id] = {
            "country": row.country_norm,
            "name": row.name_core,
            "address": row.address_norm
        }

    del chunk
    gc.collect()

print(
    "Records available:",
    len(recovered_original_evidence)
)

Records available: 268033

Measuring how many relaxed-3gram recovered true pairs were ALREADY captured by the original blockers.

In [151]:
from collections import defaultdict

relaxed_by_s1 = defaultdict(set)

for s1_id, s2_id in relaxed_pair_set:
    relaxed_by_s1[s1_id].add(s2_id)

print("S1 entities with relaxed recoveries:", len(relaxed_by_s1))
print(
    "Total relaxed pairs:",
    sum(len(v) for v in relaxed_by_s1.values())
)

S1 entities with relaxed recoveries: 155120
Total relaxed pairs: 268033

In [152]:
already_captured = 0
genuinely_new = 0

new_recovered_pairs = []

for row in s1_blocking.itertuples(index=False):

    s1_id = row.entity_id

    if s1_id not in relaxed_by_s1:
        continue

    country = row.country_norm
    name = row.name_core
    address = row.address_norm

    # Precompute S1 tokens once
    name_tokens = set(
        meaningful_tokens(name)
    ) if pd.notna(name) else set()

    address_tokens = (
        set(str(address).split())
        if pd.notna(address)
        else set()
    )

    for s2_id in relaxed_by_s1[s1_id]:

        s2 = recovered_original_evidence.get(s2_id)

        if s2 is None:
            continue

        captured_by_original = False

        # 1. Exact country + name
        if (
            pd.notna(name)
            and pd.notna(s2["name"])
            and country == s2["country"]
            and name == s2["name"]
        ):
            captured_by_original = True

        # 2. Name-token blocker
        if not captured_by_original:

            s2_name_tokens = set(
                meaningful_tokens(s2["name"])
            ) if pd.notna(s2["name"]) else set()

            if (
                name_tokens
                & s2_name_tokens
                & allowed_name_tokens
            ):
                captured_by_original = True

        # 3. Address-token blocker
        if not captured_by_original:

            s2_address_tokens = (
                set(str(s2["address"]).split())
                if pd.notna(s2["address"])
                else set()
            )

            if (
                address_tokens
                & s2_address_tokens
                & allowed_address_tokens
            ):
                captured_by_original = True

        if captured_by_original:
            already_captured += 1

        else:
            genuinely_new += 1

            new_recovered_pairs.append({
                "s1_id": s1_id,
                "s2_id": s2_id
            })


print("Already captured:", already_captured)
print("Genuinely new:", genuinely_new)

overall_captured = 3_222_405 + genuinely_new

print(
    "\nOverall captured:",
    overall_captured
)

print(
    "Overall S2 recall:",
    overall_captured / 3_693_619
)

Already captured: 258623
Genuinely new: 9410

Overall captured: 3231815
Overall S2 recall: 0.8749724863338639

In [153]:
print("Original allowed 3-grams:", len(allowed_char3))

Original allowed 3-grams: 65473

In [155]:
def address_tokens(text):
    if pd.isna(text) or not str(text).strip():
        return set()
    return set(str(text).split())


address_recovery_stats = []

for row in missed_pairs.itertuples(index=False):

    s1_addr = address_tokens(row.address_norm_s1)
    s2_addr = address_tokens(row.address_norm_s2)

    shared = s1_addr & s2_addr

    meaningful_shared = (
        shared & allowed_address_tokens
    )

    address_recovery_stats.append({
        "shared_address_tokens": len(shared),
        "shared_allowed_address_tokens": len(
            meaningful_shared
        ),
        "s1_address_tokens": len(s1_addr),
        "s2_address_tokens": len(s2_addr)
    })

address_recovery_stats = pd.DataFrame(
    address_recovery_stats
)

print(
    address_recovery_stats[
        "shared_address_tokens"
    ].describe()
)

print("\nShared address-token distribution:")
print(
    address_recovery_stats[
        "shared_address_tokens"
    ].value_counts().sort_index()
)

count    100.000000
mean       5.370000
std        3.007247
min        0.000000
25%        4.000000
50%        5.000000
75%        7.000000
max       16.000000
Name: shared_address_tokens, dtype: float64

Shared address-token distribution:
shared_address_tokens
0     11
2      1
3      4
4     19
5     24
6     15
7      9
8      3
9      5
10     3
11     3
13     2
16     1
Name: count, dtype: int64

In [156]:
print(type(missed_s2_ids))
print("Number of missed S2 IDs:", len(missed_s2_ids))

print("Sample:", list(missed_s2_ids)[:5])

<class 'set'>
Number of missed S2 IDs: 471214
Sample: ['S2-118707577', 'S2-882912476', 'S2-475085348', 'S2-946764073', 'S2-637569704']

In [157]:
missed_address_index = defaultdict(list)

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "country_norm",
        "address_norm"
    ],
    chunksize=200_000,
    dtype="string"
):

    # Keep only S2 records that are involved
    # in the remaining missed population.
    chunk = chunk[
        chunk["entity_id"].isin(missed_s2_ids)
    ]

    for row in chunk.itertuples(index=False):

        if pd.isna(row.address_norm):
            continue

        tokens = set(
            str(row.address_norm).split()
        )

        # Only keep tokens useful for blocking
        tokens = tokens.intersection(
            allowed_address_tokens
        )

        for token in tokens:
            missed_address_index[token].append(
                row.entity_id
            )

    del chunk
    gc.collect()

print(
    "Address tokens indexed:",
    len(missed_address_index)
)

Address tokens indexed: 38064

In [158]:
missed_s2_country = {}

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "country_norm"
    ],
    chunksize=200_000,
    dtype="string"
):

    chunk = chunk[
        chunk["entity_id"].isin(missed_s2_ids)
    ]

    for row in chunk.itertuples(index=False):
        missed_s2_country[row.entity_id] = row.country_norm

    del chunk
    gc.collect()

print(
    "Missed S2 country records:",
    len(missed_s2_country)
)

Missed S2 country records: 471214

In [159]:
from collections import defaultdict
import pandas as pd
import gc

# ---------------------------------------------------------
# Build address-token candidates for the remaining misses
# ---------------------------------------------------------

address_recovered_pairs = set()

for row in s1_blocking.itertuples(index=False):

    s1_id = row.entity_id
    country = row.country_norm
    address = row.address_norm

    if pd.isna(address):
        continue

    s1_tokens = set(str(address).split())
    s1_tokens = s1_tokens.intersection(allowed_address_tokens)

    if len(s1_tokens) < 2:
        continue

    # Count how many address tokens each missed S2 shares
    candidate_counts = defaultdict(int)

    for token in s1_tokens:
        for s2_id in missed_address_index.get(token, []):
            candidate_counts[s2_id] += 1

    # Keep candidates sharing >= 2 address tokens
    for s2_id, count in candidate_counts.items():

        if count >= 2:

            # Country must agree
            if missed_s2_country.get(s2_id) == country:
                address_recovered_pairs.add(
                    (s1_id, s2_id)
                )

print(
    "Address candidate pairs:",
    len(address_recovered_pairs)
)

Address candidate pairs: 3863

In [160]:
# ---------------------------------------------------------
# Measure true matches recovered
# ---------------------------------------------------------

address_true_recovered = 0

for s1_id, s2_id in address_recovered_pairs:

    true_ids = gt_lookup.get(s1_id, set())

    if s2_id in true_ids:
        address_true_recovered += 1

print(
    "True matches recovered:",
    address_true_recovered
)

print(
    "Current baseline:",
    3_241_531
)

print(
    "New total:",
    3_241_531 + address_true_recovered
)

print(
    "New recall:",
    (3_241_531 + address_true_recovered) / 3_693_619
)

True matches recovered: 0
Current baseline: 3241531
New total: 3241531
New recall: 0.8776029687956446

In [162]:
import re
import pandas as pd
import gc

def has_non_latin(text):
    if pd.isna(text):
        return False

    text = str(text)

    # Remove whitespace, punctuation and numbers.
    letters = re.sub(r'[\W\d_]+', '', text, flags=re.UNICODE)

    if not letters:
        return False

    # Latin characters only?
    return any(
        not ('a' <= c.lower() <= 'z')
        for c in letters
    )


non_latin_missed = []

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=[
        "entity_id",
        "business_name",
        "name_core"
    ],
    chunksize=200_000,
    dtype="string"
):

    chunk = chunk[
        chunk["entity_id"].isin(missed_s2_ids)
    ]

    for row in chunk.itertuples(index=False):

        if has_non_latin(row.business_name):
            non_latin_missed.append(
                (
                    row.entity_id,
                    row.business_name,
                    row.name_core
                )
            )

    del chunk
    gc.collect()

print(
    "Non-Latin missed S2 records:",
    len(non_latin_missed)
)

print(
    non_latin_missed[:10]
)

Non-Latin missed S2 records: 164111
[('S2-566688803', 'रियल मॉडर्न फूड लिमिटेड', 'र यल म डर न फ ड ल म ट ड'), ('S2-879667609', 'குளோபல் பிசினஸ் பிரைவேட் லிமிடெட்', 'க ள பல ப ச னஸ ப ர வ ட ல ம ட ட'), ('S2-64510343', 'अल्फा अल टेक्नोलॉजीज प्राइवेट लिमिटेड', 'अल फ अल ट क न ल ज ज प र इव ट ल म ट ड'), ('S2-631299191', 'ग्लोबल इन्वेस्टमेंट प्रा. लि.', 'ग ल बल इन व स टम ट प र ल'), ('S2-906753214', 'फर्स्ट फूड प्राइवेट लिमिटेड', 'फर स ट फ ड प र इव ट ल म ट ड'), ('S2-923049280', 'પ્રાઇમ બાલાજી ટ્રેડિંગ પ્રા. લિ.', 'પ ર ઇમ બ લ જ ટ ર ડ ગ પ ર લ'), ('S2-472544795', 'Rich & Dávidson Inc', 'rich dávidson'), ('S2-533197229', 'Continental Éndocrinology LLC', 'continental éndocrinology'), ('S2-582984116', 'Wildlife Sóciety', 'wildlife sóciety'), ('S2-938256871', 'ডায়নামিক ইন্ডাস্ট্রিজ প্রাইভেট লিমিটেড', 'ড য ন ম ক ইন ড স ট র জ প র ইভ ট ল ম ট ড')]

In [163]:
import unicodedata
from collections import Counter

def detect_script(text):
    if pd.isna(text):
        return "MISSING"

    scripts = set()

    for char in str(text):
        if not char.isalpha():
            continue

        name = unicodedata.name(char, "")

        if "DEVANAGARI" in name:
            scripts.add("DEVANAGARI")
        elif "BENGALI" in name:
            scripts.add("BENGALI")
        elif "GURMUKHI" in name:
            scripts.add("GURMUKHI")
        elif "GUJARATI" in name:
            scripts.add("GUJARATI")
        elif "ORIYA" in name or "ODIA" in name:
            scripts.add("ODIA")
        elif "TAMIL" in name:
            scripts.add("TAMIL")
        elif "TELUGU" in name:
            scripts.add("TELUGU")
        elif "KANNADA" in name:
            scripts.add("KANNADA")
        elif "MALAYALAM" in name:
            scripts.add("MALAYALAM")
        elif "LATIN" in name:
            scripts.add("LATIN")
        else:
            scripts.add("OTHER")

    if not scripts:
        return "OTHER"

    return "+".join(sorted(scripts))


script_counts = Counter()

for entity_id, business_name, name_core in non_latin_missed:
    script = detect_script(business_name)
    script_counts[script] += 1

print("Script distribution:")
for script, count in script_counts.most_common():
    print(f"{script:30s} {count:,}")

Script distribution:
DEVANAGARI                     73,326
LATIN                          41,429
TELUGU                         10,270
KANNADA                        9,645
TAMIL                          7,389
GUJARATI                       6,599
BENGALI                        6,498
DEVANAGARI+LATIN               2,727
MALAYALAM                      2,210
GURMUKHI                       1,458
ODIA                           1,047
LATIN+TELUGU                   345
KANNADA+LATIN                  304
BENGALI+LATIN                  264
LATIN+TAMIL                    237
GUJARATI+LATIN                 200
LATIN+MALAYALAM                67
GURMUKHI+LATIN                 67
LATIN+ODIA                     29

In [164]:
indic_scripts = {
    "DEVANAGARI",
    "TELUGU",
    "KANNADA",
    "TAMIL",
    "GUJARATI",
    "BENGALI",
    "MALAYALAM",
    "GURMUKHI",
    "ODIA"
}

indic_missed_ids = set()

for entity_id, business_name, name_core in non_latin_missed:

    script = detect_script(business_name)

    # Keep records containing at least one Indic script
    if any(s in script for s in indic_scripts):
        indic_missed_ids.add(entity_id)

print("Indic-script missed S2 records:", len(indic_missed_ids))

Indic-script missed S2 records: 122682

In [165]:
cross_script_true_pairs = []

for s1_id, true_ids in gt_lookup.items():

    # Only examine true S2 matches
    for s2_id in true_ids:

        if s2_id not in missed_s2_ids:
            continue

        if s2_id not in indic_missed_ids:
            continue

        cross_script_true_pairs.append(
            (s1_id, s2_id)
        )

print(
    "Remaining Indic-script true pairs:",
    len(cross_script_true_pairs)
)

print(
    "Percentage of remaining misses:",
    len(cross_script_true_pairs) / 452088 * 100
)

Remaining Indic-script true pairs: 122682
Percentage of remaining misses: 27.136752136752136

In [178]:
# ---------------------------------------------------------
# Build lookup of the actual remaining cross-script pairs
# ---------------------------------------------------------

cross_script_s1_ids = {
    s1_id for s1_id, s2_id in cross_script_true_pairs
}

cross_script_s2_ids = {
    s2_id for s1_id, s2_id in cross_script_true_pairs
}

print("Cross-script S1 entities:", len(cross_script_s1_ids))
print("Cross-script S2 records:", len(cross_script_s2_ids))

Cross-script S1 entities: 96119
Cross-script S2 records: 122682

In [167]:
cross_s2_names = {}

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["entity_id", "business_name"],
    chunksize=200_000,
    dtype="string"
):

    chunk = chunk[
        chunk["entity_id"].isin(cross_script_s2_ids)
    ]

    for row in chunk.itertuples(index=False):
        cross_s2_names[row.entity_id] = row.business_name

    del chunk
    gc.collect()

print(
    "S2 names loaded:",
    len(cross_s2_names)
)

S2 names loaded: 122682

In [168]:
s1_name_lookup = dict(
    zip(
        s1_blocking["entity_id"],
        s1_blocking["name_core"]
    )
)

print(
    "S1 names available:",
    len(s1_name_lookup)
)

S1 names available: 2206821

In [169]:
from indic_transliteration import sanscript
from indic_transliteration.sanscript import transliterate


SCRIPT_MAP = {
    "DEVANAGARI": sanscript.DEVANAGARI,
    "BENGALI": sanscript.BENGALI,
    "GURMUKHI": sanscript.GURMUKHI,
    "GUJARATI": sanscript.GUJARATI,
    "ODIA": sanscript.ORIYA,
    "TAMIL": sanscript.TAMIL,
    "TELUGU": sanscript.TELUGU,
    "KANNADA": sanscript.KANNADA,
    "MALAYALAM": sanscript.MALAYALAM,
}


def transliterate_name(text):

    if pd.isna(text):
        return ""

    text = str(text).strip()

    if not text:
        return ""

    script = detect_script(text)

    # Pure or mixed Latin text
    if script == "LATIN":
        return text.lower()

    # Handle mixed-script names
    result = text

    # Transliterate each supported Indic script separately.
    for script_name, scheme in SCRIPT_MAP.items():

        if script_name in script:

            try:
                result = transliterate(
                    result,
                    scheme,
                    sanscript.IAST
                )
            except Exception:
                pass

    return result.lower()

In [170]:
shared_translit_3grams = []

for s1_id, s2_id in cross_script_true_pairs:

    s1_name = s1_name_lookup.get(s1_id)
    s2_name = cross_s2_names.get(s2_id)

    if pd.isna(s1_name) or pd.isna(s2_name):
        continue

    s1_translit = transliterate_name(s1_name)
    s2_translit = transliterate_name(s2_name)

    g1 = char_ngrams(s1_translit, 3)
    g2 = char_ngrams(s2_translit, 3)

    shared = len(g1 & g2)

    shared_translit_3grams.append(shared)

shared_series = pd.Series(shared_translit_3grams)

print("Pairs analysed:", len(shared_series))
print("\nDistribution:")
print(shared_series.describe())

print("\nRecovery at each threshold:")

for threshold in [1, 2, 3, 4, 5, 6, 8, 10]:
    recovered = (shared_series >= threshold).sum()
    recall = recovered / len(shared_series)

    print(
        f">= {threshold:2d} shared grams: "
        f"{recovered:6,} "
        f"({recall:.2%})"
    )

Pairs analysed: 122682

Distribution:
count    122682.000000
mean          1.463295
std           2.039704
min           0.000000
25%           0.000000
50%           1.000000
75%           2.000000
max          22.000000
dtype: float64

Recovery at each threshold:
>=  1 shared grams: 69,981 (57.04%)
>=  2 shared grams: 41,258 (33.63%)
>=  3 shared grams: 26,864 (21.90%)
>=  4 shared grams: 15,672 (12.77%)
>=  5 shared grams:  8,637 (7.04%)
>=  6 shared grams:  5,617 (4.58%)
>=  8 shared grams:  2,546 (2.08%)
>= 10 shared grams:  1,165 (0.95%)

In [171]:
# ---------------------------------------------------------
# Diagnose the 41,272 cross-script pairs missed by
# the >=1 transliterated 3-gram blocker
# ---------------------------------------------------------

missed_translit_3gram_pairs = []

for i, (s1_id, s2_id) in enumerate(cross_script_true_pairs):

    s1_name = s1_name_lookup.get(s1_id)
    s2_name = cross_s2_names.get(s2_id)

    if pd.isna(s1_name) or pd.isna(s2_name):
        continue

    s1_translit = transliterate_name(s1_name)
    s2_translit = transliterate_name(s2_name)

    g1 = char_ngrams(s1_translit, 3)
    g2 = char_ngrams(s2_translit, 3)

    if len(g1.intersection(g2)) == 0:
        missed_translit_3gram_pairs.append(
            (s1_id, s2_id, s1_translit, s2_translit)
        )

print(
    "Missed by transliterated 3-gram:",
    len(missed_translit_3gram_pairs)
)

Missed by transliterated 3-gram: 52701

In [172]:
from difflib import SequenceMatcher

two_gram_recovery = 0
prefix3_recovery = 0
prefix4_recovery = 0
prefix5_recovery = 0

similarities = []

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    g1 = char_ngrams(s1_name, 2)
    g2 = char_ngrams(s2_name, 2)

    if g1.intersection(g2):
        two_gram_recovery += 1

    if len(s1_name) >= 3 and len(s2_name) >= 3:
        if s1_name[:3] == s2_name[:3]:
            prefix3_recovery += 1

    if len(s1_name) >= 4 and len(s2_name) >= 4:
        if s1_name[:4] == s2_name[:4]:
            prefix4_recovery += 1

    if len(s1_name) >= 5 and len(s2_name) >= 5:
        if s1_name[:5] == s2_name[:5]:
            prefix5_recovery += 1

    similarities.append(
        SequenceMatcher(
            None,
            s1_name,
            s2_name
        ).ratio()
    )

print("Missed pairs:", len(missed_translit_3gram_pairs))

print(
    ">=1 shared 2-gram:",
    two_gram_recovery,
    f"({two_gram_recovery / len(missed_translit_3gram_pairs):.2%})"
)

print(
    "Same 3-char prefix:",
    prefix3_recovery,
    f"({prefix3_recovery / len(missed_translit_3gram_pairs):.2%})"
)

print(
    "Same 4-char prefix:",
    prefix4_recovery,
    f"({prefix4_recovery / len(missed_translit_3gram_pairs):.2%})"
)

print(
    "Same 5-char prefix:",
    prefix5_recovery,
    f"({prefix5_recovery / len(missed_translit_3gram_pairs):.2%})"
)

print(
    "\nSimilarity:"
)

print(
    pd.Series(similarities).describe()
)

Missed pairs: 52701
>=1 shared 2-gram: 41388 (78.53%)
Same 3-char prefix: 151 (0.29%)
Same 4-char prefix: 0 (0.00%)
Same 5-char prefix: 0 (0.00%)

Similarity:
count    52701.000000
mean         0.303821
std          0.088745
min          0.042553
25%          0.244898
50%          0.303030
75%          0.357143
max          0.727273
dtype: float64

In [173]:
shared_2gram_counts = []

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    g1 = char_ngrams(s1_name, 2)
    g2 = char_ngrams(s2_name, 2)

    shared_2gram_counts.append(
        len(g1.intersection(g2))
    )

shared_2gram_series = pd.Series(shared_2gram_counts)

print(shared_2gram_series.describe())

print("\nRecovery at each threshold:")

for threshold in [1, 2, 3, 4, 5, 6, 8, 10]:
    recovered = (
        shared_2gram_series >= threshold
    ).sum()

    print(
        f">= {threshold:2d} shared 2-grams: "
        f"{recovered:6,} "
        f"({recovered / len(shared_2gram_series):.2%})"
    )

count    52701.000000
mean         1.404926
std          1.086914
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          7.000000
dtype: float64

Recovery at each threshold:
>=  1 shared 2-grams: 41,388 (78.53%)
>=  2 shared 2-grams: 22,163 (42.05%)
>=  3 shared 2-grams:  7,996 (15.17%)
>=  4 shared 2-grams:  2,055 (3.90%)
>=  5 shared 2-grams:    400 (0.76%)
>=  6 shared 2-grams:     34 (0.06%)
>=  8 shared 2-grams:      0 (0.00%)
>= 10 shared 2-grams:      0 (0.00%)

In [174]:
from collections import defaultdict

translit_2gram_index = defaultdict(list)

for s2_id in cross_script_s2_ids:

    name = cross_s2_names.get(s2_id)

    if pd.isna(name):
        continue

    translit = transliterate_name(name)

    grams = char_ngrams(translit, 2)

    for gram in grams:
        translit_2gram_index[gram].append(s2_id)

print(
    "2-gram index keys:",
    len(translit_2gram_index)
)

2-gram index keys: 1166

In [176]:
print("cross_script_true_pairs:", type(cross_script_true_pairs))
print("cross_script_true_pairs:", len(cross_script_true_pairs))
print("cross_script_s2_names:", len(cross_s2_names))

cross_script_true_pairs: <class 'list'>
cross_script_true_pairs: 122682
cross_script_s2_names: 122682

In [181]:
cross_script_s2_names = {}

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["entity_id", "business_name"],
    chunksize=200_000,
    dtype="string"
):

    mask = chunk["entity_id"].isin(cross_script_s2_ids)

    for row in chunk.loc[mask].itertuples(index=False):
        cross_script_s2_names[row.entity_id] = row.business_name

    del chunk
    gc.collect()

print(
    "S2 names loaded:",
    len(cross_script_s2_names)
)

S2 names loaded: 122682

In [182]:
from collections import Counter

translit_2gram_frequency = Counter()

for s2_id in cross_script_s2_ids:

    name = cross_script_s2_names.get(s2_id)

    if not name:
        continue

    translit = transliterate_name(name)

    grams = char_ngrams(translit, 2)

    for gram in grams:
        translit_2gram_frequency[gram] += 1

print(
    "Unique transliterated 2-grams:",
    len(translit_2gram_frequency)
)

print("\nRarest 20:")

for gram, freq in sorted(
    translit_2gram_frequency.items(),
    key=lambda x: x[1]
)[:20]:
    print(repr(gram), freq)

print("\nMost common 20:")

for gram, freq in translit_2gram_frequency.most_common(20):
    print(repr(gram), freq)

Unique transliterated 2-grams: 1166

Rarest 20:
'iw' 1
'lṣ' 1
'uऑ' 1
'ḍṣ' 1
'jś' 1
'wg' 1
'xh' 1
'wf' 1
'kୱ' 1
'kf' 1
'ൺḍ' 1
'tṟ' 1
'df' 1
'~j' 1
'ൺt' 1
'ṟf' 1
'ṃò' 1
'ർy' 1
'ൺy' 1
'èā' 1

Most common 20:
'li' 106192
'im' 95392
'mi' 94251
'pr' 90042
'iṭ' 85963
'iv' 77256
'al' 76072
've' 75529
'eṭ' 74869
'rā' 74390
'eḍ' 73202
'ḍa' 71398
'ṭe' 70389
'ṭa' 69113
'ap' 65625
'āi' 60159
'ra' 52564
'sa' 47477
'ar' 47468
'ai' 43321

In [183]:
rare_thresholds = [1, 2, 5, 10, 25, 50, 100, 250, 500, 1000]

hard_pair_stats = {
    threshold: 0
    for threshold in rare_thresholds
}

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    grams = char_ngrams(s2_name, 2)

    gram_freqs = [
        translit_2gram_frequency.get(g, 10**9)
        for g in grams
    ]

    for threshold in rare_thresholds:

        # At least one rare 2-gram
        if any(freq <= threshold for freq in gram_freqs):
            hard_pair_stats[threshold] += 1

print("Hard-pair recovery using >=1 rare S2 2-gram:\n")

for threshold in rare_thresholds:

    recovered = hard_pair_stats[threshold]

    print(
        f"freq <= {threshold:4d}: "
        f"{recovered:6,} "
        f"({recovered / len(missed_translit_3gram_pairs):.2%})"
    )

Hard-pair recovery using >=1 rare S2 2-gram:

freq <=    1:     20 (0.04%)
freq <=    2:     45 (0.09%)
freq <=    5:    146 (0.28%)
freq <=   10:    340 (0.65%)
freq <=   25:    998 (1.89%)
freq <=   50:  2,357 (4.47%)
freq <=  100:  5,374 (10.20%)
freq <=  250: 11,276 (21.40%)
freq <=  500: 16,975 (32.21%)
freq <= 1000: 24,124 (45.78%)

In [184]:
from difflib import SequenceMatcher

hard_pair_similarities = []

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    sim = SequenceMatcher(
        None,
        s1_name,
        s2_name
    ).ratio()

    hard_pair_similarities.append(sim)

sim_series = pd.Series(hard_pair_similarities)

print(sim_series.describe())

print("\nRecovery at similarity thresholds:")

for threshold in [
    0.30, 0.35, 0.40, 0.45,
    0.50, 0.55, 0.60, 0.65,
    0.70
]:

    recovered = (
        sim_series >= threshold
    ).sum()

    print(
        f">= {threshold:.2f}: "
        f"{recovered:6,} "
        f"({recovered / len(sim_series):.2%})"
    )

count    52701.000000
mean         0.303821
std          0.088745
min          0.042553
25%          0.244898
50%          0.303030
75%          0.357143
max          0.727273
dtype: float64

Recovery at similarity thresholds:
>= 0.30: 27,202 (51.62%)
>= 0.35: 14,920 (28.31%)
>= 0.40:  6,929 (13.15%)
>= 0.45:  2,924 (5.55%)
>= 0.50:  1,418 (2.69%)
>= 0.55:    566 (1.07%)
>= 0.60:    188 (0.36%)
>= 0.65:     27 (0.05%)
>= 0.70:      5 (0.01%)

In [186]:
print("missed_translit_3gram_pairs:", len(missed_translit_3gram_pairs))
print(
    "cross_script_true_pairs:",
    len(cross_script_true_pairs)
)

missed_translit_3gram_pairs: 52701
cross_script_true_pairs: 122682

In [187]:
# Rebuild the exact set of cross-script true pairs
# that have ZERO shared transliterated 3-grams.

missed_translit_3gram_pairs = []

for s1_id, s2_id in cross_script_true_pairs:

    s1_name = s1_name_lookup.get(s1_id)
    s2_name = cross_script_s2_names.get(s2_id)

    if not s1_name or not s2_name:
        continue

    s1_translit = transliterate_name(s1_name)
    s2_translit = transliterate_name(s2_name)

    g1 = char_ngrams(s1_translit, 3)
    g2 = char_ngrams(s2_translit, 3)

    if not g1.intersection(g2):
        missed_translit_3gram_pairs.append(
            (
                s1_id,
                s2_id,
                s1_translit,
                s2_translit
            )
        )

print(
    "Exact hard-pair population:",
    len(missed_translit_3gram_pairs)
)

print(
    "Recovered by >=1 transliterated 3-gram:",
    len(cross_script_true_pairs)
    - len(missed_translit_3gram_pairs)
)

Exact hard-pair population: 52701
Recovered by >=1 transliterated 3-gram: 69981

In [188]:
shared_2gram_counts = []

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    g1 = char_ngrams(s1_name, 2)
    g2 = char_ngrams(s2_name, 2)

    shared_2gram_counts.append(
        len(g1.intersection(g2))
    )

shared_2gram_series = pd.Series(shared_2gram_counts)

print(shared_2gram_series.describe())

print("\nRecovery:")

for threshold in [1, 2, 3, 4, 5, 6]:
    recovered = (
        shared_2gram_series >= threshold
    ).sum()

    print(
        f">= {threshold} shared 2-grams: "
        f"{recovered:,} "
        f"({recovered / len(shared_2gram_series):.2%})"
    )

count    52701.000000
mean         1.404926
std          1.086914
min          0.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          7.000000
dtype: float64

Recovery:
>= 1 shared 2-grams: 41,388 (78.53%)
>= 2 shared 2-grams: 22,163 (42.05%)
>= 3 shared 2-grams: 7,996 (15.17%)
>= 4 shared 2-grams: 2,055 (3.90%)
>= 5 shared 2-grams: 400 (0.76%)
>= 6 shared 2-grams: 34 (0.06%)

In [189]:
id="m8v4k2"
pair_stats = []

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    g1 = char_ngrams(s1_name, 2)
    g2 = char_ngrams(s2_name, 2)

    shared = len(g1 & g2)

    if min(len(g1), len(g2)) > 0:
        density = shared / min(len(g1), len(g2))
    else:
        density = 0.0

    pair_stats.append(
        (shared, density)
    )

pair_stats_df = pd.DataFrame(
    pair_stats,
    columns=["shared_2grams", "density"]
)

print(pair_stats_df.describe())

print("\nRecovery by density, requiring >=2 shared 2-grams:")

for threshold in [
    0.05,
    0.10,
    0.15,
    0.20,
    0.25,
    0.30,
    0.40,
    0.50
]:

    mask = (
        (pair_stats_df["shared_2grams"] >= 2)
        &
        (pair_stats_df["density"] >= threshold)
    )

    recovered = mask.sum()

    print(
        f"density >= {threshold:.2f}: "
        f"{recovered:6,} "
        f"({recovered / len(pair_stats_df):.2%})"
    )

       shared_2grams       density
count   52701.000000  52701.000000
mean        1.404926      0.117807
std         1.086914      0.090209
min         0.000000      0.000000
25%         1.000000      0.062500
50%         1.000000      0.111111
75%         2.000000      0.166667
max         7.000000      1.000000

Recovery by density, requiring >=2 shared 2-grams:
density >= 0.05: 22,163 (42.05%)
density >= 0.10: 22,010 (41.76%)
density >= 0.15: 16,895 (32.06%)
density >= 0.20: 10,324 (19.59%)
density >= 0.25:  5,079 (9.64%)
density >= 0.30:  1,946 (3.69%)
density >= 0.40:    259 (0.49%)
density >= 0.50:     61 (0.12%)

In [190]:
# Recalculate transliterated character similarity
# for the authoritative 52,701 hard pairs.

from difflib import SequenceMatcher

hard_similarity = []

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    sim = SequenceMatcher(
        None,
        s1_name,
        s2_name
    ).ratio()

    hard_similarity.append(sim)

hard_similarity = pd.Series(hard_similarity)

print(hard_similarity.describe())

count    52701.000000
mean         0.303821
std          0.088745
min          0.042553
25%          0.244898
50%          0.303030
75%          0.357143
max          0.727273
dtype: float64

In [191]:
hard_shared = pair_stats_df["shared_2grams"]

print("Combined recovery:\n")

for sim_threshold in [
    0.35,
    0.40,
    0.45,
    0.50,
    0.55
]:

    for gram_threshold in [1, 2, 3]:

        mask = (
            (hard_shared >= gram_threshold)
            |
            (hard_similarity >= sim_threshold)
        )

        recovered = mask.sum()

        print(
            f"grams >= {gram_threshold} OR "
            f"sim >= {sim_threshold:.2f}: "
            f"{recovered:6,} "
            f"({recovered / len(hard_similarity):.2%})"
        )

    print()

Combined recovery:

grams >= 1 OR sim >= 0.35: 42,293 (80.25%)
grams >= 2 OR sim >= 0.35: 26,933 (51.11%)
grams >= 3 OR sim >= 0.35: 18,287 (34.70%)

grams >= 1 OR sim >= 0.40: 41,757 (79.23%)
grams >= 2 OR sim >= 0.40: 24,134 (45.79%)
grams >= 3 OR sim >= 0.40: 12,602 (23.91%)

grams >= 1 OR sim >= 0.45: 41,510 (78.77%)
grams >= 2 OR sim >= 0.45: 22,915 (43.48%)
grams >= 3 OR sim >= 0.45:  9,826 (18.64%)

grams >= 1 OR sim >= 0.50: 41,433 (78.62%)
grams >= 2 OR sim >= 0.50: 22,510 (42.71%)
grams >= 3 OR sim >= 0.50:  8,924 (16.93%)

grams >= 1 OR sim >= 0.55: 41,396 (78.55%)
grams >= 2 OR sim >= 0.55: 22,225 (42.17%)
grams >= 3 OR sim >= 0.55:  8,302 (15.75%)

In [192]:
target_mask = (
    (pair_stats_df["shared_2grams"] < 3)
    &
    (hard_similarity < 0.40)
)

hard_remaining = pair_stats_df[target_mask].copy()

print(
    "Pairs missed by combined rule:",
    len(hard_remaining)
)

print(
    "\nSimilarity distribution:"
)

print(
    hard_similarity[target_mask].describe()
)

print(
    "\nShared 2-gram distribution:"
)

print(
    pair_stats_df.loc[
        target_mask,
        "shared_2grams"
    ].value_counts().sort_index()
)

Pairs missed by combined rule: 40099

Similarity distribution:
count    40099.000000
mean         0.275193
std          0.066983
min          0.042553
25%          0.230769
50%          0.280702
75%          0.326531
max          0.395062
dtype: float64

Shared 2-gram distribution:
shared_2grams
0    10944
1    17623
2    11532
Name: count, dtype: int64

In [193]:
borderline = pair_stats_df[
    (pair_stats_df["shared_2grams"] < 3) &
    (hard_similarity >= 0.30) &
    (hard_similarity < 0.40)
].copy()

print(
    "Borderline pairs:",
    len(borderline)
)

print(
    borderline["shared_2grams"].value_counts().sort_index()
)

print(
    hard_similarity[
        (pair_stats_df["shared_2grams"] < 3) &
        (hard_similarity >= 0.30) &
        (hard_similarity < 0.40)
    ].describe()
)

Borderline pairs: 16180
shared_2grams
0    1923
1    7037
2    7220
Name: count, dtype: int64
count    16180.000000
mean         0.339335
std          0.025791
min          0.300000
25%          0.318182
50%          0.333333
75%          0.358974
max          0.395062
dtype: float64

In [194]:
print("Fine-grained thresholds:\n")

for threshold in [
    0.36, 0.37, 0.38, 0.39,
    0.395, 0.40
]:

    mask = (
        (pair_stats_df["shared_2grams"] >= 3)
        |
        (hard_similarity >= threshold)
    )

    recovered = mask.sum()

    print(
        f"grams >=3 OR sim >= {threshold:.3f}: "
        f"{recovered:6,} "
        f"({recovered / len(hard_similarity):.2%})"
    )

Fine-grained thresholds:

grams >=3 OR sim >= 0.360: 16,469 (31.25%)
grams >=3 OR sim >= 0.370: 15,173 (28.79%)
grams >=3 OR sim >= 0.380: 13,985 (26.54%)
grams >=3 OR sim >= 0.390: 13,072 (24.80%)
grams >=3 OR sim >= 0.395: 12,603 (23.91%)
grams >=3 OR sim >= 0.400: 12,602 (23.91%)

In [195]:
# Analyze the pairs that are captured by similarity >= 0.390
# but NOT by >=3 shared 2-grams.

sim_only_mask = (
    (hard_similarity >= 0.390)
    &
    (pair_stats_df["shared_2grams"] < 3)
)

sim_only = pair_stats_df[sim_only_mask].copy()

sim_only["similarity"] = hard_similarity[sim_only_mask].values

print("Similarity-only pairs:", len(sim_only))

print("\nShared 2-gram distribution:")
print(
    sim_only["shared_2grams"]
    .value_counts()
    .sort_index()
)

print("\nSimilarity:")
print(sim_only["similarity"].describe())

Similarity-only pairs: 5076

Shared 2-gram distribution:
shared_2grams
0     379
1    1738
2    2959
Name: count, dtype: int64

Similarity:
count    5076.000000
mean        0.445991
std         0.051847
min         0.390244
25%         0.409091
50%         0.428571
75%         0.470588
max         0.705882
Name: similarity, dtype: float64

In [196]:
print("\nSimilarity by shared 2-gram count:")

print(
    sim_only.groupby("shared_2grams")["similarity"]
    .describe()
)

Similarity by shared 2-gram count:
                count      mean       std       min       25%       50%  \
shared_2grams
0               379.0  0.438334  0.040579  0.390244  0.400000  0.424242
1              1738.0  0.443087  0.045516  0.390244  0.410256  0.428571
2              2959.0  0.448677  0.056261  0.390244  0.409091  0.428571

                    75%       max
shared_2grams
0              0.466667  0.571429
1              0.470588  0.666667
2              0.473684  0.705882

In [197]:
# ---------------------------------------------------------
# For similarity-only true pairs, determine whether they
# contain rare transliterated 2-grams.
# ---------------------------------------------------------

sim_only_pairs = []

for s1_id, s2_id, s1_name, s2_name in missed_translit_3gram_pairs:

    # Recompute only the condition we're interested in
    sim = SequenceMatcher(
        None,
        s1_name,
        s2_name
    ).ratio()

    shared = len(
        char_ngrams(s1_name, 2)
        &
        char_ngrams(s2_name, 2)
    )

    if sim >= 0.390 and shared < 3:
        sim_only_pairs.append(
            (s1_id, s2_id, s1_name, s2_name)
        )

print(
    "Similarity-only pairs:",
    len(sim_only_pairs)
)

Similarity-only pairs: 5076

In [198]:
rare_anchor_thresholds = [10, 25, 50, 100, 250, 500, 1000]

print("\nSimilarity-only recovery using an S2 2-gram with frequency <= threshold:\n")

for threshold in rare_anchor_thresholds:

    recovered = 0

    for s1_id, s2_id, s1_name, s2_name in sim_only_pairs:

        s2_grams = char_ngrams(s2_name, 2)

        if any(
            translit_2gram_frequency.get(g, 10**9)
            <= threshold
            for g in s2_grams
        ):
            recovered += 1

    print(
        f"freq <= {threshold:4d}: "
        f"{recovered:5,} "
        f"({recovered / len(sim_only_pairs):.2%})"
    )

Similarity-only recovery using an S2 2-gram with frequency <= threshold:

freq <=   10:    21 (0.41%)
freq <=   25:    76 (1.50%)
freq <=   50:   135 (2.66%)
freq <=  100:   383 (7.55%)
freq <=  250:   823 (16.21%)
freq <=  500: 1,349 (26.58%)
freq <= 1000: 1,972 (38.85%)

In [199]:
print("s1_name_lookup:", len(s1_name_lookup))
print("cross_script_s2_names:", len(cross_script_s2_names))

s1_name_lookup: 2206821
cross_script_s2_names: 122682

In [200]:
id="f3m8q1"
missed_s2_names = {}

for chunk in pd.read_csv(
    S2_PATH,
    sep="\t",
    usecols=["entity_id", "name_core"],
    chunksize=200_000,
    dtype="string"
):

    mask = chunk["entity_id"].isin(missed_s2_ids)

    for row in chunk.loc[mask].itertuples(index=False):
        missed_s2_names[row.entity_id] = row.name_core

    del chunk
    gc.collect()

print(
    "Remaining missed S2 names:",
    len(missed_s2_names)
)

Remaining missed S2 names: 471214

In [201]:
id="r8v2k6"
from itertools import combinations

def name_token_pairs(name):

    tokens = sorted(
        set(meaningful_tokens(name))
    )

    if len(tokens) < 2:
        return set()

    return set(
        combinations(tokens, 2)
    )

In [202]:
id="w4n7p3"
two_token_recovered = 0
two_token_evaluable = 0

for s1_id, true_ids in gt_lookup.items():

    for s2_id in true_ids:

        # Only remaining misses
        if s2_id not in missed_s2_ids:
            continue

        s1_name = s1_name_lookup.get(s1_id)
        s2_name = missed_s2_names.get(s2_id)

        if pd.isna(s1_name) or pd.isna(s2_name):
            continue

        s1_pairs = name_token_pairs(s1_name)
        s2_pairs = name_token_pairs(s2_name)

        two_token_evaluable += 1

        if s1_pairs.intersection(s2_pairs):
            two_token_recovered += 1

print(
    "True pairs evaluated:",
    two_token_evaluable
)

print(
    "Recovered by >=1 shared token pair:",
    two_token_recovered
)

print(
    "Recall:",
    two_token_recovered / two_token_evaluable
)

True pairs evaluated: 471212
Recovered by >=1 shared token pair: 174899
Recall: 0.37116839129733536

In [203]:
from collections import Counter

two_token_frequency = Counter()

for s2_id, name in missed_s2_names.items():

    if pd.isna(name):
        continue

    pairs = name_token_pairs(name)

    for pair in pairs:
        two_token_frequency[pair] += 1

print(
    "Unique token pairs:",
    len(two_token_frequency)
)

print("\nRarest 20:")

for pair, freq in sorted(
    two_token_frequency.items(),
    key=lambda x: x[1]
)[:20]:
    print(pair, freq)

print("\nMost common 20:")

for pair, freq in two_token_frequency.most_common(20):
    print(pair, freq)

Unique token pairs: 362476

Rarest 20:
('clean', 'crestline') 1
('keystone', 'odyssey') 1
('fog1eman', 'lambert') 1
('fog1eman', 'lewis') 1
('apple', 'optimal') 1
('medf0rd', 'optimal') 1
('apple', 'medf0rd') 1
('centre', 'strategic') 1
('egnivonmntal', 'great') 1
('systems', 'xl') 1
('prvstbae', 'traders') 1
('prvstbae', 'unified') 1
('dávidson', 'rich') 1
('com', 'glyphifylaw') 1
('furniture', 'pioberce') 1
('continental', 'éndocrinology') 1
('dream', 'htopotl') 1
('com', 'kaseyherediatailwind') 1
('berry', 'saul') 1
('fúnure', 'vanguard') 1

Most common 20:
('इव', 'यर') 4629
('इव', 'सल') 3343
('इन', 'इव') 3199
('इन', 'टम') 2958
('इव', 'रक') 2848
('इव', 'टम') 2739
('इव', 'चर') 2448
('टरन', 'शनल') 2389
('com', 'www') 2137
('इव', 'वर') 2003
('इव', 'सर') 1825
('इव', 'शन') 1796
('റഡ', 'വറ') 1711
('चर', 'रक') 1686
('टव', 'यर') 1553
('इट', 'इव') 1545
('एक', 'सप') 1521
('इव', 'जन') 1506
('थक', 'यर') 1499
('इम', 'इव') 1492

In [204]:
thresholds = [
    1, 2, 5, 10,
    25, 50, 100,
    250, 500, 1000
]

recovery = {
    t: 0
    for t in thresholds
}

for s1_id, true_ids in gt_lookup.items():

    for s2_id in true_ids:

        if s2_id not in missed_s2_ids:
            continue

        s1_name = s1_name_lookup.get(s1_id)
        s2_name = missed_s2_names.get(s2_id)

        if pd.isna(s1_name) or pd.isna(s2_name):
            continue

        s1_pairs = name_token_pairs(s1_name)
        s2_pairs = name_token_pairs(s2_name)

        shared_pairs = s1_pairs.intersection(s2_pairs)

        if not shared_pairs:
            continue

        # Rarest shared pair
        min_freq = min(
            two_token_frequency.get(pair, 10**9)
            for pair in shared_pairs
        )

        for t in thresholds:
            if min_freq <= t:
                recovery[t] += 1

print("\nRecovery using at least one shared token-pair:")

for t in thresholds:
    print(
        f"freq <= {t:4d}: "
        f"{recovery[t]:7,} "
        f"({recovery[t] / 471212:.2%})"
    )

Recovery using at least one shared token-pair:
freq <=    1:  39,744 (8.43%)
freq <=    2:  63,602 (13.50%)
freq <=    5: 104,450 (22.17%)
freq <=   10: 136,898 (29.05%)
freq <=   25: 155,552 (33.01%)
freq <=   50: 158,317 (33.60%)
freq <=  100: 163,144 (34.62%)
freq <=  250: 166,796 (35.40%)
freq <=  500: 168,518 (35.76%)
freq <= 1000: 169,168 (35.90%)

In [205]:
# ---------------------------------------------------------
# Build a rare two-token-pair index.
# Only token pairs appearing <= 5 times are retained.
# ---------------------------------------------------------

RARE_PAIR_MAX_FREQ = 5

rare_two_token_index = defaultdict(list)

for s2_id, name in missed_s2_names.items():

    if pd.isna(name):
        continue

    pairs = name_token_pairs(name)

    for pair in pairs:

        if two_token_frequency[pair] <= RARE_PAIR_MAX_FREQ:
            rare_two_token_index[pair].append(s2_id)

print(
    "Rare token-pair index keys:",
    len(rare_two_token_index)
)

print(
    "Indexed S2 references:",
    sum(
        len(v)
        for v in rare_two_token_index.values()
    )
)

Rare token-pair index keys: 343023
Indexed S2 references: 440527

In [206]:
candidate_counts = []

for s1_id, true_ids in gt_lookup.items():

    # Only S1s with remaining missed S2 matches
    remaining_true = true_ids.intersection(
        missed_s2_ids
    )

    if not remaining_true:
        continue

    s1_name = s1_name_lookup.get(s1_id)

    if pd.isna(s1_name):
        continue

    s1_pairs = name_token_pairs(s1_name)

    candidates = set()

    for pair in s1_pairs:

        if pair in rare_two_token_index:
            candidates.update(
                rare_two_token_index[pair]
            )

    candidate_counts.append(
        len(candidates)
    )

candidate_series = pd.Series(candidate_counts)

print(candidate_series.describe())

print(
    "\nTotal candidate references:",
    candidate_series.sum()
)

print(
    "S1 entities evaluated:",
    len(candidate_series)
)

print(
    "S1 entities with candidates:",
    (candidate_series > 0).sum()
)

count    348965.000000
mean          1.751319
std           2.279004
min           0.000000
25%           0.000000
50%           1.000000
75%           3.000000
max          21.000000
dtype: float64

Total candidate references: 611149
S1 entities evaluated: 348965
S1 entities with candidates: 182010